### ISSUE TITLE
Option to disable for certain folders - eg node_modules

### ISSUE THREAD

**Issue by SteveALee** [prettier/prettier-vscode#198] opened 2017-08-14 15:44 UTC
Occaisonally you need to patch packages that have been installed (and patch-package is useful here). However, if format on save is enabled yo uget more changes that you actually want.

So it would be vey useful  to be able to stop it working in some places.

As far as I can see, VS code does not have such a feature itself.

**Comment by CiGit** [comment] 2017-08-15 14:00
This is something we will do 
It is done in prettier (master) through a _.prettierignore_ file. It should be in next version (1.6)
We also want to do that but it there is still no PR for that.
Do you want to do it?

Duplicate of #57

**Closed** 2017-09-30 07:49 UTC
Labels: duplicate
