### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kwameopareasiedu** [prettier/prettier-vscode#820] opened 2019-04-30 22:57 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.9.0`
- OS Version: `Linux x64 4.15.0-48-generic`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3133403/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by ntotten** [comment] 2019-08-12 17:37
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:37 UTC
Labels: performance
