### ISSUE TITLE
Add support for VSCode Web or codespaces

### ISSUE THREAD

**Issue by shivapoudel** [prettier/prettier-vscode#2142] opened 2021-08-18 14:39 UTC
I'm often using VSCode web on GitHub and would love to have the same feature available.

**Comment by ntotten** [comment] 2021-08-18 21:53
I've used it in codespaces a fair bit. What problems are you seeing?

**Comment by shivapoudel** [comment] 2021-08-19 03:55
This ticket for PHPDocblocker might help https://github.com/neild3r/vscode-php-docblocker/issues/176

**Comment by ntotten** [comment] 2021-08-19 23:58
I'm not going on a hunt for issues. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by hatala91** [comment] 2021-09-02 06:17
I, too, have this problem and can elaborate a bit:

I am using Codespaces/ VS Code Web by typing "." (dot) in any GitHub Repo. There in the UI one can navigate to the Extensions Marketplace on the left and search for "Prettier - Code formatter". However, the Plugin is greyed out with this info text: `The 'Prettier - Code formatter' extension is not available in VS Code Web.`

Hope this helps 🙏 

![image](https://user-images.githubusercontent.com/19345882/131791584-e12281f5-c413-4d12-ac54-8173625e865e.png)

**Comment by ntotten** [comment] 2021-09-02 13:23
This is a duplicate of #1938

**Closed** 2021-09-02 13:23 UTC
