### ISSUE TITLE
Vue template garbled when tag ends on new line

### ISSUE THREAD

**Issue by hyvyys** [prettier/prettier-vscode#923] opened 2019-08-24 20:16 UTC
### Summary

I've had an issue when trying to quick fix a code snippet where the `>` of the opening vue tag was on a new line to allow one attribute per line. I know Prettier doesn't support multi-line... anything (shucks!), so I'll probably just stop using it (after 5 minutes' trial), but here's something that shouldn't happen so I thought I'll let you know.

### Steps To Reproduce:

My code:

```vue
<template>
  <div class="nav">
    <router-link
      v-for="kind in textKinds"
      :key="kind"
      :to="`/${kind}`"
    >{{ navlinkText(kind) }}</router-link>
  </div>
</template>
```

### Expected result

```vue
<template>
  <div class="nav">
    <router-link v-for="kind in textKinds" :key="kind" :to="`/${kind}`">
      {{ navlinkText(kind) }}
    </router-link>
  </div>
</template>
```

### Actual result

After applying quick fix:

```vue
<template>
  <div class="nav">
    <router-link
      v-for="kind in textKinds"
      :key="kind"
      :to="`/${kind}`"
      navlinkText(kind)
    }}</router-link>
  </div>
</template>
```

### Additional information

**VS Code Version**:
1.37.1

**Prettier & Prettier Plugin Version**:
"prettier": "^1.18.2",
"eslint-plugin-prettier": "^3.1.0",

**OS and version**:
Windows 10

**Comment by ntotten** [comment] 2019-08-26 11:59
This is our parser inference. The extension is likely not detecting the type of the file correctly. As a workaround, you can specify the parser in a prettier config file "overrides" property and set the parser. See: https://prettier.io/docs/en/options.html#parser

{
	// ...
	"overrides":[{
		"files": "*.html", // replace this by more specific extension if needed
      	"options": {
        	"parser": "html"
      	}
	}]
}

Duplicate of #487

**Closed by ntotten** 2019-08-26 11:59 UTC
