### ISSUE TITLE
[typescript] unfolds unrelated code block after format

### ISSUE THREAD

**Issue by chriswep** [prettier/prettier-vscode#264] opened 2017-11-17 14:10 UTC
I tried some time to figure out what type of code structure triggers this. It seems to only happen on complex and/or long typescript files. On those files where it happens, it happens consistently on formatting with prettier (no file save required). There needs to be a change made. If then the prettier action is executed the editor unfolds unrelated code blocks, mostly after the change being made.

If the extension is disabled (using the default typescript vscode formatter) the issue goes away.

**Comment by RobinMalfait** [comment] 2017-11-17 17:49
I think that your problem relates to the following problem #173 and #134 : Currently, if you select something and format it, the whole file is still formatted if I'm not mistaken.

**Comment by RobinMalfait** [comment] 2017-11-18 11:49
Going to mark this as a duplicate for now. If this is not correct please respond to this issue.

Duplicate of #173, #134 and #137

**Closed by RobinMalfait** 2017-11-18 11:49 UTC

**Comment by chriswep** [comment] 2017-11-18 19:12
don't know.. but at least from a practical viewpoint the issue is not related to formatting of selections (like all the mentioned issues). this issue happens when formatting the whole file:
- the file is formatted with prettier already
- the file is folded recursively to level 2
- i change one line somewhere (space at the end does the trick)
- completely unrelated blocks of code are unfolded

this does not happen with every file. as i said, i unfortunately couldn't find out (even after some trying) what type of code / structure in the files exactly triggers the issue. I also can't see a pattern in what is unfolded and what not. What i can say is, that prettier did no change in the blocks that are unfolded.
