### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by luhar63** [prettier/prettier-vscode#776] opened 2019-04-03 09:24 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 15.6.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/rahulmaurya/esbenp.prettier-vs code-unresponsive.cpuprofile.txt` :warning:
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3037862/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment] 2019-08-12 17:36
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:36 UTC
Labels: performance
