### ISSUE TITLE
Typescript React - can't find scoped modules

### ISSUE THREAD

**Issue by TidyIQ** [prettier/prettier-vscode#860] opened 2019-06-26 03:50 UTC
Running `tsc` in the cli works without issues. This error only occurs in vscode, only for scoped modules, and only for Typescript React files

For example,

**In src/app.tsx** 

This has no issue:
```
import React from "react";
```
This errors with `Cannot find module '@material-ui/core/CssBaseline'.ts(2307)`
```
import CssBaseline from "@material-ui/core/CssBaseline";
```

**In dist/app.js (after compiling)**
This has no issue:
```
import React from "react";
import CssBaseline from "@material-ui/core/CssBaseline";
```

VSCode settings:
```
{
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.formatOnSave": false
  },
  "[javascriptreact]": {
    "editor.formatOnSave": false
  },
  "[typescript]": {
    "editor.formatOnSave": false
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": false
  },
  "editor.tabSize": 2,
  "eslint.autoFixOnSave": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    { "language": "typescript", "autoFix": true },
    { "language": "typescriptreact", "autoFix": true }
  ],
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "prettier.eslintIntegration": true,
  "typescript.autoClosingTags": true,
  "typescript.check.npmIsInstalled": false,
  "typescript.format.enable": true,
  "typescript.format.insertSpaceAfterCommaDelimiter": false,
  "typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
  "typescript.format.insertSpaceAfterKeywordsInControlFlowStatements": false,
  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
  "typescript.format.insertSpaceAfterSemicolonInForStatements": false,
  "typescript.format.insertSpaceBeforeAndAfterBinaryOperators": false,
  "typescript.reportStyleChecksAsWarnings": false,
  "typescript.suggest.autoImports": true,
  "typescript.suggest.enabled": true,
  "typescript.suggest.paths": true,
  "typescript.surveys.enabled": false,
  "typescript.tsc.autoDetect": "off",
  "typescript.updateImportsOnFileMove.enabled": "always",
  "typescript.validate.enable": true
}
```

**Comment by deadlyhifi** [comment] 2019-07-16 07:06
I had the same issue - setting `"prettier.eslintIntegration"` to `false` solves it.

Through VSCode bring up settings menu and search for "eslintIntegration", then untick the "Prettier: Eslint Integration" field.

**Comment by ntotten** [comment] 2019-08-12 15:55
Duplicate of #870

**Closed by ntotten** 2019-08-12 15:55 UTC
