### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by matshagam** [prettier/prettier-vscode#700] opened 2019-01-25 10:52 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.7.3`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/dmatveev/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by t1mmen** [comment] 2019-02-07 03:19
I'm having similar issue. This issue appeared after VSCode updated to `1.31.0`


- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

https://gist.github.com/t1mmen/8db415366d541550a4ba39c0c53e5286

**Comment by ntotten** [comment] 2019-08-12 17:35
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:35 UTC
Labels: performance
