### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by frankiefab100** [prettier/prettier-vscode#1493] opened 2020-08-02 00:26 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `2.2.2`
- OS Version: `Windows_NT x64 10.0.14385`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Mr. Eclectique\esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment] 2020-08-05 15:59
Duplicate of #1201

**Closed by ntotten** 2020-08-05 15:59 UTC
