### ISSUE TITLE
Prettier randomly formatting parts of SCSS file inconsistently

### ISSUE THREAD

**Issue by abdullahseba** [prettier/prettier-vscode#644] opened 2018-11-19 18:58 UTC
Hi
I have a long SCSS variables file. The first part of it gets formatted perfectly but then randomly on line 216 it starts frommating inconsistently by ignoring my new lines, adding an extra space after a comment `//` and changes `/* ************************************** */` to `/****************************************/`.

This happens across multiple files but I could not find anything in common with them and where the issue began.
I have included a playground link with my code. Take a look at line 216 onwards and compare it to previous lines.

**Prettier 1.15.2 VSCode Plugin**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAHSgAnTgFQAs4BbOHABQEMwBrHARgDoAGNnACiJhgAcAzklSoA5gEsYRAK4AjZpFKpqsgCbSANhupEBcWdVRSycALR9adAJTY8OAMIQ+ATwBO40TxwAmVowAcOACCapraRDgAyvrUtvgAMuJgCHqqONJQqnCuOACyAJIEcajY2Bg4cTgAatTuKhpwAjgCRBCaaQBmEFoQAO44xjgABgAkxuQA+iquAG6minzQCDCmAjDU8OauTtkwzqviAF5wQzhdrqSa1GcQrpWQUALia8s4UNSk4lCizDgAogAPJA4MZ8Uz8UzvOYaL50UyqZ71OCqebdNo5aiZEEQ0ykCCqagaVGwZamWQQAGrIjUVR9UwAgTMYqlKAiGp1WQNRkskQAMWgMGCvUaEHIN1gTQsUiZUFBpi6sHMGyIwIA5MxmKgNagEWtUAqYAJVTgAIRZDrUTQwADcPNQf3enMaMow6Dd7o9nq93p9vr9-oD6BKUGwcoQSKpNL6QgGrmkFDNcAtVttsoh4adplcNPE0hjMDjCfNlo0Nrtjg06O5rMDtbr9YbnuDZVQuWoXwcaOkrmrfO6ld6TVIG2y4kJOCyT1EUF+PH4QhEw-gdQ0zHEEDE0nEWRhUEaqDWzgaqEgldczB4pA0ZUbt-dzbTYNcyOBAGIOgAWD8AZm-ADZTWLFNQwhPhYTfOAAE5GDgP9v0ApMSzLR9zG7PgGjfSCwG8AB2WRWAQ5NS1TOUsjgME+DQjCcFfP8cO-FQcMIpCSIhL4EVECA32-DoAFZGFkXjmOAlDOXjN9vEYSC-w6eDEyI5C5RhTwVjEuA31YBjIM-YTiJAsEwGcTENNYWQwFUD9dMUiF4EJEzpP8QJ5JY-TTFEZ8EDfD8wGoPiCOckSlI8Hg3I8qA338Mzvw-a4Ar0lCYXIN9zNUMBv0gqzWLBZw4B6Xo3w6Dp9G-WRMtcj5ZGyAqOjARhWCYuLrLBW5MVEdSaMKyD-FYfygPi0i4HI0wWu+dr3z4nDvG8MrRO2XpwponDIN43iPycvqmtCuBnEwqC9pmuU1K2naaL-erVEig6IU5SwTJ6nqrrBXoiEkMbCvejoZtc08q2BTgrC+lCfu7GNhzBchXDazhbC4GGcBwVVn1UVVgTlJGABo4YRsCoDoFHsQo2FMdweHsaouB8blSjXHQuBidJhGyIo8nKYhJnUJphp6dJ1V2I8CBWbBPnOO5+HVTUwWyQ0eNRYR5SQol1GIXl1TpbprHVUMzFJa1qBZdVWyNElw39fcwaoEls2EH1lWtoQSXbatvWNcSimlbBV39ZyvLJe9gd9Yq7JJcD1x9ZGtrJfD9WSbF9mo8luPs1G-XZDmi33bJNPTefZxLZzlO1eOyWjrN5wC8sYvtHofXnteyXa-gGGrG5uVgZ7bArFTFsAHEc+CZ9qBdVB2XXPMompSccAgT7S5dO87wfOVS9MXjWAK3yN8e47TDqteOt4vi+K35ffD319BovotEMCiFl+-HqINYOAn966-+tvnPTA-B+aLUP+0kallbeq8z6QT2mA4+n8zpnxwrxWBsDIHbVMDhH+tFGB-nQYwRB+xupnw-N4fB+DsGmEgqgyS5CsGAJZEvHOMZ-qAxodtUG1BwbZChjDaGMcEbL1XnnJBq9s5IN3nw-Yu9BH7FPiI0wp9xGmHvqwKR8jZHfwURnZeKjZEgKkSA2R0CpHQNkSg1RBNt5GNkbgqRuDZGkOMYw-YNim4tw-kwjuXdWSoGICYTslYQZD0cKQPEuBxgUDbr2eet5F6gXcMOVw+w24ZzUlvPQDwCSxNRD41wCTC6ly3gYeg7k2iZHSeiDODcr4KSAQIaQYBkgCAEMU7saiwpby+F0BpmSTG6y3r0WoUAviiHaRnEOW8CSjVcIMkxSMt623iSY5eu8Rm1DhLMuxphcEMJsiQcg7S6EAyoSGFCwSdnAjBriNhcBOHw0uTzPg0Tai5wzrc8QMS4ldlDhrZJ0BUkPJMZ8zI9z2kp0sAUjIyMEnAu2KCwFHzqm1KNBnKpNTGj1LbvrVpAsM7ouhVw1UPTXB9O+PXXp-TsUM1VKMtqrgE6tWyKSnmKsHbBRWKijWqS8YZzZe0xxMM5RHNCa4u0AB5CwYBJDOBlHKJwtAxW4mkPAVQwJ2B-iEvsyVIqZWUkuPKxVzBvzrTfptKVoq9imBVjq6aqqIRGo1aaplOrGAWo2kA61Jq2U6v8A1J1QrjA5DWNIQqQ8AAiSYvghNFIEnAFhVAIm+DgTEaRySuCyDkbMCIx5PGOE0eNOA8TPjnuEgtha-QPhEPYSIkQcCJD3DgEgTK-HlrlqG0wtaVLGluTsVwex81FsDJEj2TaW0K2oHoYELBHUGqAbuMwg6VgCFIKO6ZA64BMtxAqpgzAVVeoSkuldGhRDAnHRUu0kQfK7h+C2aIgoDB6AcA258pAbi+tPf07tPb-R9rJMOswAhT3fvnTgbqABSXJX7Vi-tXaOnqwHLVgmvd+8De7R2+Gg1ulsZaK0ACFbjJvrRW8W2HaWptzEaSN2w+C7HFTeN9AYS2oAAOrbikNWQ6BHxm9EY0QT9I6cDsFYH+bwvF72ZRwCIRgfAASuUTcm0w7HVBSFWP+3j34HWCbIMJkQ7BeLick6xmTHHIS3GHBoBJunZPybg7k0z+nEM8eYCpoTgCROoG8Npg5pa3kSuurplZzj9jyMBiIAASjmPMqpmNeaTYRkL9S53mtUw+mDZJdNEbzBB2z8XLORfGSl+pNnGAOdQ+4yIIrshhOo++6hEIBAlfGXB0dBWJ2uWq7QWle9X5HpQs15I4zGAIpq1xig+B2ACaSf17wfWWu1a-XYTTo3JtyIm91gbM3mAIMS112lH5Fu0os-gFgm7Gudf67xbbU2b34EPS5A5coNs9j+nswrN2avMNYZDC5HCsZ1d+f1uDss95Pfm6wWWvXvvzcYLLcboOlveFlt+U7cjZZbah5t2WJ3kfjN4tykmAPusCAFe4qI6x4C9lQITo8jQcAzFqKPJoCwliwGaETin2bc1wDnngcrPo8DBhEN4qsnmDKikWHuRUawRymFoDAcQMwzA+aei9eAW86ci9nUziXYApcy7JPukxTyXntJmrz4V0qpfOhbDgQNSyp64BVgL4a6rXWIidCiN1OA9UocO7zxIKlrcTiWXbl1+xdRIhRGanAq8Pcdd51hrLdvlekjF5sSX0uzBSdpWZlUJip3NuXSpU1ogldC-p6r8Xyetdp-GXL4BD19m84IEnJ4UvoAk9vRWgsmJG-rkeOzznXOgyuXb48SQXeBvAkJBoWz3gmhwFA18Yacqt6D879AeUNJ2qB9s4wXiTQp21EXw34fK-TzaEEO1Gdtnvzb5wDPm9tfScYYHgwRYXxDQ99716bnknH-P8VACBkwJvxfBxNclv8IAX96QYxvxYFgDEtU4Z86Af9Z1-18EtMAQQD4DEC0scI-x-AYCt1DpQDwC8tWACE8DDsCCMCwDf9jMmB-w-wyCOsKDqAECqCVg-8aCpIgC0DYDCDf92CD1eIzoGCrsmCWCX9dl0DmDECXszk3trlrl4Y-8YxRDMClDZZ-8TE4CpDWCIDZZYtNDeCkDZZSA10VCdCTDZYbMzCiDRB1CaDrDqD1CAR7DrpDD6RnCnDnCEk3C-9nCsd4YHDDR8caFtw9M5NOMlCADWAPxhCRJedeJANXJ3JQiM8ICADBDmABNYj4p4jEiUJkiURUj9Dv5vxVtUDDdScEikj3BCj9MTDgQ-xoJMjsibQnMmBWA8iQjajwj89gR-ApJmjuCt1edkNqiUj9MvCcBlo-xBiKi3cOixjuj5N+CmAt8XMhiJ02jv5OiP5xiejfCODvBuoWjrQ2iI9FiwimN7tIE9iric0WFZD2ESYFCcBIi5kajLiIiGR1DlDdiliIiBA9D-0ujPiFNjDTC-jQSLCsYrDITUi907CmlbiIiNAnCXCwQCjQT2DPD0TQpkT3C-CSZm4eU4SOM8coBO5zcCBnBFh3IWEiBKMawOd38WT-RP8Cd+QJQ7cDRV9PgNB9gvtVRAsIByQYABZ0ZmgO9VhRxPo78+cQZXIeS25R9NCq4GA5TIgjgzcUIeSM1U8v16s1M5Sgg6lpByAmhBhU5oxsgJwDUJS9gwJT1+Thh0FxMhhFSBQDhjg0iuA5RdStTlshtmA6JeIHtyCIR-TvT9DOA-TPS9TAzbMPVQyt5IyzB6iTFUzltEtMybMYyIy4yAzdt10BMwzGD8zRctSJDsyCzM0TkHiIYnirksZ9DYyKyozSBwSM5MzoSuFYSwQczRB-CMyazGh8dec6Nc8eBwt+zPThQV0oBDM7IcAVEUzZzJyVgw9-NqzFQ5y89yQNA10jFVydz1yqz8DyyVhdypy6zXtGzYYcUFyLhCRJYeSryVhHyjMbYmUXy1zd0mUU5ugwVhyTyV19zVAhzWzLzTyxzSdBUfU7d4AAQVgtUXwBgwRELkK5VkQ8yZzFRlS4NSyRD0wGhyAJQ-oYZVRqBVRuZKLZBU5qKKKaRVBnw6kGKSZKKB42KxZagpcwAGguKEZh1twKYaLLQERxSKLZABLxYERpK1AJL2LOQIB6AABHaQCAeAOS-EXOGi+i3SuVMUi2GinyKAKnI0YylhJvIyii41ESmy-EOy9i08aS08EFPgFy8NeNaSgkdYGENYby5GGincbyuAdYcQDQcyii1QDoay9ihEGYbyo2IKmAaSsgVK0gSqQKiijocQXKVQPQFKminK0QHyPgKy6S4q7sRysWLoDSoOIqwzaSogRgJq7wJq78Jqj8Jq3iJqv8JqmfZNJqqlGiy8JKii8QaS8QDobMcgSa0gUQSaqASiQq8ax4aSugNQda7aNqWKsWbQSqMa9ihoHarKo6iami4cL4aSsGa6pZa6hAaQe65caSqEaSkUgAKzgA1zesOrFicBgDcrerKq7zerlWWukvcpoosBmohufFhogDNlYpopUukpplRpWvYrjFkB0oosivYoEA+Ehtxq+vKpor0AaG+rJqM1+oRgEHRGSGkua12tpoLGgAWrJrkEZrNJeS5qJvYvWCdGkpgHJFUBxv5tOrFgwtqBnyFtqoxslqICFpIBpCFueWqoRgLCFuzHoGksepos0Gkqp2GoopmGEoUrFl6Hoo7i3lP2kFpFMFyhMDIvvO4o6Get0qTFuHVs1njAqvEB7A3NCvduyv9rWFtT3EZsdo1xBrJsrF4GRFVGtsS1tvtr4uHT0DoUYujplwquUtCwarAFS3YykCupGogBl2NvYtNsbwTqCqdwaGRiTuGNJ3iGoGcDaFf1cm0HbrlXmG0DqUaHIpJmVukxyoBFQoNnQlxHbCgBzzX3GTHtrphjltpUXrXUnqJEutnpXoXvEHHoluaGEoMF3v3rVH4E3pnoOCyGPvlD3qXpJieGvtqGnoBHEDPqnq3qvpiHGWHFfs+GOAPsfu-txC+HfovrnyAZvs+D6X-vvvhkgefuPxYVSDAenogaPsQf7GQbgZwHcDzwQZ-uoFftQbwZCgIZfueS1IPtIdnQwZ-tAY1qnpoa-qga+EoYAcTopJmhAHRhAH+q7wEGQFAFqDmhoGfEeGQBAGoBmDANUB4ZAFTksFCuK2lW+GQALBlhAFGrowV0aBK2iCH01zFUkbADqXka+D0E7UoGzFEGHGQAtAirphAHeoEABAfyUZgEiA+DgCrTgHscJD0F4ZcYBE1O+AaAAEV1L4B-HHHeHobLHJGf0zG4n3BYAGNwjkBuoUmIA9A6Nsw+BJHblGhsgZd5Hnw1L-a4BrHqBbHqAYnAmQA9BPh1HCxeGngwm4BIm6r6mnGBb0mpBkAYcQB29wr+l-E7GUAFy9x5G8w4ACAVBBGkAHG9AABfFZoAA.)

**Comment by abdullahseba** [comment] 2018-12-02 19:29
I've figured out why prettier is doing this.
Turns out is doesn't like map keys that are unquoted. This is rather inconvenient especially for numbers and math related maps. It's pretty selective though.
This works fine for example, even though `base` is unquoted:
```scss
$tp-spacers: () !default;
$tp-spacers: map-merge
  (
    base: $tp-spacer-b
    '0': $tp-spacer-0,
    '1': $tp-spacer-1,
    '2': $tp-spacer-2,
    '3': $tp-spacer-3,
    '4': $tp-spacer-4,
    '5': $tp-spacer-5
  ),
  $tp-spacers
);
```
While this causes formatting issues further down:
```scss
$tp-spacers: () !default;
$tp-spacers: map-merge
  (
    base: $tp-spacer-b
    0: $tp-spacer-0,
    1: $tp-spacer-1,
    2: $tp-spacer-2,
    3: $tp-spacer-3,
    4: $tp-spacer-4,
    5: $tp-spacer-5
  ),
  $tp-spacers
);
````

**Comment by appleseedexm** [comment] 2019-07-11 11:04
I'm also having issues with prettier formatting a map (e.g. an angular palette):

base:
```scss
$md-white: (
    50 : #ffffff,
    100 : #ffffff,
    200 : #ffffff,
    400 : #ffffff,
    700 : #ffffff,
    A100 : #ffffff,
    A200 : #ffffff,
    A400 : #ffffff,
    A700 : #ffffff,
    contrast: (
        50 : #000000,
        100 : #000000,
        200 : #000000,
        400 : #000000,
        700 : #000000,
        A100 : #000000,
        A200 : #000000,
        A400 : #000000,
        A700 : #000000,
    )
);
```

prettier:
```scss
$md-white: (50 : #ffffff,
100 : #ffffff,
200 : #ffffff,
400 : #ffffff,
700 : #ffffff,
A100 : #ffffff,
A200 : #ffffff,
A400 : #ffffff,
A700 : #ffffff,
contrast: (50 : #000000,
100 : #000000,
200 : #000000,
400 : #000000,
700 : #000000,
A100 : #000000,
A200 : #000000,
A400 : #000000,
A700 : #000000,
));
```

Would be nice to see a fix for this :)

**Comment by ntotten** [comment] 2019-10-11 14:46
I believe this is now fixed as I cannot reproduce it. Please reopen if you still have this issue.

**Closed by ntotten** 2019-10-11 14:46 UTC
