### ISSUE TITLE
Handlebars in HTML handled differently on vscode and prettier playground

### ISSUE THREAD

**Issue by mgenware** [prettier/prettier-vscode#865] opened 2019-06-30 11:45 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgEsBmACAdAGQjAEMZ1oBfCgHSgB4AHAPjQAsYBbAGz0JLMoU6Aema00CACZUQAGhAQGAqAGdkoYgCdNEAO4AFLQjUpiANwjpJckACNNxMAGs4MAMoNH6KAHNkMTQBXOHl2bgB1VnR4FU8wODdjaPQzaIBPZHAVNXlvFThNGH0HHw5iZExiLnz5ACsVAA8AIQdnVzdiDjh8bzgKqpqQeoa3bx8uOABFQIh4fuqQkE9NfM1MsK4bBk1vGHCrGFZkAA4ABnltiHzwhwZM7bhVsz75AEcZ+GLFExBiFQBaKBwOCSEE2TRwd7oCHFYilcpISoLeT5DjofxBRYqMYTaazPqIgaLGDEWz7SSHZAAJnkAWI6C4YwAwhAOGVMlBoC8QIF8gAVUkmJH5KhAA)
```sh
--parser html
```

**Input:**
```html
{{if .Location}}
<p>{{html .Location}}</p>
{{end}}
```

**Output:**
```html
{{if .Location}}
<p>{{html .Location}}</p>
{{end}}

```

**vscode latest with prettier plugin 1.9.0 installed**
Create a new HTML file, and paste the code above:

**Input:**
```html
{{if .Location}}
<p>{{html .Location}}</p>
{{end}}
```

Save and format with prettier, output:

**Output:**
```html
{{if .Location}}
<p>{{ html.Location }}</p>
{{ end }}

```

The output on vscode looks quite weird and in fact it breaks my golang HTML templates, tried on windows and macos, same results.

**Comment by jcklpe** [comment] 2019-07-02 20:57
Does this extension cover HTML? I thought it only covered JS.

**Comment by mgenware** [comment] 2019-07-04 14:14
@jcklpe I think so, as prettier now officially supports HTML

**Comment by jcklpe** [comment] 2019-07-04 21:04
Is it possible to get some clarification from @CiGit  maybe?

**Comment by CiGit** [comment] 2019-08-12 15:31
This is our parser inference. currently every _HTML_ file are processed with the _angular_ parser where prettier CLI infers it with file extension:
 - .component.html -> angular (code's languageId: html)
 - .html -> html (code's languageId: html)

In the case of an untitled file (a not persisted file) we wouldn't have any chance to be able to differentiate both case.

As a current workaround, you can specify the parser in a prettier config file "overrides" property:
```json5
{
	// ...
	"overrides":[{
		"files": "*.html", // replace this by more specific extension if needed
      	"options": {
        	"parser": "html"
      	}
	}]
}
```

**Comment by ntotten** [comment] 2019-08-12 15:53
Duplicate of #487

**Closed by ntotten** 2019-08-12 15:53 UTC
