### ISSUE TITLE
Cant read prettier.config.js when requiring a shared a config file

### ISSUE THREAD

**Issue by nathanvale** [prettier/prettier-vscode#702] opened 2019-01-28 05:41 UTC
As soon as you use a require statement in your root prettier.config.js the prettier-vscode extension doesn't pull in config settings.

```
'use strict'

const {prettier: prettierConfig} = require('./src/config')
module.exports = Object.assign(prettierConfig, {})
````

**Comment by CiGit** [comment] 2019-01-30 10:15
duplicate of #601

**Closed by CiGit** 2019-01-30 10:15 UTC
