### ISSUE TITLE
Failed to load 'react-hooks'

### ISSUE THREAD

**Issue by shaunjanssens** [prettier/prettier-vscode#910] opened 2019-08-16 08:03 UTC
### Failed to format React files

I'm using VSCode - insiders and Remote - SSH to develop on a remote machine. When using `create-react-app`, Prettiers fails to format the files and gives an error.

### Steps To Reproduce:

1. Create React app with `npx create-react-app app`
2. Configure ESLint and Prettier extensions in VSCode
3. Save file

### Expected result

Formatted file.

### Actual result

Error by Prettier:
```
8/16/2019, 9:45:43 AM:
----------------------
Failed to load plugin 'react-hooks' declared in 'CLIOptions'/home/shaunjanssens/projects/gotoo/webapp/src/App.js:: Cannot find module 'eslint-plugin-react-hooks'
Require stack:
- /home/shaunjanssens/__placeholder__.js
```

### Additional information

**VS Code Version**: 1.38.0-insider 

**Prettier & Prettier Plugin Version**: 1.18.2 (installed on server) / 1.9.0 

**OS and version**: Mac OS and Ubuntu 18.04 (remote development)

**React-scripts**: 3.1.1

 **settings.json**
```
{
  "eslint.validate": [
    {
      "language": "vue",
      "autoFix": true
    },
    {
      "language": "html",
      "autoFix": true
    },
    {
      "language": "javascript",
      "autoFix": true
    },
    {
      "language": "react",
      "autoFix": true
    }
  ],
  "eslint.autoFixOnSave": true,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.formatOnType": false,
  "prettier.eslintIntegration": true,
  "prettier.singleQuote": true,
  "prettier.semi": false
}
```

I already tried to install `eslint-plugin-react-hooks` both as a dev dependency and global on server.

**Comment by danikkks** [comment] 2019-08-17 15:55
same problem
- windows 10
- create-react-app v3.1.1
- vscode version 1.37.1

**Comment by xinkule** [comment] 2019-08-19 16:04
same here
- macOS Mojave 10.14.5
- vscode 1.36.1
- prettier-vscode 1.9.0
- CRA 3.1.1

I guess the problem lies on the eslint version 6.x, it's incompatible with the current version of prettier-vscode.

**Comment by danihazler** [comment] 2019-08-20 12:57
same problem here

**Comment by jaegz** [comment] 2019-08-20 12:58
Also experiencing this issue

- windows 10
- create-react-app 3.0.1
- vscode 1.37.1
- prettier 1.9.0

**Comment by rrlevy** [comment] 2019-08-20 22:40
Same problem here

**Comment by djkalmyk** [comment] 2019-08-21 01:10
also experiencing this problem:
- macOS Mojave 10.14.6
- vscode 1.37.1
- prettier 1.9.0

**Comment by cemujax** [comment] 2019-08-21 08:24
Same problem here

- windows 10 64bit
- vscode 1.37.1
- prettier1.9.0
- CRA 3.1.1

**Comment by YYvanYang** [comment] 2019-08-21 08:57
Same problem here

windows 10 64bit
vscode 1.37.1
CRA 3.1.0

**Comment by agusterodin** [comment] 2019-08-21 15:14
Must be a vscode issue

**Comment by eclecticjohny** [comment] 2019-08-21 18:12
Same as @cemujax here

- windows 10 64bit
- vscode 1.37.1
- prettier1.9.0
- CRA 3.1.1

**Comment by lsw8168** [comment] 2019-08-21 23:49
same problem

windows 10
create-react-app v3.1.1
vscode version 1.37.1

**Comment by GRJser** [comment] 2019-08-22 04:12
I get Similar problem
i got the error of 'cant get module eslint-plugin-vue'
but i already install it both as a dev dependency and global dependency.

**Comment by tylergraf** [comment] 2019-08-22 04:30
https://github.com/facebook/react/issues/16531#issuecomment-523620795

`rm -rf node_modules && npm i` and then restart vscode fixed it for me.

**Comment by yogathanh99** [comment] 2019-08-22 13:17
@tylergraf I do like you talk but I can't fix this issue

**Comment by deadcoder0904** [comment] 2019-08-22 13:54
Yep facing same issue

**Comment by tim-gnue** [comment] 2019-08-22 14:29
same

**Comment by Jonny15t** [comment] 2019-08-22 15:07
I was able to correct this issue by deleting `eslint-config-react-app` from `node_modules` and reinstalling the newest version via `npm i --save-dev eslint-config-react-app`.

**Comment by izayl** [comment] 2019-08-23 07:31
I resolve this problem use `"prettier.eslintIntegration": false` in my VSCode config

**Comment by yogathanh99** [comment] 2019-08-23 09:11
Thanks, @izayl. I fixed this issue like you

**Comment by agusterodin** [comment] 2019-08-24 06:01
RIP productivity and sanity at work this week. Hope someone finds a proper fix

**Comment by sarbazx** [comment] 2019-08-24 12:16
the main reason this error appears is because you didn't install eslint or prettier extension on remote ssh. I have installed and then this error stopped showing up.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/5629946/63637173-14e34e80-c682-11e9-900a-f3e93fd15f9f.png">

**Comment by ntotten** [comment] 2019-08-24 13:05
Duplicate of #870

**Closed by ntotten** 2019-08-24 13:05 UTC

**Comment by cburkins** [comment] 2019-08-25 18:24
Also disabled Prettier ESLint integration to fix the issue.  When I disabled it (vis User Settings panel), it was marked as deprecated in orange text.  Now when I go back to look at it, I'm pretty sure the setting is no longer there.  Did a bit of reading on this as well: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration

**Comment by agusterodin** [comment] 2019-08-25 18:51
Yeah I just narrowed down through trial and error that prettier eslint will not work on any project with react-scripts later than 3.0.1

Pretty devastating considering my entire workflow revolves around using this. So painful developing without it. I could imagine a lot of other people work this way as well.

**Comment by diljitvj** [comment] 2019-08-27 07:19
In my case ES lint was installed globally so I resolved it by installing the package globally.

This is the ES lint error report

> This can happen for a couple of reasons:
> 1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
> 2. If ESLint is installed globally, then make sure 'eslint-plugin-react-hooks' is installed globally as well.
> 3. If ESLint is installed locally, then 'eslint-plugin-react-hooks' isn't installed correctly.

**Comment by KasparasGud** [comment] 2019-08-27 15:01
@diljitvj Thanks !
Installed the 'eslint-plugin-react-hooks' globally with 

`npm i -g eslint-plugin-react-hooks`

and everything is back to normal 💪

**Comment by nick-gaudreau** [comment] 2019-08-29 20:19
Changed `prettier.eslintIntegration": true` to `"prettier-eslint.eslintIntegration": true` in settings.json

**Comment by jetaimefrc** [comment] 2019-08-30 04:36
> Changed `prettier.eslintIntegration": true` to `"prettier-eslint.eslintIntegration": true` in settings.json

When I set that in settings.json => Unknown Configuration Setting =>  Not working!

**Comment by jetaimefrc** [comment] 2019-08-30 04:41
> In my case ES lint was installed globally so I resolved it by installing the 'eslint-plugin-react-hooks' package globally.
> 
> This is the ES lint error report
> 
> > This can happen for a couple of reasons:
> > 
> > 1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
> > 2. If ESLint is installed globally, then make sure 'eslint-plugin-react-hooks' is installed globally as well.
> > 3. If ESLint is installed locally, then 'eslint-plugin-react-hooks' isn't installed correctly.

It worked! Thanks @diljitvj

**Comment by eltNEG** [comment] 2019-08-31 09:34
A temporary I did was to remove the eslintConfig in my package.json

```
"eslintConfig": {
     "extends": "react-app"
   },
```

**Comment by thealexandrelara** [comment] 2019-08-31 22:26
`prettier.eslintIntegration` [is deprecated](https://github.com/prettier/prettier-vscode#deprecated-prettiereslintintegration-default-false---javascript-and-typescript-only) so I removed it from my VSCode settings

According to [Prettier's documentation](https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration) it's recommended to use the ESLint or TSLint extensions directly so I just use `"eslint.autoFixOnSave": true` in my VSCode config and it is working well.

**Comment by tupizz** [comment] 2019-09-04 01:56
Here too... Any workaround?

**Comment by diljitvj** [comment] 2019-09-04 05:50
@tupizz Try this => https://github.com/prettier/prettier-vscode/issues/910#issuecomment-525174068

**Comment by neyosoft** [comment] 2019-09-04 09:27
> lint.autoFixOnSave":

This setting works for me. There is an update on prettier website also about the deprecation and changes.

**Comment by floroz** [comment] 2019-11-18 16:15
here as well, I solved it by installing the 'react-hooks' npm package locally as dev dependency

**Comment by skube** [comment] 2019-11-18 21:38
@floroz That didn't seem to work for me :(

**Comment by floroz** [comment] 2019-11-20 16:07
> @floroz That didn't seem to work for me :(

I have gone through several steps:

1. Remove all eslint and prettier global npm packages
2. Remove all local eslint and prettier packages and plugins
3. Remove VS Code Extensions ESLint and Prettier
4. Reinstall VS Code ESLint extensions
5. If you are using Create-React-App look at the 'Output' for extensions error
6. Gradually install each package and monitor errors in the output.
