### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lucianodecezare** [prettier/prettier-vscode#759] opened 2019-03-18 15:57 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.2`

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2979058/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment] 2019-08-12 17:36
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:36 UTC
Labels: performance
