### ISSUE TITLE
How to use different prettier configs in vscode's user setting

### ISSUE THREAD

**Issue by xuoutput** [prettier/prettier-vscode#740] opened 2019-03-02 07:40 UTC
I want to config js or jsx with semi, while ts or tsx is with no semi

so here is my vscode user config

```
{
  // prettier user setting
  // js, jsx, ts, tsx
  "prettier.jsxSingleQuote": true,
  "prettier.singleQuote": true,
  "[typescript]": {
    // it didn't work
    "prettier.semi": false
  },
  "[typescriptreact]": {
    // so it is
    "prettier.semi": false
  }
}
```
when I use `alt+shift+f`, it still add a semicolon at the end of every line in tsx or ts file.

tslint tell me the config `"prettier.semi": false` didn't exist inside `"[typescriptreact]": {}` . 
![image](https://user-images.githubusercontent.com/16385443/53678987-7cd36080-3d01-11e9-91d3-26275cbd31e6.png)

so how  to config  it, thanks.

**Comment by xuoutput** [comment] 2019-04-13 03:10
https://code.visualstudio.com/updates/v1_33#_default-formatter-selection
```
"[javascript]": {
  "editor.defaultFormatter": "HookyQR.beautify"
}
```

**Comment by CiGit** [comment] 2019-04-25 14:34
duplicate of #312

**Closed by CiGit** 2019-04-25 14:34 UTC
