### ISSUE TITLE
prettier-eslint error

### ISSUE THREAD

**Issue by ronaldruzicka** [prettier/prettier-vscode#879] opened 2019-07-19 08:12 UTC
Hi,
recently I started to receive the following error while formatting via Prettier:

![Screen Shot 2019-07-19 at 10 00 46](https://user-images.githubusercontent.com/20684387/61519403-1fb81d00-aa0c-11e9-9edd-de40a1b26560.png)

Prettier stops working and doesn't format the code. I can make it work if I turn off Eslint integration. But then I lose some formatting from Eslint. For example empty lines between functions or blocks of code:

```js
const fn = () => {
  ...
}
// empty line
const anotherFn = () => {
  ...
}
```
Prettier without Eslint integration removes the the empty line.
The same with `import/newline-after-import` and other rules from Eslint.

```
OS: MacOS 10.14.5
VS code: 1.36.1
Prettier - Code formatter (VS code package): 1.9.0
Eslint (VS code package) - 1.9.0
```

Any help appreciated!

**Comment by idbartosz** [comment] 2019-07-26 06:31
Probably related to https://github.com/prettier/prettier-vscode/issues/870 - leave 👍there to show authors that it should be fixed ASAP

**Comment by ntotten** [comment] 2019-08-12 14:57
Duplicate of #870

**Closed by ntotten** 2019-08-12 14:57 UTC
