### ISSUE TITLE
Location detection logic differs between .prettierignore and .prettierrc

### ISSUE THREAD

**Issue by bmaupin** [prettier/prettier-vscode#1694] opened 2020-12-14 20:46 UTC
### Summary

I have one directory where I put all my Git projects. Let's say it's called `workspace`. I open this in VS Code using *File* > *Open Folder*. Then any repo I `git clone` into that folder automatically gets added to my VS Code workspace.

Whenever I use this plugin, it appropriately finds the .prettierrc in the folder of the specific git repo. So if the git repo is named `prettier-test`:

```
Using config file at '/home/user/workspace/prettier-test/.prettierrc'
```

However it only looks for .prettierignore at the root level of the entire VS Code workspace:

```
Using ignore file (if present) at /home/user/workspace/.prettierignore
```

So any .prettierignore files in my Git repos are completely ignored.

```json
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true,
"prettier.requireConfig": true,
```

### Expected result

I would've expected .prettierignore in /home/user/workspace/prettier-test/ to be used, as this seems to be the behaviour for .prettierrc

### Actual result

The plugin looked for .prettierignore in /home/user/workspace/ which seems to be inconsistent behaviour

### Additional information

**VS Code Version**: 1.51.1

**Prettier Extension Version**: 5.8.0

**OS and version**: Ubuntu 20.04

## Prettier Log Output

```
["INFO" - 3:38:58 p.m.] Formatting /home/user/workspace/prettier-test/test.yaml
["INFO" - 3:38:58 p.m.] Using ignore file (if present) at /home/user/workspace/.prettierignore
["INFO" - 3:38:58 p.m.] Using bundled version of prettier.
["INFO" - 3:38:58 p.m.] File Info:
{
  "ignored": false,
  "inferredParser": "yaml"
}
["INFO" - 3:38:58 p.m.] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 3:38:58 p.m.] Using config file at '/home/user/workspace/prettier-test/.prettierrc'
["INFO" - 3:38:58 p.m.] Prettier Options:
{
  "filepath": "/home/user/workspace/prettier-test/test.yaml",
  "parser": "yaml"
}
["INFO" - 3:38:58 p.m.] Formatting completed in 19.610672ms.
```

Thanks!

**Comment by ntotten** [comment] 2020-12-29 18:05
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to reproduce this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).

**Comment by bmaupin** [comment] 2021-01-05 16:51
I originally didn't create a git repo since it doesn't fully replicate my situation. But it seems whether a particular directory is a git repo seems to bet seems to be irrelevant in this case so I went ahead and created a test repo here: https://github.com/bmaupin/prettier-vscode-1694

So for this test:

- prettier-vscode-1694 (this would mimic the parent directory on my workstation, which is not a git repo)
    - project1 (on my workstation this would be a Git repo in a subdirectory)
    - project2 (on my workstation this would be a Git repo in a subdirectory)

Steps to reproduce:

1. `git clone https://github.com/bmaupin/prettier-vscode-1694.git`
1. In vscode, go to _File_ > _Open Folder_ and browse to prettier-vscode-1694
2. Open project1/test.yaml
3. Save the file and observe that the single quotes are changed to double quotes
4. Open the prettier log and observe that inconsistent logic is used in determining the location of .prettierignore vs .prettierrc:

   ```
   Using ignore file (if present) at /home/user/Desktop/prettier-vscode-1694/.prettierignore
   Using config file at '/home/user/Desktop/prettier-vscode-1694/project1/.prettierrc'
   ```

**Comment by shadowspawn** [comment] 2021-03-03 04:11
Possibly related, Prettier does not have support for finding "nearest" `.prettierignore` file: #375

**Comment by ntotten** [comment] 2021-03-13 20:22
To fix this, some changes would have to be made to the core prettier library. It's something we have talked about, but not something anyone is actively working on. Here are some possible related bugs: https://github.com/prettier/prettier/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aignore+label%3Aarea%3Acli

**Comment by bmaupin** [comment] 2021-03-14 16:38
Looks like it relates to this issue in particular: https://github.com/prettier/prettier/issues/4081

**Comment by ntotten** [comment] 2021-07-26 15:29
Closing in favor of prettier/prettier#4081. If core library implements this we can take it upstream.

**Closed by ntotten** 2021-07-26 15:29 UTC
Labels: enhancement
