### ISSUE TITLE
Inconsistent results when running prettier cli and prettier-vscode

### ISSUE THREAD

**Issue by yareg** [prettier/prettier-vscode#1241] opened 2020-02-07 23:21 UTC
I have vs code configuration:

>     "editor.defaultFormatter": "esbenp.prettier-vscode", 
>     "[javascript]": {
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
>     },
>     "prettier.requireConfig": true,
>     "prettier.useEditorConfig": false

also disabled all other formatters from vs code.

file test.js
> const logger = {};
> this.paraId = '1';
> const error = 'error';
> logger.warn(
>   `Get error on calc open anchor height by paraId: ${
>     this.paraId
>   } error:${error} return default val 0.`
> );

package.json
> "prett": "prettier -c --write test.js",

And, most interesting
Result of executing "yarn prett":

![image](https://user-images.githubusercontent.com/1394597/74072702-58ebc500-4a10-11ea-898a-31f3d26749c2.png)

but, after "Format document" in vs code
![image](https://user-images.githubusercontent.com/1394597/74072789-aec06d00-4a10-11ea-8651-a806b38ccb27.png)

.prettierrc.js file:
`module.exports = {
  singleQuote: true
};`
both prettiers (cli and vs code extension) uses this config... and, what I do wrong?

Thank you.

**Comment by ntotten** [comment] 2020-02-10 17:01
Could you provide the output of the Prettier log. You can access it either by clicking the `Prettier` label in the bottom right of the VS Code toolbar or by opening View -> Output, then selecting Prettier from the drop-down.

**Comment by yareg** [comment] 2020-02-11 08:25
VirtualScrollList.js -- real file with same content

> ["INFO" - 10:22:56 AM] Formatting d:\project\v-product\src\components\views\BookScroll\VirtualScrollList\VirtualScrollList.js
["INFO" - 10:22:56 AM] Using ignore file (if present) at d:\project\v-product\.prettierignore
["INFO" - 10:22:56 AM] Using bundled version of prettier.
["INFO" - 10:22:56 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 10:22:56 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:22:56 AM] Prettier Options:
{
  "filepath": "d:\\project\\v-product\\src\\components\\views\\BookScroll\\VirtualScrollList\\VirtualScrollList.js",
  "parser": "babel",
  "singleQuote": true
}
["INFO" - 10:22:56 AM] Formatting completed in 99.3175ms.

**Comment by ntotten** [comment] 2020-02-13 14:21
Do you have prettier installed globally? If so which version? The plugin is using the bundled version of prettier, not a locally installed version. I am wondering if you are just using an older version of prettier when running through the CLI.

Another thing to try is make sure prettier is installed in the project by running `npm i prettier -D`, then your script `prett` and the extension will for sure use the same instance of prettier.

**Comment by vitorbal** [comment] 2020-02-13 14:57
@ntotten I have a similar situation, and in my case, `prettier` is a transitive dependency from an npm package called `zapier-scripts` that my company developed internally that abstracts prettier behind a `format` command.

That means our top-level `package.json` file has this:
```
  "devDependencies": {
    "zapier-scripts": "*"
  }
```

Yarn hoists the `prettier` bin to the root `node_modules` folder (`node_modules/.bin/prettier`). Is there a way pretter-vscode could also consider this case when trying to resolve the local version of prettier?

**Comment by yareg** [comment] 2020-02-13 16:48
> Do you have prettier installed globally? If so which version? The plugin is using the bundled version of prettier, not a locally installed version. I am wondering if you are just using an older version of prettier when running through the CLI.
> 
> Another thing to try is make sure prettier is installed in the project by running `npm i prettier -D`, then your script `prett` and the extension will for sure use the same instance of prettier.

Yeah, I had globally installed prettier - the result is the same
another, edit package.json
`"prett": "which prettier && prettier -c --write test.js"`  
result
`D:\project\v-product\node_modules\.bin\prettier.CMD`  
which prettier uses vscode extension, I don't know.
Finally, I installed prettier as dev dependency -- nothing changed

**Comment by ntotten** [comment] 2020-03-04 23:26
Duplicate of #950

**Closed by ntotten** 2020-03-04 23:26 UTC
