### ISSUE TITLE
Doesn't respect .prettierignore

### ISSUE THREAD

**Issue by koistya** [prettier/prettier-vscode#208] opened 2017-08-31 13:55 UTC

**Comment by gihrig** [comment] 2017-08-31 16:34
prettier-vscode with format on save enabled creates problems in `package.json`, `webpack.config.js` etc. Even if the format change does not break the file, npm formats `package.json` and the diff churn becomes distracting/annoying.

It would be helpful if prettier-vscode would read `.prettierignore` and void those files when format on save is enabled.

**Comment by konekoya** [comment] 2017-09-01 08:14
+ 1 for this feature

**Comment by CiGit** [comment] 2017-09-01 08:34
This is something we want to do.
I'd like it to copy prettier's feature.

Duplicate of #57 #198 

Someone wants to tackle this feature?

**Comment by azz** [comment] 2017-09-06 09:18
I might give this one a crack.

**Closed** 2017-09-30 07:49 UTC
Labels: enhancement
