### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cezarneaga** [prettier/prettier-vscode#824] opened 2019-05-06 12:09 UTC
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3147818/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.9.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

**Comment by ntotten** [comment] 2019-08-12 17:37
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:37 UTC
Labels: performance
