### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Sadhr** [prettier/prettier-vscode#683] opened 2018-12-26 10:26 UTC
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2710046/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.7.3`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment] 2019-08-12 17:35
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:35 UTC
Labels: performance
