### ISSUE TITLE
not register prettier plugin installed by pnpm

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier-vscode#2586] opened 2022-06-14 17:43 UTC
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/173645784-683a9a58-85e4-4ba4-bad7-219d5d751fad.png">

Repoduce steps:

1. `git clone git@github.com:tjx666/adobe-devtools.git`
2. `git reset --hard  77a25eadb2bfee5f3398437edd1b9d1248a82c03`
3. install dependencies by `pnpm install`
4. try format xml file `CSXS/manifest.xml`
5. try install dependencies by npm, no this issue

- MacOS: 12.4
- VSCode: 1.69.0-insider
- extension: v9.5.0
- Pnpm: 7.2.1

**Comment by ibrahimduran** [comment] 2022-06-25 10:50
Temporary workaround that worked for me is using `.prettierrc.js` and manually resolving plugin imports as showed in [here](https://github.com/trivago/prettier-plugin-sort-imports/issues/131#issuecomment-1163488213).

**Comment by JounQin** [comment] 2022-07-01 16:12
Duplicate of https://github.com/prettier/prettier/issues/8474

**Comment by viceice** [comment] 2022-07-20 07:43
Same for yarn pnp. from cli i can format xml files when manual configure the plugins in `.prettierrc.json` or `.prettierrc.cjs`
But `prettier-vscode` isn't registering the xml formatter 😕

**Comment by ntotten** [comment] 2022-08-20 19:52
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Closed by ntotten** 2022-08-20 19:52 UTC
