### ISSUE TITLE
Not formatting

### ISSUE THREAD

**Issue by derakhshanfar** [prettier/prettier-vscode#704] opened 2019-01-30 20:15 UTC
Using the format command "Shift + Alt + F" doesn't format the file with prettier, use VS default parameters
but if i run with CLI like this, it works

> prettier --config .\.prettierrc --write  "./src/**/*.js"

vs code: 1.30.2

**Comment by colinrcummings** [comment] 2019-02-01 13:55
In the meantime, installing `prettier-vscode` 1.7.3 fixed the issue for me on `vscode` 1.30.2

**Comment by kristianmitk** [comment] 2019-02-01 14:03
Seems the same as #705 which was fixed with https://github.com/prettier/prettier-vscode/pull/706.

@colinrcummings updating to 1.8.1 should work as well

**Comment by colinrcummings** [comment] 2019-02-01 14:09
@kristianmitk, for me 1.8.1 fails to format without any output; 1.8.0 fails to format along with the output `Couldn't resolve parser "babel"`.

**Comment by CiGit** [comment] 2019-02-01 14:10
Could you share your setup?

**Comment by colinrcummings** [comment] 2019-02-01 14:23
https://gist.github.com/colinrcummings/f8187418977f2b553f6ecd29e42546d7

**Comment by CiGit** [comment] 2019-02-01 14:31
No errors in the dev console?

**Comment by JHilker** [comment] 2019-02-01 15:04
@colinrcummings What is your local version of Prettier in the repo?

**Comment by colinrcummings** [comment] 2019-02-01 15:19
@CiGit, there is; after saving a file that requires formatting:

```
  ERR prettierInstance.getSupportInfo is not a function: TypeError: prettierInstance.getSupportInfo is not a function
	at getSupportLanguages (/Users/ccummin3/.vscode/extensions/esbenp.prettier-vscode-1.8.1/out/src/utils.js:43:29)
	at Object.getParsersFromLanguageId (/Users/ccummin3/.vscode/extensions/esbenp.prettier-vscode-1.8.1/out/src/utils.js:11:22)
	at /Users/ccummin3/.vscode/extensions/esbenp.prettier-vscode-1.8.1/out/src/PrettierEditProvider.js:46:40
	at Generator.next (<anonymous>)
	at __awaiter (/Users/ccummin3/.vscode/extensions/esbenp.prettier-vscode-1.8.1/out/src/PrettierEditProvider.js:7:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/ccummin3/.vscode/extensions/esbenp.prettier-vscode-1.8.1/out/src/PrettierEditProvider.js:3:12)
	at format (/Users/ccummin3/.vscode/extensions/esbenp.prettier-vscode-1.8.1/out/src/PrettierEditProvider.js:40:12)
	at PrettierEditProvider._provideEdits (/Users/ccummin3/.vscode/extensions/esbenp.prettier-vscode-1.8.1/out/src/PrettierEditProvider.js:158:16)
	at PrettierEditProvider.provideDocumentFormattingEdits (/Users/ccummin3/.vscode/extensions/esbenp.prettier-vscode-1.8.1/out/src/PrettierEditProvider.js:152:21)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:557:303
	at t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:941)
	at new Promise (<anonymous>)
	at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:909)
	at e.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:557:262)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:572:705
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:567:513)
	at e.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:572:667)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:60)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
	at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

 @jhiker, the `prettier` version in the project I'm working in this morning is 1.7.0.

**Comment by JHilker** [comment] 2019-02-01 15:42
@colinrcummings, thought as much. The fix in https://github.com/prettier/prettier-vscode/pull/706#discussion_r252837934 only fixed support for > 1.8.0.

https://github.com/prettier/prettier-vscode/pull/707 is outstanding, but depends on an upstream change to Prettier. If upgrading your version of Prettier is an option, I'd probably recommend that

**Comment by CiGit** [comment] 2019-02-01 15:43
Ow that was fast ...
The current solution is to use prettier-vscode < 1.8 or to upgrade prettier >= 1.8

Both versions matching is not intended

**Comment by colinrcummings** [comment] 2019-02-01 15:49
@JHilker & @CiGit thanks for the info. Is there an issue or pr in prettier for the upstream change I can watch?

**Comment by JHilker** [comment] 2019-02-01 15:59
@colinrcummings I created a more detailed (and searchable) issue in this repo: https://github.com/prettier/prettier-vscode/issues/710

The upstream issue in Prettier is https://github.com/prettier/prettier/issues/5822

**Comment by CiGit** [comment] 2019-02-01 18:49
Ok, this was faster than expected (I'm joining you @JHilker on faith and deps)

I think the original issue (title is a bit vague) is not about that. 2 days ago this wasn't a thing.

@derakhshanfar can you share a repository ?

**Comment by pedrogyn** [comment] 2019-02-02 10:48
hello guys, i'm fix this following the steps:
1 - download https://github.com/prettier/prettier-vscode/archive/v1.7.0.zip
2 - open the directory ~/.vscode/extensions - https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions
3 - replace folder esbenp.prettier-vscode-1.8.1 to esbenp.prettier-vscode-1.7.0
4 - restart vscode if is open

**Comment by DomiR** [comment] 2019-03-22 14:58
I'm experiencing this since yesterday with this setup:

VSCode: Version 1.33.0-insider (1.33.0-insider)
Plugin: esbenp.prettier-vscode 1.8.0
Package:
  "prettier": "^1.16.4",
  "typescript-tslint-plugin": "^0.3.1",

**Comment by martellaj** [comment] 2019-03-25 14:53
@colinrcummings I'm also reproducing this issue on the latest Insiders build. I confirmed that it doesn't repro in the latest production version.

**Comment by krzkaczor** [comment] 2019-03-25 15:29
Yup, I am experiencing it as well. I guess this is what you get for using insiders build :(

**Comment by martellaj** [comment] 2019-03-25 16:05
@krzkaczor Just updated VS Code (for today's update), and it seems to be working. Can you give it a try and confirm?

**Comment by krzkaczor** [comment] 2019-03-25 16:16
@martellaj oh, it updated twice in a row and now it works again 😆  thanks for this tip.

**Comment by CiGit** [comment] 2019-04-25 13:43
Fixed !

**Closed by CiGit** 2019-04-25 13:43 UTC
Labels: need more info

**Comment by ehmicky** [comment] 2019-04-25 14:06
Great, thanks @CiGit!

Could you please publish a new release?

**Comment by klippx** [comment] 2019-05-27 09:42
For me this was broken in `1.34.0` and I tracked it down to config.json:

```
"prettier.eslintIntegration": true,
```

When I removed this everything worked again.

**Comment by robatron** [comment] 2019-07-16 17:39
Thanks, @klippx , that turned out to be my issue too!
