### ISSUE TITLE
use eslint Unexpected token ...

### ISSUE THREAD

**Issue by lizilong007** [prettier/prettier-vscode#895] opened 2019-08-08 15:07 UTC
node: v12.6.0

settings.json
```json
{
  "prettier.semi": false,
  "prettier.singleQuote": true,
  "prettier.eslintIntegration": true,
  "prettier.printWidth": 120,
  "editor.formatOnSave": true
}
```

eslint Not available... 
![image](https://user-images.githubusercontent.com/15603767/62714238-be92d080-ba30-11e9-8241-553a21a3836f.png)
![image](https://user-images.githubusercontent.com/15603767/62714253-c8b4cf00-ba30-11e9-83e4-e5597b01df8a.png)

eslint can be used normally
![image](https://user-images.githubusercontent.com/15603767/62714168-9d31e480-ba30-11e9-8512-30df0f9d57f3.png)

if `"prettier.eslintIntegration": false` prettier can be used normally

package.json
```json
{
  "name": "am",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "md5": "^2.2.1",
    "react": "16.8.6",
    "react-json-view": "^1.19.1",
    "react-native": "0.60.4",
    "react-native-fs": "^2.14.1",
    "react-native-sqlite-storage": "^3.3.11",
    "react-native-zip-archive": "^4.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by ntotten** [comment] 2019-08-12 14:54
The prettier eslint module is not yet compatible with eslint 6. see: https://github.com/prettier/prettier-eslint/issues/222

**Comment by ntotten** [comment] 2019-08-12 14:57
Duplicate of #870

**Closed by ntotten** 2019-08-12 14:57 UTC
Labels: bug, dependency
