### ISSUE TITLE
Failed to load plugin 'standard' declared

### ISSUE THREAD

**Issue by ldwqh0** [prettier/prettier-vscode#869] opened 2019-07-05 03:51 UTC
when I set   "prettier.eslintIntegration": true

then the error happend in VSCode

```bash
Failed to load plugin 'standard' declared in 'CLIOptions'd:\Users\LiDong\Projects\xyyh-git\edc\web\src\c.js:: Cannot find module 'eslint-plugin-standard'
Require stack:
- D:\Users\LiDong\AppData\Local\Programs\Microsoft VS Code\__placeholder__.js
```

i installed eslint and eslint-plugin-standard in node_modules

**Comment by nashaofu** [comment] 2019-07-05 07:34
same problem,Seems to be caused by eslint upgrade to 6.

**Comment by jimblue** [comment] 2019-07-05 10:46
Ya same problem too since I've updgrade to eslint 6

**Comment by alexbassy** [comment] 2019-07-05 12:46
Disabling `prettier.eslintIntegration": true` seemed to fix this for me

**Comment by BernardoFBBraga** [comment] 2019-07-08 15:25
I also had this problem and rolled back my eslint version. alexbassy's solution worked but turned off prettier which was not an option for me :P

**Comment by ntotten** [comment] 2019-08-12 15:47
Duplicate of #870

**Closed by ntotten** 2019-08-12 15:47 UTC
