### ISSUE TITLE
Prettier- TypeError: Cannot read properties of undefined (reading 'uid')

### ISSUE THREAD

**Issue by sumanssaurabh** [prettier/prettier-vscode#3020] opened 2023-06-09 05:29 UTC
**Edited by maintainer**

> I'll work on this. So please do not post any more +1 comments..

https://github.com/prettier/prettier-vscode/issues/3020#issuecomment-1586703424

----

Type: <b>Bug</b>

Prettier running in ssh remote gives error 
vscode TypeError: Cannot read properties of undefined (reading 'uid') at Object.statSync (/home/ubuntu/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/node_modules/graceful-fs/polyfills.js:313:17)

Extension version: 9.13.0
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'ssh-remote+neo' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+neo' could not be established
</details>

**Comment by aleimu** [comment] 2023-06-09 05:48
+1

**Comment by mupkoo** [comment] 2023-06-09 06:18
This happened to me this morning after I upgraded VS Code to `1.79.0`

**Comment by Clark-G** [comment] 2023-06-09 06:33
This also happended to me today, my vs code version is 1.79.0

**Comment by einarpersson** [comment] 2023-06-09 06:35
Same here `1.79.0`

**Comment by NattakornS** [comment] 2023-06-09 06:43
Me also happened on vscode 1.79.0.

**Comment by xiaojia21190** [comment] 2023-06-09 06:45
+1

**Comment by sumanssaurabh** [comment] 2023-06-09 06:55
workaround suggested in https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998 

Quick fix, add to project settings in .vscode/settings.json
```
"prettier.prettierPath": "./node_modules/prettier"
```

**Comment by gyhyfj** [comment] 2023-06-09 07:47
same problem

**Comment by szszoke** [comment] 2023-06-09 08:00
The problem started for me after I went from 1.78.2 to 1.79.0.

**Comment by paul-vd** [comment] 2023-06-09 08:33
Same here

**Comment by adsonmacedo** [comment] 2023-06-09 10:02
+1

**Comment by AnmSaiful** [comment] 2023-06-09 11:27
I just attempted to report the issue and found this one.

+1

**Comment by souvikmishra** [comment] 2023-06-09 11:31
+1 also happens when running vscode in wsl

**Comment by pedroperesx** [comment] 2023-06-09 14:04
+1

And my vs code version is 1.79.0

**Comment by Rigel-Developer** [comment] 2023-06-09 16:11
same problem here!!

**Comment by gitawego** [comment] 2023-06-09 16:51
I've the same issue with vscode 1.79.0

**Comment by trulycool** [comment] 2023-06-09 17:21
Same problem directly after upgrade VS Code. The fix suggested above by @sumanssaurabh fixed it straight away, no reload/restart required...thanks very much for that!
🙏

**Comment by narcis-fv** [comment] 2023-06-09 18:15
+1

**Comment by MikeFranco** [comment] 2023-06-09 19:05
Solved with @sumanssaurabh fix, thanks man ❤️

**Comment by jngchenghin-msft** [comment] 2023-06-09 21:29
+1

**Comment by kayandra** [comment] 2023-06-09 23:05
+1 here.... I was going crazy thinking I'd somehow broken my vscode installation.

**Comment by JoarDev** [comment] 2023-06-09 23:29
+1 first time trying the prettier extension and this happened :(

**Comment by oezguerisbert** [comment] 2023-06-10 11:07
[Here](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998) is a small quickfix.
Create a file in the root of the project; `.vscode/settings.json`
```
{
  ...
  "prettier.prettierPath": "./node_modules/prettier"
}
```

**Comment by victor-pagnozi** [comment] 2023-06-10 12:16
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

Solved with your fix, man!! Tksss

**Comment by 709kyb** [comment] 2023-06-10 15:34
@sumanssaurabh  it works ! thanks man.

**Comment by dantevicenzo** [comment] 2023-06-10 19:09
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

This solved here. Thanks!

**Comment by jeremydthomas** [comment] 2023-06-11 00:12
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

thank you so much, fixed it!

**Comment by codebycarlos** [comment] 2023-06-11 01:25
Glad I'm not the only one 😅

**Comment by immois** [comment] 2023-06-11 04:49
It also works by adding it to the VSCode configuration like this:

Looking for **Prettier Path** and adding `./node_modules/prettier`
![image](https://github.com/prettier/prettier-vscode/assets/60050894/a0e6f9d9-14cd-44ec-89f8-9f55731f821b)

**Comment by jtapeg** [comment] 2023-06-11 16:24
+1

**Comment by jtapeg** [comment] 2023-06-11 16:27
The correction must be made by vscode, the problem is in the extension installation

This solution doesn't work well if the file is not together with node_modules
![image](https://github.com/prettier/prettier-vscode/assets/52453013/4ba80b1d-90c9-47a8-90bd-043c828c7daa)

**Comment by lucasbazev** [comment] 2023-06-11 21:53
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

this worked like a charm! thanks a lot

**Comment by parkgang** [comment] 2023-06-12 01:30
+1

**Comment by sosukesuzuki** [comment] 2023-06-12 07:00
I'll work on this. So please do not post any more `+1` comments..

**Comment by sosukesuzuki** [comment] 2023-06-12 07:07
Has anyone had this happen in an environment other than ssh? I could not reproduce this on my local machine (MacOS).

**Comment by parkgang** [comment] 2023-06-12 07:08
> Has anyone had this happen in an environment other than ssh? I could not reproduce this on my local machine (MacOS).

I had that problem in my local WSL2 environment.

**Comment by sosukesuzuki** [comment] 2023-06-12 07:12
Thanks, but I think WSL's VSCode uses ssh internally. Right?

**Comment by parkgang** [comment] 2023-06-12 07:16
> Thanks, but I think WSL's VSCode uses ssh internally. Right?

Not sure if you use `SSH` or not.
However, it is inferred from VSCode's connection to work remotely.

**Comment by edx-mohammed-waleed** [comment] 2023-06-12 07:25
> ./node_modules/prettier

This fixed it, thanks

**Comment by gitchaell** [comment] 2023-06-12 13:26
I have managed to solve it in the following way:

1. Install Prettier as a global dependency

```powershell
npm install -g prettier
````

2. Obtain the installation path of global npm dependencies (`/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/` in my case)
 
```powershell
npm root -g
```

3. Navigate to VSCode Prettier Path configuration section and paste the path + ` /prettier`)

![image](https://github.com/prettier/prettier-vscode/assets/125929961/4285591f-386d-4336-be7c-416074fdb964)

**Comment by kayandra** [comment] 2023-06-12 14:45
> I have managed to solve it in the following way:
> 
>     1. Install Prettier as a global dependency
> 
> 
> ```powershell
> npm install -g prettier
> ```
> 
>     2. Obtain the installation path of global npm dependencies (`/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/` in my case)
> 
> 
> ```powershell
> npm root -g
> ```
> 
>     3. Navigate to VSCode Prettier Path configuration section and paste the path + ` /prettier`)
> 
> 
> ![image](https://user-images.githubusercontent.com/125929961/245156712-4285591f-386d-4336-be7c-416074fdb964.png)

I did the same thing, but didn't comment it as a solution as it's hacky and not documented.

**Comment by jtapeg** [comment] 2023-06-12 19:10
> Alguém já viu isso acontecer em um ambiente diferente do ssh? Não consegui reproduzir isso na minha máquina local (MacOS).

Just install Debian or Ubuntu on Windows WSL and try to use prettier with the latest version of VSCODE

**Comment by basicdays** [comment] 2023-06-12 19:34
I'm also having this happen when using Docker and remote Dev Containers. Host machine is MacOS.

**Comment by anrondon-microsoft** [comment] 2023-06-12 21:00
+1 Having the same problem with WSL Ubuntu on a Windows host

**Comment by ffimnsr** [comment] 2023-06-13 01:46
Same problem the said temporary fix above doesn't work with npm/pnpm workspace installed prettier.

**Comment by josephinebienes** [comment] 2023-06-13 05:04
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

Had the same problem with WSL Ubunut in Windows and the above worked for me

**Comment by jooyal** [comment] 2023-06-13 05:05
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

Thanks! This fixed the issue for me.

**Comment by hrenaud** [comment] 2023-06-13 05:47
Inside a devcontainer:
1. do `nvm install XX.xx.yy` ← change `XX.xx.yy` to the node version to needed
2. in VSCode settings or in `.devcontainer/devcontainer.json` set
```sh
"prettier.prettierPath": "$NVM_DIR/current/lib/node_modules"
```

**Comment by viceice** [comment] 2023-06-13 06:09
Duplicate of #3019

**Comment by dev-richierich** [comment] 2023-06-13 14:41
> same problem

lol why you get down-voted hahahhaa ... anyways happened to me as well, going to try one of these fixes

**Comment by devferx** [comment] 2023-06-13 16:57
Same problem here

**Comment by yuripiresalves** [comment] 2023-06-13 20:20
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

This fixed my problem, thx 👍

**Comment by P3DR0DEV** [comment] 2023-06-14 01:35
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

This fixed for me, thx

**Comment by apenab** [comment] 2023-06-14 12:04
> "prettier.prettierPath": "./node_modules/prettier"

The same for me.

**Comment by apmoronez** [comment] 2023-06-14 16:05
> > same problem
> 
> lol why you get down-voted hahahhaa ... anyways happened to me as well, going to try one of these fixes

because the dev is actively working on this issue and has requesting people stop spamming with "+1 same problem" comments

**Comment by xianghongai** [comment] 2023-06-15 02:30
vs code upgrade to 1.79.1

**Comment by MrVauxs** [comment] 2023-06-15 06:01
Got the same issue on 1.79.1 in an SSH setup. Was fine before updating.

**Comment by Soviut** [comment] 2023-06-15 06:09
Updated to vscode 1.79.1 and still having the same issue in WSL2 (ubuntu20.04) under Windows 10.

Adding the following to `.vscode/settings.json` _does_ solve the issue, but I'd rather not add this to every project I'm running.

```
"prettier.prettierPath": "./node_modules/prettier"
```

**Comment by hasithar** [comment] 2023-06-15 09:48
> workaround suggested in [#3019 (comment)](https://github.com/prettier/prettier-vscode/issues/3019#issuecomment-1583356998)
> 
> Quick fix, add to project settings in .vscode/settings.json
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

I faced the same issue after upgrading vscode. This solved it. Thank you...

**Comment by Ev357** [comment] 2023-06-15 11:32
> "prettier.prettierPath": "./node_modules/prettier"

thx

**Closed** 2023-06-16 00:29 UTC

**Comment by Chsirgelbayev** [comment] 2023-06-16 18:14
+1

**Comment by jtorresv232** [comment] 2023-06-16 18:34
Why is this closed, what is the fix?

**Comment by apmoronez** [comment] 2023-06-16 18:47
> Why is this closed, what is the fix?

it _literally_ says "fixed by #3030 "

**Comment by Apestein** [comment] 2023-06-17 05:05
RIP to the people who didn't find this and still trying to debug right now 💀

**Comment by Ev357** [comment] 2023-06-21 15:34
> RIP to the people who didn't find this and still trying to debug right now 💀

I had this error, on a code that actually used a variable named `uid`, so i was super confused XD

**Comment by Hibrix-net** [comment] 2023-06-23 05:29
Hello,

I am currently experiencing an issue with the Prettier module. It appears to have stopped functioning correctly for me starting from version 9.12.0. The plugin is now prompting me to npm install the module either locally or globally.

As a temporary workaround, I have downgraded to version 9.10.4, which has allowed me to continue using the module as usual. However, this is not a long-term solution.

I have attempted to follow the solution suggested by @sumanssaurabh, but unfortunately, it did not resolve the issue for me.

Could anyone provide some insight or assistance on this matter? Any help would be greatly appreciated.

Thank you.

**Comment by Soviut** [comment] 2023-06-23 06:12
@Hibrix-net sorry to hear you're having a problem but please don't use closed issues to report new issues. Please report a new issue.

**Comment by Hibrix-net** [comment] 2023-06-23 06:22
Hello @Soviut,

Thank you for your response. I apologize for any confusion, but I was under the impression that this issue was still open as it doesn't explicitly state that it's closed. Could you kindly clarify why this issue is considered closed? Also, could you please point me to the solution that resolved the original issue? This information will help me understand if my problem is indeed different and warrants a new issue.

Thank you for your assistance.

**Comment by farzadso** [comment] 2023-06-23 06:34
@Hibrix-net It was closed because the issue was solved in a recent update and the proposed workaround is no longer required.

**Comment by Hibrix-net** [comment] 2023-06-23 06:38
> @Hibrix-net It was closed because the issue was solved in a recent update and the proposed workaround is no longer required.

The latest version is v9.16.0, right? but I'm still encountering the issue. I'm curious, am I the only one still experiencing this problem?

**Comment by farzadso** [comment] 2023-06-23 06:42
@Hibrix-net 

I think it's best to do the follow-up in a separate issue as your issue seems a bit different (asking you to do some sort of  `npm install`). And yes the latest version is `v9.16.0`.

I also recommend adding logs/screenshots to your issue.

**Comment by Hibrix-net** [comment] 2023-06-23 07:04
Hello @Soviut,

Thank you for your response. However, I believe there might be a misunderstanding. The issue I'm experiencing is not distinct but rather a continuation of the problem discussed in #3019. If you refer to that thread, you'll notice that the problem described there is identical to mine, including the prompt to install the Prettier module.

Many users in this thread are suggesting the solution from #3019, and this issue is also considered a duplicate of that one. Therefore, I believe my issue is not separate but a persistent instance of the original problem.

I hope this clarifies the situation. I appreciate your understanding and assistance.

**Comment by Soviut** [comment] 2023-06-23 07:09
> Thank you for your response. I apologize for any confusion, but I was under the impression that this issue was still open as it doesn't explicitly state that it's closed. 

It's closed in the timeline and says "Closed" at the top of the issue and in the header sticky header.

![image](https://github.com/prettier/prettier-vscode/assets/226882/804a3789-9750-48eb-a2a2-9cf4c6e772d1)

![image](https://github.com/prettier/prettier-vscode/assets/226882/6c2053b5-8436-4fd8-ac99-79ea2f8bf97a)

For this issue and #3019 all you need to do is fully restart VSCode after it's been completely updated. If this doesn't work for some reason, restart your entire computer.

**Comment by Hibrix-net** [comment] 2023-06-23 07:19
> > Thank you for your response. I apologize for any confusion, but I was under the impression that this issue was still open as it doesn't explicitly state that it's closed.
> 
> It's closed in the timeline and says "Closed" at the top of the issue and in the header sticky header.
> 
> ![image](https://user-images.githubusercontent.com/226882/248197141-804a3789-9750-48eb-a2a2-9cf4c6e772d1.png)
> 
> ![image](https://user-images.githubusercontent.com/226882/248196905-6c2053b5-8436-4fd8-ac99-79ea2f8bf97a.png)
> 
> **However**, for this issue and #3019 all you need to do is fully restart VSCode after it's been updated to the latest version `v1.79.2` (or later) AND the prettier plugin for VSCode has been updated to the latest version `v9.16.0` (or later). If this doesn't work for some reason, restart your entire computer.
> 
> If it still doesn't work and you see a Prettier in the bottom right corner of VSCode is red, then start a new issue, paste your log and any relevant screenshots.
> 
> ![image](https://user-images.githubusercontent.com/226882/248198721-6da4c0a6-8000-4802-8d6b-5e8e871e169a.png)

Hi,
Yes, I already tried what you said several times but didn't worked. If you look at the issue #3019 its seems I'm not the only one who had to downgrade to a previous Prettier version to make it work.

Thanks anyway for your patience.

**Comment by ehoogeveen-medweb** [comment] 2023-06-23 10:18
@Hibrix-net Did you apply the `prettier.prettierPath` workaround from this issue? If so, remove it: The workaround broke extension version 9.16. This is being tracked in https://github.com/prettier/prettier-vscode/issues/3041.

**Comment by Hibrix-net** [comment] 2023-06-23 10:29
> @Hibrix-net Did you apply the `prettier.prettierPath` workaround from this issue? If so, remove it: The workaround broke extension version 9.16. This is being tracked in #3041.

Yes, I tried it then removed it but still having the issue with versions above the 9.10.4 + VS Code latest version installed on my Windows 10 machine.
