### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by budalin** [prettier/prettier-vscode#723] opened 2019-02-13 09:34 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2859678/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

- OS Version: `Darwin x64 15.6.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/gothic/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` 
:warning:
Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kachkaev** [comment] 2019-02-13 10:25
Hi @budalin! Please check existing issues before creating a new one:
https://github.com/prettier/prettier-vscode/issues?q=is%3Aissue+Extension+causes+high+cpu+load+is%3Aopen

**Comment by ntotten** [comment] 2019-08-12 17:35
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:35 UTC
Labels: performance
