### ISSUE TITLE
prettier.trailingComma: es5 removed on save

### ISSUE THREAD

**Issue by chrisbeaver** [prettier/prettier-vscode#1323] opened 2020-04-13 17:11 UTC
Issue Type: <b>Bug</b>

I'm attempting to have prettier format my file with the es5 setting on the trailingComma.  I do not recall changing any of my settings and this alway worked before, but I cannot tell if it's a problem with the extension or a conflict between the extension and code editor.

Reproduce the Results:
1. Edit a javascript file, allow prettier to fix all problems (and add the trailing commas). 
2. The squiggle lines under the errors disappear, code looks like I want it to. So I save it.
3. After the file is saved, my trailing commas are removed and the squiggle lines return.

I'm setting the es5 in my User Settings file, but noticed in the integrated terminal that it's not being passed to Prettier.

![image](https://user-images.githubusercontent.com/5077917/79141257-6c583b00-7d87-11ea-8567-d09c10cc9329.png)

Even if I don't fix the file, I can see the autoFormatOnSave attempt to, but then the commas are removed almost immediately.

<b>Please note I'm using the Insiders Edition.</b>

Extension version: 4.2.0
VS Code version: Code - Insiders 1.45.0-insider (44c5185373d5f209cd6c0b5d29a216fb801da34e, 2020-04-10T18:12:33.780Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (4.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by baohouse** [comment] 2020-04-14 04:53
Looks like reverting back to 4.1.1 release works, so 4.2.0 and 4.3.0 have the bug.

**Comment by ntotten** [comment] 2020-04-14 10:52
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).

**Comment by chrisbeaver** [comment] 2020-04-14 11:34
> Looks like reverting back to 4.1.1 release works, so 4.2.0 and 4.3.0 have the bug.

Yes, I've found that reverting back to 4.1.1 has resolved my issue.

**Comment by chrisbeaver** [comment] 2020-04-14 12:16
I'd think that the changes here https://github.com/prettier/prettier-vscode/commit/1a8a8fc1d2012f11d50b8f0294380b3f8d9518be#diff-5f0a14a626b969e3eff17cb440ab6e41R60 may have something to do with it. 

I'm setting `"prettier.trailingComma": "es5",` and it's not coming through. The ternary expression on `usePrettierV2Defaults` appears to be false and passing the hardcoded "none".

**Comment by ntotten** [comment] 2020-04-14 13:24
Ugh, yeah that was stupid of me. Reverting and will publish a new version shortly. Thanks for catching that.

**Comment by ntotten** [comment] 2020-04-14 13:27
Should be fixed in v4.4.0.

**Closed by ntotten** 2020-04-14 13:27 UTC

**Comment by codler** [comment] 2020-04-18 07:53
I run https://create-react-app.dev/ and have never changed any config. Today after restarting VScode after haven't restarted for many days. Suddenly when I formatted my code all the trailing comma are gone! I always had trailing comma before the restart.
