### ISSUE TITLE
.vue file Prettier format is broken in Vetur 0.20.0

### ISSUE THREAD

**Issue by lizy0329** [prettier/prettier-vscode#830] opened 2019-05-10 01:52 UTC
## Info

- Platform: mac & windows 10
- Vetur version: 0.20.0
- VS Code version: 1.33.1
- Prettier - Code formatter: 1.9.0

## Problem
.vue file Prettier format is broken in Vetur 0.20.0

but in .js file is work file

## Reproducible Case

vue -> js
![GIF.gif](https://i.loli.net/2019/05/09/5cd3a56c1d9ec.gif)

js file
![js.png](https://i.loli.net/2019/05/09/5cd3a56e42894.png)

vue file
![vue.png](https://i.loli.net/2019/05/09/5cd3a56ff29b4.png)

Vetur < 0.20.0, vue file is exist `Prettier √` status

**Comment by diego81b** [comment] 2019-06-05 13:19
i have the same issue

**Comment by ntotten** [comment] 2019-08-12 17:06
This is our parser inference. The extension is likely not detecting the type of the file correctly. As a workaround, you can specify the parser in a prettier config file "overrides" property and set the parser. See: https://prettier.io/docs/en/options.html#parser

{
	// ...
	"overrides":[{
		"files": "*.html", // replace this by more specific extension if needed
      	"options": {
        	"parser": "html"
      	}
	}]
}

Duplicate of #487

**Closed by ntotten** 2019-08-12 17:06 UTC

**Comment by StarkBrothers** [comment] 2019-09-02 09:15
You should first forbidden vetur, and then start it, maybe their order crash.
