### ISSUE TITLE
plugin-ruby conflict with rubocop

### ISSUE THREAD

**Issue by chevinbrown** [prettier/prettier-vscode#731] opened 2019-02-18 13:47 UTC
https://github.com/prettier/plugin-ruby 👏 is looking pretty sweet. 
I've run into issues where prettier seems to abort when rubocop is enabled.
https://github.com/prettier/plugin-ruby/issues/113

I'm no VSCode expert, so I'm not sure where to begin, but will happily proxy debug if anyone can direct me.

**Comment by kddeisz** [comment] 2019-04-25 14:53
Does the suggestion here help at all? @chevinbrown 
 https://qiita.com/koshilife/items/ec2cc281f8238275c5cb I don't use vscode so I'm shooting in the dark a bit

**Comment by chevinbrown** [comment] 2019-04-25 14:59
I don't think that's _the best_ solution. For me, the issue was VSCode-prettier not finding the plugin (as well as interfering with rubocop's formatting, resulting in a very long save-participants run time). 
For now, [this comment](https://github.com/prettier/plugin-ruby/issues/113#issuecomment-464203844) has solved my issues.

**Comment by CiGit** [comment] 2019-04-25 16:33
This should be fixed with plugin support #757 
Installing it in the extension directly is a current workaround. But you will have to do it on every update (I think)
Closing as duplicate of #395

**Closed by CiGit** 2019-04-25 16:33 UTC

**Comment by kddeisz** [comment] 2019-04-25 16:40
Great @CiGit thanks!
