### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by clerval** [prettier/prettier-vscode#680] opened 2018-12-21 17:53 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.7.3`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/armando/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by clerval** [comment] 2018-12-21 17:56
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2703705/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by ntotten** [comment] 2019-08-12 17:35
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:35 UTC
Labels: performance
