### ISSUE TITLE
Unable to resolve custom configuration module

### ISSUE THREAD

**Issue by vincerubinetti** [prettier/prettier-vscode#1289] opened 2020-04-03 15:27 UTC
### Summary

It seems that version `4.0.0` released a few hours ago breaks importing/using custom Prettier configs. Downgrading to `3.20.0` fixes the issue.

I know `4.0.0` would be a breaking change, but I don't see anything in the change logs or in the readme that indicates that custom configs would work differently...

### Github Repository to Reproduce Issue

https://github.com/greenelab/prettier-config-greenelab

### Steps To Reproduce:

1.  Create a new project with `npm init`
1.  Install [this custom Prettier config](https://github.com/greenelab/prettier-config-greenelab) with `yarn add --dev git+https://git@github.com/greenelab/prettier-config-greenelab.git`
1.  Create `.prettierrc.yaml` and put this in it: `prettier-config-greenelab`
1.  Install the prettier-vscode extension and try to format some javascript code with it

### Expected result

The code should format with no errors in the console.

### Actual result

The code does not format, and throws errors, as copy-pasted below

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: `1.43.2`

**Prettier Extension Version**: `4.0.0`

**OS and version**: Windows 10 64bit

## Prettier Log Output

```
["INFO" - 11:27:07 AM] Extension Name: "prettier-vscode".
["INFO" - 11:27:07 AM] Extension Version: "4.0.0".
["INFO" - 11:27:07 AM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 11:27:07 AM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 11:27:08 AM] Formatting c:\Users\Vincent\Desktop\adage-frontend\src\pages\signatures\participating\index.js
["ERROR" - 11:27:08 AM] Invalid prettier configuration file detected.
["ERROR" - 11:27:08 AM] Cannot find module 'prettier-config-greenelab' from 'c:\Users\Vincent\Desktop\adage-frontend'
Error: Cannot find module 'prettier-config-greenelab' from 'c:\Users\Vincent\Desktop\adage-frontend'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Function.n.resolve (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:584)
	at Object.transform (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:23283:40)
	at run (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11472:51)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11300:20)
	at async Explorer.search (c:\Users\Vincent\.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier\third-party.js:11457:22)
	at async Promise.all (index 0)
```

Note that `node_modules/prettier-config-greenelab` DOES exist in my project. Everything has been installed correctly. I also have a `eslint-config-greenelab` installed in the same project as well, which works with no problems. And as I said, downgrading `prettier-vscode` in-situ, while in the same project, works.

**Comment by ntotten** [comment] 2020-04-03 19:32
Opened related issue here: https://github.com/prettier/prettier/issues/7949

**Comment by vincerubinetti** [comment] 2020-04-03 20:16
Turns out it's an upstream bug or breaking change with Prettier.

A temporary fix per @ntotten is to change your `.prettierrc.yaml` to `prettier: prettier-config-yourcustomlib`.

Or, I guess if you're using `.prettier.json`: `{ "prettier": "prettier-config-yourcustomlib" }`

**Comment by laozhu** [comment] 2020-04-04 07:43
```json
{
  "prettier": "./packages/chores/prettier",
}
```

Prettier config in package.json is broken with new version vscode plugin,  but it's OK with `prettier.config.js`config below.

```js
module.exports = require('./packages/chores/prettier');
```
Error screenshot

![image](https://user-images.githubusercontent.com/1212457/78421549-0f73cb00-768b-11ea-968d-2fdc147379d3.png)

**Comment by ntotten** [comment] 2020-04-04 17:11
A PR is open on prettier to resolve this, hopefully it can be released quickly into a patch release. I will update the extension as soon as this is read. 

See: https://github.com/prettier/prettier/pull/7951

**Comment by thorn0** [comment] 2020-04-05 20:59
@ntotten Prettier 2.0.3 is out.

**Comment by AndrewLeedham** [comment] 2020-04-06 09:01
This seems to still be broken for me, I made a minimal repro here:
https://github.com/AndrewLeedham/repros/tree/master/packages/prettier-2.0-resolution

Probably worth noting this is a mono-repo, so to properly recreate: I would just copy the files from the specific linked sub-package. Also note that the issue occurs out of a mono-repo, I just store all my repros in a single repo so I don't have to create new ones every time.

### Environment details:
- vscode-prettier: 4.0.0
- prettier 2.0.3
- node 12.16.1
- macOS Catalina (10.15.3)
- vscode 1.43.2

### Error summary:
```
["INFO" - 9:54:03 AM] Extension Name: "prettier-vscode".
["INFO" - 9:54:03 AM] Extension Version: "4.0.0".
["INFO" - 9:54:03 AM] Loaded module 'prettier@2.0.3' from '**REDACTED**/repros/node_modules/prettier/index.js'
["INFO" - 9:54:03 AM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 9:54:03 AM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 9:54:20 AM] Formatting **REDACTED**/repros/packages/prettier-2.0-resolution/format.js
["ERROR" - 9:54:20 AM] Invalid prettier configuration file detected.
["ERROR" - 9:54:20 AM] Cannot find module '@xerox/prettier-config' from '**REDACTED**/repros/packages/prettier-2.0-resolution'
Error: Cannot find module '@xerox/prettier-config' from '**REDACTED**/repros/packages/prettier-2.0-resolution'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Function.n.resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:584)
	at Object.transform (**REDACTED**/.vscode/extensions/esbenp.prettier-vscode-4.0.0/node_modules/prettier/index.js:23283:40)
	at run (**REDACTED**/.vscode/extensions/esbenp.prettier-vscode-4.0.0/node_modules/prettier/third-party.js:11472:51)
	at async cacheWrapper (**REDACTED**/.vscode/extensions/esbenp.prettier-vscode-4.0.0/node_modules/prettier/third-party.js:11300:20)
	at async Explorer.search **REDACTED**/.vscode/extensions/esbenp.prettier-vscode-4.0.0/node_modules/prettier/third-party.js:11457:22)
	at async Promise.all (index 0)
```

**Comment by thorn0** [comment] 2020-04-06 09:45
Looking into it... 
I was sure this fix was going to help because I tested it locally on Windows and it worked. To test it, I simply overwrote the files in
`.vscode\extensions\esbenp.prettier-vscode-4.0.0\node_modules\prettier` with Prettier 2.0.3.

**Comment by thorn0** [comment] 2020-04-06 09:58
@AndrewLeedham The new version of the extension, which bundles the new version of Prettier, hasn't been released yet. The extension uses the bundled Prettier package to resolve the config files, not the locally installed one.

**Comment by thorn0** [comment] 2020-04-06 10:00
@ntotten Please wait a bit more. I'm going to release 2.0.4 because of a severe regression in 2.0.3 (see https://github.com/prettier/prettier/pull/7958).

**Comment by AndrewLeedham** [comment] 2020-04-06 10:04
> @AndrewLeedham The new version of the extension, which bundles the new version of Prettier, hasn't been released yet. The extension uses the bundled Prettier package to resolve the config files, not the locally installed one.

I see was not aware of that, slightly confusing given it logs the installed version. Reverting until the new release then. Thanks @thorn0 😃

**Comment by thorn0** [comment] 2020-04-06 11:59
@ntotten 2.0.4 is out

**Comment by ntotten** [comment] 2020-04-06 12:00
Issue fixed in version 4.1.1 published which has prettier 2.0.4. Thanks for the rapid fix @thorn0!

**Closed by ntotten** 2020-04-06 12:00 UTC
Labels: bug

**Comment by mohsinxx365** [comment] 2020-04-18 12:50
I am still having the same problem

**Comment by thorn0** [comment] 2020-04-18 13:13
@mohsinxx365 Please [fill a proper bug report](https://github.com/prettier/prettier-vscode/issues/new?template=Bug_report.md).
