### ISSUE TITLE
Not working with PHP plugin?

### ISSUE THREAD

**Issue by antonioribeiro** [prettier/prettier-vscode#612] opened 2018-10-27 21:26 UTC
This is how I'm installing it:

```
$ npm install prettier @prettier/plugin-php --save-dev
+ prettier@1.14.3
+ @prettier/plugin-php@0.9.0
```

Looks like the plugin is working for javascript:

    "editor.formatOnSave": false,

    "[javascript]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true
    },

But not for PHP: 

    "[php]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true
    },

The strangest is that when I save this PHP file:

```
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Queue Connection Name
    |--------------------------------------------------------------------------
    |
    | Laravel's queue API supports an assortment of back-ends via a single
    | API, giving you convenient access to each back-end using the same
    | syntax for every one. Here you may define a default connection.
    |
    */

    'default' => env('QUEUE_CONNECTION', 'sync'),
```

Nothing but the docblock changes:

```
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Queue Connection Name
    |--------------------------------------------------------------------------
    |
    | Laravel's queue API supports an assortment of back-ends via a single
    | API, giving you convenient access to each back-end using the same
    | syntax for every one. Here you may define a default connection.
    |
*/ <============ THIS IS WHAT IT CHANGES IN THE FILE

    'default' => env('QUEUE_CONNECTION', 'sync'),
```

But, still, running it manually, it works fine:

```
prettier --write config/queue.php
```

**Comment by CiGit** [comment] 2018-11-08 14:40
We currently have no plugin support. see #395 
It should (I've not tested) work if you install it in this extension's folder
`$HOME/.vscode/extensions/esbenp.prettier-vscode-VERSION/`

It seems you have an extension which does something to your php file if it changes when you `Format Document` (you should do it without saving as a lot of other things can kick in onSave)

**Comment by ntotten** [comment] 2019-08-12 17:28
Duplicate of #899

**Closed by ntotten** 2019-08-12 17:28 UTC

**Comment by antonioribeiro** [comment] 2019-08-12 17:52
I understand your Pull Request is fixing this Issue, but one cannot be a duplicate of the other, they are complementary: a change in the code is done to fix an issue.

But all right, thanks for the fix.
