### ISSUE TITLE
Incorrect Instructions for VS Code

### ISSUE THREAD

**Issue by SPCMorris** [prettier/prettier-vscode#266] opened 2017-11-17 22:40 UTC
We just added Prettier to our code base and when I was trying to use it in VS Code I was doing so per these instructions you give: 

Using Command Palette (CMD/CTRL + Shift + P)

1. CMD + Shift + P -> Format Document
OR
1. Select the text you want to Prettify
2. CMD + Shift + P -> Format Selection

However, I found that in VS Code I have to use `shift`+`alt`+`f` (options instead of alt for mac)  to formate a document with Prettier. I just wanted to let you guys know, not sure if it is an issue with everyone.

Thanks!

*EDIT*

Explained that poorly. Basically, when I try to use that command on format selected text it doesn't work and sometimes won't with formatting the whole doc. With the shortcut I provided above it works every time for me.

**Comment by RobinMalfait** [comment] 2017-11-18 11:50
Hello sir, we had some misunderstandings about the usage of the extension. What we describe is that you can open the command palette (with CMD+SHIFT+P) and then search for 'Format Document' which is indeed SHIFT+ALT+F.

The formatting on selected text is currently a known bug, so I'm going to mark this issue as a duplicate.

Duplicate of #173, #134 and #137

**Closed by RobinMalfait** 2017-11-18 11:50 UTC

**Comment by patelrohan** [comment] 2018-03-15 14:32
@RobinMalfait  Maybe a screenshot or better explanation in description of the extension can help avoiding such misunderstandings? I was hitting CMD + Shift + P and nothing happened and checked the reviews that had a lotto 1 star saying does not work. So, I decided to investigate this issue on the Github and found this.

**Comment by RobinMalfait** [comment] 2018-03-15 15:08
Feel free to open a PR to make it the documentation better. 🙏
