### ISSUE TITLE
With version 9.9.0, the. vue file cannot be formatted. When I use version 9.8.0, it is OK

### ISSUE THREAD

**Issue by YangJianshun** [prettier/prettier-vscode#2737] opened 2022-10-04 10:46 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**Prettier Extension Version**:

**OS and version**:

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREENSHOT, COPY AND PASTE THE TEXT
```

**Comment by ntotten** [comment] 2022-10-07 00:14
Duplicate of #2729

**Closed by ntotten** 2022-10-07 00:14 UTC
