### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nonameolsson** [prettier/prettier-vscode#682] opened 2018-12-24 22:15 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.7.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: [esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2707787/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment] 2019-08-12 17:35
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:35 UTC
Labels: performance
