### ISSUE TITLE
Extension 'prettier' cannot format xxx

### ISSUE THREAD

**Issue by xinkule** [prettier/prettier-vscode#921] opened 2019-08-24 09:34 UTC
### Summary

I just update prettier-vscode to 1.10.0, and when I format code, it just doesn't work anymore, keeps showing the message: extension 'prettier' cannot format xxx.

And I cannot see **format** option when I right click mouse in css files anymore.

### Steps To Reproduce:

1.  Update to 1.10.0
2.  Format your js/tsx code, and you can see the message.

### Expected result

works as usual.

### Actual result

error message.

### Additional information

**VS Code Version**: 1.37.1

**Prettier**: local dependency 1.18.2 and no local prettier.

**Prettier-vscode**: 1.10.0

**OS and version**: macOS Mojave 10.14.5

**Comment by ntotten** [comment] 2019-08-24 12:08
Duplicate of #918

**Closed by ntotten** 2019-08-24 12:08 UTC
