### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aftabnack1** [prettier/prettier-vscode#827] opened 2019-05-07 09:30 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.9.0`
- OS Version: `Linux x64 5.0.0-13-generic`
- VSCode version: `1.33.1`

Attaching the expected file
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3151837/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by ntotten** [comment] 2019-08-12 17:37
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:37 UTC
Labels: performance
