### ISSUE TITLE
Semi colons flicker whilst formatting on save

### ISSUE THREAD

**Issue by bitttttten** [prettier/prettier-vscode#711] opened 2019-02-03 14:06 UTC
When I forgot my document that has no semi colons by saving, they seem to appear and then disappear. If I format from the commands (Ctrl+Shift+P) it does not seem to flicker.

I recorded an example: https://i.imgur.com/9OxDzJ4.gifv

.vscode/settings.json:

```
{
	"editor.codeActionsOnSave": { "source.organizeImports": true },
	"eslint.trace.server": "messages",
	"editor.formatOnSave": true,
}
```

user settings:

```
{
  "workbench.startupEditor": "newUntitledFile",
  "editor.detectIndentation": false,
  "editor.insertSpaces": false,
  "window.zoomLevel": 0,
  "editor.fontSize": 13,
  "javascript.validate.enable": false,
  "explorer.autoReveal": false,
  "explorer.confirmDragAndDrop": false,
  "editor.minimap.enabled": false,
  "workbench.colorTheme": "fairyfloss",
  "indentRainbow.colors": [
    "rgba(255,179,186, .05)",
    "rgba(255,223,186, .08)",
    "rgba(255, 255, 186, .05)",
    "rgba(186,255,201, .08)",
    "rgba(186,225,255, .05)"
  ],
  "explorer.confirmDelete": false,
  "eslint.packageManager": "yarn",
  "eslint.autoFixOnSave": true,
  "files.autoSave": "onFocusChange",
  "eslint.alwaysShowStatus": true,
  "files.eol": "\n",
  "terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe",
  "eslint.run": "onSave"
}
```

**Comment by codepunkt** [comment] 2019-02-25 13:53
`source.organizeImports` is the culprit, it seems to reorganize the imports and add semicolons to them.

**Comment by bitttttten** [comment] 2019-02-25 18:38
Oh yeah, you're right!

**Comment by ntotten** [comment] 2019-08-12 17:19
Duplicate of #716

**Closed by ntotten** 2019-08-12 17:19 UTC
