### ISSUE TITLE
Trying to format .js and .jsx files results in "Error formatting document"

### ISSUE THREAD

**Issue by myessail** [prettier/prettier-vscode#1447] opened 2020-06-25 19:58 UTC
### Summary

I have my editor configured to format on save. When I save a .js or .jsx file, I get the warning triangle indicator in the bottom right, and the message "Error formatting document" in the Prettier logs.

### Github Repository to Reproduce Issue

https://github.com/DataBiosphere/jade-data-repo-ui

### Steps To Reproduce:

1.  Edit a .js or .jsx file
2. Save the file

### Expected result

Prettier should have detected any issues and formatted the file correctly.

### Actual result

Prettier throws an error:

```["INFO" - 3:48:31 PM] Formatting /Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/FreetextFilter.jsx
["INFO" - 3:48:31 PM] Using ignore file (if present) at /Users/myessail/broad/jade-data-repo-ui/.prettierignore
["INFO" - 3:48:31 PM] Loaded module 'prettier@2.0.5' from '/Users/myessail/broad/jade-data-repo-ui/node_modules/prettier/index.js'
["INFO" - 3:48:31 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 3:48:31 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 3:48:31 PM] Prettier Options:
{
  "filepath": "/Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/FreetextFilter.jsx",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "all",
  "jsxBracketSameLine": false
}
["ERROR" - 3:48:31 PM] Error formatting document.
["INFO" - 3:48:31 PM] Formatting completed in 12.922509ms.
```

### Additional information

I've experienced this problem once before, and the only way I was able to resolve it was to uninstall and reinstall VSCode, which is not an acceptable solution. If I run Prettier from the command line, it works with no issues.

My settings.json:

```
{
  "workbench.colorTheme": "Noctis Lux",
  "editor.formatOnSave": true,
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "editor.formatOnPaste": true,
  "files.autoSave": "off",
  "window.zoomLevel": 0,
  "prettier.eslintIntegration": true,
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.codeActionsOnSave": {
    // For ESLint
    "source.fixAll.eslint": true
  }
}
```

**VS Code Version**:

```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Prettier Extension Version**:

`5.1.0`

**OS and version**:

Mac OS Mojave 10.14.6 (18G3020)

## Prettier Log Output

```
["INFO" - 3:48:31 PM] Formatting /Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/FreetextFilter.jsx
["INFO" - 3:48:31 PM] Using ignore file (if present) at /Users/myessail/broad/jade-data-repo-ui/.prettierignore
["INFO" - 3:48:31 PM] Loaded module 'prettier@2.0.5' from '/Users/myessail/broad/jade-data-repo-ui/node_modules/prettier/index.js'
["INFO" - 3:48:31 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 3:48:31 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 3:48:31 PM] Prettier Options:
{
  "filepath": "/Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/FreetextFilter.jsx",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "all",
  "jsxBracketSameLine": false
}
["ERROR" - 3:48:31 PM] Error formatting document.
["INFO" - 3:48:31 PM] Formatting completed in 12.922509ms.
```

**Comment by ntotten** [comment] 2020-06-30 14:10
I am not able to reproduce this. Can you try disabling all extensions except prettier and see if you can reproduce?

**Comment by myessail** [comment] 2020-06-30 16:39
Yes, I disabled all my extensions and still got the output"

```
["INFO" - 12:38:41 PM] Formatting /Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/JadeAutocomplete.jsx
["INFO" - 12:38:41 PM] Using ignore file (if present) at /Users/myessail/broad/jade-data-repo-ui/.prettierignore
["INFO" - 12:38:41 PM] Loaded module 'prettier@2.0.5' from '/Users/myessail/broad/jade-data-repo-ui/node_modules/prettier/index.js'
["INFO" - 12:38:41 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 12:38:41 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 12:38:41 PM] Prettier Options:
{
  "filepath": "/Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/JadeAutocomplete.jsx",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "all",
  "jsxBracketSameLine": false
}
["ERROR" - 12:38:41 PM] Error formatting document.
["INFO" - 12:38:41 PM] Formatting completed in 15.599895ms.
```

**Comment by ntotten** [comment] 2020-06-30 18:04
I just added some additional logging in 5.1.1. Upgrade to v5.1.1 and run this again and provide the logs.

**Comment by myessail** [comment] 2020-06-30 19:43
```
["INFO" - 3:42:18 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 3:42:18 PM] Extension Version: 5.1.1.
["INFO" - 3:42:18 PM] Loaded module 'prettier@2.0.5' from '/Users/myessail/broad/jade-data-repo-ui/node_modules/prettier/index.js'
["INFO" - 3:42:18 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 3:42:18 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 3:42:31 PM] Formatting /Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/JadeAutocomplete.jsx
["INFO" - 3:42:31 PM] Using ignore file (if present) at /Users/myessail/broad/jade-data-repo-ui/.prettierignore
["INFO" - 3:42:31 PM] Loaded module 'prettier@2.0.5' from '/Users/myessail/broad/jade-data-repo-ui/node_modules/prettier/index.js'
["INFO" - 3:42:31 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 3:42:31 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 3:42:31 PM] Prettier Options:
{
  "filepath": "/Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/JadeAutocomplete.jsx",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "all",
  "jsxBracketSameLine": false
}
["ERROR" - 3:42:31 PM] Error formatting document.
["INFO" - 3:42:31 PM] Formatting completed in 480.165338ms.
```

**Comment by ntotten** [comment] 2020-07-01 19:21
Can you update to version 5.1.2 and run this again and paste the log again.

**Comment by myessail** [comment] 2020-07-01 21:28
Hmm, it looks like updating to 5.1.2 worked for me! Not sure what changed, I don't think I've changed anything in the project since I last ran it. Logs for reference:

```
["INFO" - 5:27:37 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 5:27:37 PM] Extension Version: 5.1.2.
["INFO" - 5:27:37 PM] Loaded module 'prettier@2.0.5' from '/Users/myessail/broad/jade-data-repo-ui/node_modules/prettier/index.js'
["INFO" - 5:27:37 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 5:27:37 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 5:27:51 PM] Formatting /Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/FreetextFilter.jsx
["INFO" - 5:27:51 PM] Using ignore file (if present) at /Users/myessail/broad/jade-data-repo-ui/.prettierignore
["INFO" - 5:27:51 PM] Loaded module 'prettier@2.0.5' from '/Users/myessail/broad/jade-data-repo-ui/node_modules/prettier/index.js'
["INFO" - 5:27:51 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 5:27:51 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:27:51 PM] Prettier Options:
{
  "filepath": "/Users/myessail/broad/jade-data-repo-ui/src/components/dataset/query/sidebar/filter/FreetextFilter.jsx",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "all",
  "jsxBracketSameLine": false
}
["INFO" - 5:27:51 PM] Formatting completed in 110.178453ms.
```

**Comment by ntotten** [comment] 2020-07-02 14:02
Weird. The only change in 5.1.2 was to add additional logging. I'll close this for now, but please reopen if you see the issue again.

**Closed by ntotten** 2020-07-02 14:02 UTC
Labels: need more info
