### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SajjadSM** [prettier/prettier-vscode#756] opened 2019-03-16 13:56 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: [esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2973954/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by adFedorovich** [comment] 2019-03-29 09:03
Add this line to .eslintrc.json file, it works for me) 

```
"env": {
	"browser": true
},

```

**Comment by ntotten** [comment] 2019-08-12 17:36
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:36 UTC
Labels: performance
