### ISSUE TITLE
[Question] Format HTML in PHP files (only html)

### ISSUE THREAD

**Issue by kanlukasz** [prettier/prettier-vscode#847] opened 2019-06-04 08:32 UTC
Is it possible to formatting HTML in PHP files with Prettier?
I don't want to formatting PHP (i know it's not possible at this moment).
I talk about only HTML content but in PHP files.

#### Just for example:
In **Beautify** VSCode plugin by HookyQR exist option like this:

```
"beautify.language": {
	"html": [
		"htm",
		"html",
		"php", //add php to formatting html in php files,
	]
},
```
Can I configure **Prettier** in that way or another?

**Comment by jcklpe** [comment] 2019-07-02 20:57
I would also like to know this

**Comment by ntotten** [comment] 2019-08-12 17:09
This will be supported in the next release once we add support for plugins. Duplicate of #899

**Closed by ntotten** 2019-08-12 17:09 UTC
