### ISSUE TITLE
FormatOnSave not working /w. v.1.9 & Monorepo

### ISSUE THREAD

**Issue by NikoMontana** [prettier/prettier-vscode#887] opened 2019-07-30 13:16 UTC
Using prettier via VSCode and workspace settings. Changes get applied to `www/pages/index.tsx` but nothing happens on `api/server.ts`

```
{
  "editor.formatOnSave": true
}
```

```
|--- api
    |--- package.json
    |--- tsconfig.json 
    |--- server.ts
|--- www
    |--- pages
         |--- index.tsx
    |--- package.json
    |--- tsconfig.json 
```

**Comment by Kylar13** [comment] 2019-08-02 08:55
Having this issue as well, even with a `.prettierrc` and `.editorconfig` file. Tried putting these files at package level on all packages and still nothing

**Comment by ntotten** [comment] 2019-08-12 15:50
Please provide more information on what versions of prettier, eslint, etc you are using. I suspect this is a duplicate of #870.

**Comment by waesabi** [comment] 2019-08-12 15:53
try setting `prettier.eslintIntegration` to false . it worked for me .

**Closed** 2019-08-19 16:35 UTC
Labels: need more info
