### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by a-eid** [prettier/prettier-vscode#746] opened 2019-03-09 10:44 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.31.1`

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2948293/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment] 2019-08-12 17:36
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:36 UTC
Labels: performance
