### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Hossam-Ali** [prettier/prettier-vscode#729] opened 2019-02-17 17:24 UTC
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/hali/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Hossam-Ali** [comment] 2019-02-17 17:27
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2873206/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by kachkaev** [comment] 2019-02-17 17:27
https://github.com/prettier/prettier-vscode/issues?utf8=✓&q=is%3Aissue+is%3Aopen+Extension+causes+high+cpu+load

**Comment by ntotten** [comment] 2019-08-12 17:35
Duplicate of #676

**Closed by ntotten** 2019-08-12 17:35 UTC
Labels: performance
