### ISSUE TITLE
Version above 3.2.0 adding trailing comma and round brackets to fat arrow fn argument

### ISSUE THREAD

**Issue by Dhiraj3089** [prettier/prettier-vscode#1302] opened 2020-04-07 03:47 UTC
`const a =  b.find((x)=> x);`

**Comment by raymondp413** [comment] 2020-04-08 02:20
I can confirm I'm having this issue as well.

**Comment by trivikr** [comment] 2020-04-08 03:49
Duplicate of https://github.com/prettier/prettier-vscode/issues/1290

As of now, you should either:
* define your own prettier configuration
* use [prettier-v1-config](https://www.npmjs.com/package/prettier-v1-config)
* update to prettier@2 ([blog post](https://prettier.io/blog/2020/03/21/2.0.0.html))

Details: https://github.com/prettier/prettier-vscode/issues/1290#issuecomment-610468847

**Comment by ntotten** [comment] 2020-04-09 19:12
Duplicate of #1290

**Closed by ntotten** 2020-04-09 19:12 UTC
