### ISSUE TITLE
Wrong .tsx formatting with fragments

### ISSUE THREAD

**Issue by bazo** [prettier/prettier-vscode#656] opened 2018-11-27 10:14 UTC
this code 

```jsx
import React from "react";

const Buddies = () => <>Buddies</>;
export default Buddies;
````

after saving becomes this

````jsx
import React from "react";

const Buddies = () => <>"uddie"</>;
export default Buddies;
````

if i use a div instead of a fragment it works ok

prettier ran from command line works ok too

**Comment by italomlp** [comment] 2019-06-17 04:23
I am having this problem too. In my case, this code:
```jsx
<>
  <SafeAreaView style={styles.statusBar} />
  <SafeAreaView style={styles.safeArea}>{...children}</SafeAreaView>
</>
```
Is becoming this:
```jsx
<>'   '<SafeAreaView style={styles.statusBar} />'   '<SafeAreaView style={styles.safeArea}>{...children}</SafeAreaView>' '</>
```

If I use `React.Fragment` explicitly, it works, but not with the empty tag.

**Comment by HVish** [comment] 2019-06-24 07:49
I am also facing same issue! Following code:

```jsx
<><div>abc</div></>
```

becomes:
```jsx
<>
  ' \' \' \' \' '<div>abc</div>' '
</>
```

**Comment by hibikine** [comment] 2019-07-08 03:25
As a temporary solution, to turn off `prettier.eslintIntegration` fixes this issue.

```settings.json
{
  "prettier.eslintIntegration": false
}
```

**Comment by BrunoQuaresma** [comment] 2019-08-10 18:08
any update?

**Comment by ntotten** [comment] 2019-08-12 16:04
Duplicate of #870

**Closed by ntotten** 2019-08-12 16:04 UTC
