### ISSUE TITLE
Prettier is not working any more? 

### ISSUE THREAD

**Issue by AhmedHalim96** [prettier/prettier-vscode#774] opened 2019-03-31 19:59 UTC
I think Prettier is not working anymore. I use the latest vscode on windows, I removed all my settings and other extensions just in case and I did  a clean installation still doesn't work
is it just me?

**Comment by Titozzz** [comment] 2019-04-01 08:15
Duplicate of https://github.com/prettier/prettier-vscode/issues/763 probably

**Comment by CiGit** [comment] 2019-04-25 13:53
If you call format on save without having specified a default formatter, chances are nothing happens since vscode 1.33

**Comment by lomeat** [comment] 2019-08-11 15:21
+, dont work Prettier anymore.

**Comment by ntotten** [comment] 2019-08-12 16:04
Duplicate of #870

**Closed by ntotten** 2019-08-12 16:04 UTC

**Comment by GregRush** [comment] 2019-11-12 15:15
Yup, it does nothing. I just wasted so much time trying to debug it...

**Comment by anthonysim** [comment] 2020-04-01 05:26
Yup stopped working for me and I have no idea how to fix it.

**Comment by dancherb** [comment] 2020-04-12 08:27
Prettier (and also Beautify) are being completely ignored as extensions for me (including any configurations) - VSCode continues to just use the default formatting for "Format" and "Format on save" (`"editor.defaultFormatter": "esbenp.prettier-vscode"` is set)

**Comment by lomeat** [comment] 2020-04-12 15:40
Use extension for vs code 'JavaScript and TypeScript Nightly'
