### ISSUE TITLE
Extension not working: Cannot find module 'acorn'

### ISSUE THREAD

**Issue by alexeychikk** [prettier/prettier-vscode#858] opened 2019-06-23 09:18 UTC
Extension is not working currently and outputs the following error `Cannot find module 'acorn'`.
**Reinstalling didn't help.**
It helped when I manually installed `acorn` package in the project's folder even though my project doesn't depend on it.

**Comment by himanshupnt** [comment] 2019-06-23 20:24
I'm also facing the same issue. Any plugin in `plugins` errors out `Cannot find module <module name>`
.eslintrc ->
```json
{
  "parser": "babel-eslint",
  "parserOptions": {
      "sourceType": "module"
  },
  "env": {
    "browser": true,
    "node": true,
    "jest": true,
    "es6": true
  },
  "plugins": [
    "prettier",
    "react",
    "jest"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "settings": {
    "react": {
      "createClass": "createReactClass",
      "pragma": "React",
      "version": "detect"
    }
  },
  "rules": {
    "react/destructuring-assignment": [2, "always", { "ignoreClassFields": true }],
    "react/no-array-index-key": 2,
    "react/no-unused-state": 2,
    "react/no-unused-prop-types": 2,
    "prettier/prettier": "error",
    "no-nested-ternary": 2,
    "semi": [2, "always"],
    "prefer-destructuring": ["error", {"object": true, "array": true}],
    "prefer-const": ["error", {
      "destructuring": "any"
    }],
    "indent": ["error", 2, { "SwitchCase": 1 }],
    "max-len": ["error", { "code": 120 }]
  }
}
```
package.json -> 
```json
"eslint": "^6.0.0",
    "eslint-config-prettier": "^5.0.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-jest": "^22.7.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.13.0",
    "prettier": "^1.18.2",
```

**Comment by AlaaZorkane** [comment] 2019-06-25 05:51
Same issue here.
VS code throws me an error each time I try to format:
![image](https://user-images.githubusercontent.com/2952507/60072386-345b0b00-9715-11e9-82ff-3dc07ea0c271.png)
This is only within vscode itself, the cli tool works perfectly using "prettier --write /somefile.js"

Some additional info:
eslint debug shows no errors - eslint is working as intended
Any plugin/extends throw the same error not only eslint-plugin-prettier
Tried installing/uninstalling globally, same issue eveytime.

**Comment by cannap** [comment] 2019-06-27 09:22
i donwgraded eslint to ^4.0.0 until a fix

**Comment by EthanNYT** [comment] 2019-06-28 18:20
> I downgraded eslint to ^4.0.0

Works for me as well:

- ESLint: v4.0.0
- Node: v10.14.2
- VS Code: 1.35.1

**Comment by devias-io** [comment] 2019-07-24 14:15
Try to remove everything from `settings.json`. It should fix the problem.

**Comment by cannap** [comment] 2019-07-24 16:58
i dont have any prettier related stuff in settings.json


this is my workspace settings.json file 

{
  "search.exclude": {
    "**/.nuxt": true
  },
  "files.watcherExclude": {
    "**/.nuxt": true
  },
  "files.exclude": {
    "**/.nuxt": true
  },
  "vue-i18n-ally.localesPaths": "lang"
}

**Comment by samarti** [comment] 2019-07-26 15:12
What I did was to remove any reference to esLint on `settings.json`
I removed:
```
{
  "prettier.eslintIntegration": true,
  "eslint.enable": true,
}
```
and it worked fine

**Comment by ntotten** [comment] 2019-08-12 15:56
Duplicate of #870

**Closed by ntotten** 2019-08-12 15:56 UTC
