### ISSUE TITLE
Prettier stops formatting my code

### ISSUE THREAD

**Issue by Chiamaka** [prettier/prettier-vscode#181] opened 2017-07-26 11:49 UTC
Hey, guys. Awesome work with Prettier, I love it. 

Recently, I started noticing that prettier doesn't format my code. It doesn't always start out this way though. It starts out fine but after a while (I notice vscode takes about 2 seconds to save my file), it stops until I restart my editor.

Has anyone encountered this? Anyone know the issue? Thanks

**Comment by CiGit** [comment] 2017-07-26 12:20
I've not encountered such issue.
What do you mean by 'after a while' ? after some time doing nothing ? after some time saving a lot?
Does it happen with prettier being the only enabled extension ?

And just to be sure, does it **stop** or does it **take time** formatting?

**Comment by Chiamaka** [comment] 2017-07-26 12:41
'After a while' means after some time saving alot. I have other extensions installed/enabled. And yeah, it just stops formatting. What takes time is vscode when I hit save. I was thinking maybe there is a correlation between the two events (vscode taking about 2 seconds to save my code and when prettier stop formatting my code).

**Comment by CiGit** [comment] 2017-07-26 14:21
A correlation seems right.
It this happens again, it seems it should, can you see if developer tool says something ?
Snapshot memory, CPU profile would also certainly help in that case :sob:

**Comment by kv4sha** [comment] 2017-08-15 17:01
If file saving completes before than "prettier" completes working, file doesn't format.
You can see it especially often when you work with large files or on a slow computer.

**Comment by RobinMalfait** [comment] 2017-08-15 19:57
Interesting, I wonder if this is a problem with vscode itself since we are just providing a `formatter` using their api. 🤔

**Comment by CiGit** [comment] 2017-08-16 08:22
Introduced a delay to test this:
```ts
return format(document.getText(), document, {})
            .then(
                code =>
                    new Promise<string>(r => setTimeout(() => r(code), 1000)) // delay
            )
            .then(code => [
                TextEdit.replace(fullDocumentRange(document), code),
            ]);
```

Seems it formats when calling the formatter command. But it is completely discarded on save. Seems to be about 1 second.
Will need a lot more digging

**Comment by CiGit** [comment] 2017-08-16 08:45
I don't think this last problem is exactly what @Chiamaka encountered. I may be wrong, but if it takes time to save, it should let us more time to return from format call.
Or do we take more time *after a while* ? Those hard to debug things ...

**Comment by CiGit** [comment] 2017-08-16 09:01
And thinking about it right now, I suppose this is a problem with vscode. Something like 

|vscode | prettier |
|------| ---- |
|call format |  start format|
| save buffer | process format |
| buffer saved | process format |
| | update buffer|
| don't care, buffer already dropped ||

**Comment by kv4sha** [comment] 2017-08-16 09:53
May be better to use onWillSaveTextDocument
https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace

**Comment by CiGit** [comment] 2017-08-16 11:54
This may be a work around. Even if from the doc you linked
> The current thresholds are 1.5 seconds

It seems to be near 1 sec in this case.

It will also change a good part of our code AND users won't be able to use format document anymore. We will need a new actions and mostly some new settings ....

**Comment by kv4sha** [comment] 2017-08-16 15:43
Maybe it help, this plugin wrote in Microsoft.
https://github.com/Microsoft/vscode-go/blob/master/src/goFormat.ts

**Comment by HelveticaScenario** [comment] 2017-08-17 17:40
I have been experiencing this as well. Ive noticed that when it happens there is a process in the activity manager called Code Helper that is taking up a significant percentage of cpu. Im on a MacBook Pro (Retina, Mid 2012) with 2.6ghz i7 and 8gb ram

**Comment by willadamskeane** [comment] 2017-11-02 20:35
I also have this problem. I have to restart Visual Code to get it working again.

**Comment by Nimelrian** [comment] 2017-11-08 09:58
Question to everyone experiencing this bug: What is your `printWidth` configuration set to?
I experience the same issue when Prettier encounters long lines (mainly React elements with many props) with a `printWidth` of 200. I experimented with reducing it to 100 and the problems disappeared.

Can somebody else verify that this fixes the issue for them?

**Comment by Nimelrian** [comment] 2017-11-08 10:59
Some more testing yielded a pretty good way to reproduce the problem which may help finding the cause for this issue.

1. Create the following file `test.jsx` inside an empty folder, open it in VS Code:
```jsx
const ThisKillsThePrettier = () => (
  <div>
    <img
      anotherProp="LongValueLongValueLongValueLongValueLongValue"
      src="TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest"
      className="AnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTest"
      id="LongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTest"
    />
    <img
      anotherProp="LongValueLongValueLongValueLongValueLongValue"
      src="TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest"
      className="AnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTest"
      id="LongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTest"
    />
    <img
      anotherProp="LongValueLongValueLongValueLongValueLongValue"
      src="TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest"
      className="AnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTest"
      id="LongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTest"
    />
  </div>
);
```

2. Then, remove all the linebreaks between the props so that it looks like this (`End -> Ctrl+Del -> Space` helps with this):
```jsx
const ThisKillsThePrettier = () => (
  <div>
    <img anotherProp="LongValueLongValueLongValueLongValueLongValue" src="TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest" className="AnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTest" id="LongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTest" />
    <img anotherProp="LongValueLongValueLongValueLongValueLongValue" src="TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest" className="AnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTest" id="LongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTest" />
    <img anotherProp="LongValueLongValueLongValueLongValueLongValue" src="TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest" className="AnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTestAnotherTest" id="LongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTestLongerTest" />
  </div>
);
```

3. Save the file
4. The file should be saved after ~1-2 seconds, without being reformatted (still looks like step 2, rather than step 1).
5. In the meantime, Prettier finishes the formatting after ~2-3 additional seconds. Note that this is a very long time for such a short file. When it occurs in my production code, it does not finish in a reasonable amount of time, causing the CPU hogging.
6. Save the file again
7. The file is now formatted correctly.
8. Repeat step 2
9. Run the "Format Document" task, it will take a long time to finish
10. Save the file
11. The file is saved instantly in it's correct format

Running standalone Prettier on the file finishes in 67ms, so the dramatic slowdown does indeed seem to come from the plugin, rather than from Prettier itself

**Comment by braposo** [comment] 2017-11-16 23:32
I'm getting a similar delay with `"prettier.eslintIntegration": true,` in the settings, but it seems to work fine if eslint integration is disabled. 

What I also notice is that doing the format on save takes some time and the file isn't saved correctly, but triggering the formatting manually seems to be a bit faster, although not as fast as when eslint integration is disabled.

Do you also have eslint integration enabled?

**Comment by CiGit** [comment] 2017-11-17 10:53
This may be relevant to this issue : prettier/prettier#3263 (just fixed not yet released)

@Nimelrian Quickly testing your reproduction steps leads to a really fast formatting in my case...

>Running standalone Prettier on the file finishes in 67ms, so the dramatic slowdown does indeed seem to come from the plugin, rather than from Prettier itself

This seems weird to me. We do things prettier don't. mostly reading your file system tree upwards (is that slow?). But prettier is cached after first use (Node require). We don't have the cost of a node start + prettier load. (`echo "" | prettier` is ~200ms on my system)

I would expect both to be at the same speed. Of course there is vscode and other extensions which may do other things.
To compare, quickly profiling vscode when calling Format takes around 20ms on a 200 loc tsx file. (DOM update excluded, cold ~160ms)

**Comment by Badbreaddead** [comment] 2017-12-30 23:03
Any updates according to this issue?

**Comment by kv4sha** [comment] 2017-12-31 08:23
If eslint-integration is on, auto format on save drops down with timeout. Without eslint-integration everything is OK.

**Comment by CiGit** [comment] 2018-01-03 11:21
It seems VSCode discards formatOnSave if it takes more than ~1 sec. 
The solution I see for now is calling `Format Document` action explicitly.
Or disable `eslintIntegration` which does a lot more work (prettier -> eslint --fix). It can still timeout with only prettier on some big files tho.

**Comment by anthonybrown** [comment] 2018-03-20 19:56
I'm starting to use vscode and liking it so far except for the fact that vscode doesn't format my code when I use the keyboard shortcut, so I set up the `editor.formatOnSave: true` and that's not working as well??? 🤓

**Comment by CiGit** [comment] 2018-03-26 12:17
I don't know your kb shortcuts, but if you open command palette and search for _Format Document_ it should do something 😄

**Comment by anthonybrown** [comment] 2018-03-26 22:16
@CiGit , it didn't do anything? Do I need a pragma or something?
This is my `.prettierrc` file:
```
{
  "noSemi": false,
  "parser": "babylon",
  "singleQuote": true,
  "printWidth": 100,
  "trailingComma": "all",
  "jsxBracketSameLine": false
}
```

**Comment by anthonybrown** [comment] 2018-03-26 22:17
It should be putting in the semi-colons for me right?
```
class BookList extends Component {
	renderList() {
		return this.props.books.map((book) => {
			return (
				<li
					key={book.title}
					className='list-group-item'
					onClick={() => this.props.selectBook(book)}
				>
					{book.title}
				</li>
			)
		})
	}
```

**Comment by CiGit** [comment] 2018-03-26 22:26
@anthonybrown try with [`"semi": true`](https://prettier.io/docs/en/options.html#semicolons)
you should have an error message in the output panel by the way.

@RobinMalfait We should maybe see to do something with the new notification center :-)

**Comment by anthonybrown** [comment] 2018-03-26 22:28
Nothing ☹️

**Comment by CiGit** [comment] 2018-03-26 22:39
Right, this is a warning, it appears only in dev console.
if you remove your prettierrc, does it work?

**Comment by CiGit** [comment] 2018-04-08 10:57
As of VSCode 1.22 you can now specify formatOnSave's timeout: https://code.visualstudio.com/updates/v1_22#_configurable-format-on-save-timeout

**Comment by fbacker** [comment] 2018-04-25 05:34
@CiGit that was a good fix for now
"editor.formatOnSaveTimeout": 3000,

**Comment by Flink91** [comment] 2018-06-06 12:59
None of the above worked for me. What did work was closing my bazillion Tabs in the editor.

**Comment by harleyguru** [comment] 2018-07-30 09:39
Hey @CiGit , I think this is the issue related with Prettier itself.
Even if I try to format explicitly without saving, it's not working.
any idea?

Prettier only works when I had to restart VSCode for some mins only.

**Comment by HarisHashim** [comment] 2018-08-25 12:44
I am having the same problem.  Coding using VSCode and Vue. So Vetur is the formatter.

Afterabout 5 to 10 minutes of heavy editing. I notice that code hint (CTRL-SPACE) will just display loading and code formating (ALT-SHIFT-F) will not do formatting.

I have to restart VSCode and then terminate it in Task Manager. So looks like VSCode it self has become zombie.

**Comment by Talhah** [comment] 2018-09-12 12:36
I am experiencing the exact same issue.

**Comment by raulfdm** [comment] 2019-06-03 14:07
> It seems VSCode discards formatOnSave if it takes more than ~1 sec.
> The solution I see for now is calling `Format Document` action explicitly.
> Or disable `eslintIntegration` which does a lot more work (prettier -> eslint --fix). It can still timeout with only prettier on some big files tho.

Just want to say disable this integration solve my `prettier~performance` issue.

**Comment by raulfdm** [comment] 2019-06-03 14:15
> I don't use Prettier and I still experienced this. It might be related to another extension. How many of you are using the `Zignd.html-css-class-completion` extension? Try disabling it
> 
> See [microsoft/vscode#16328](https://github.com/microsoft/vscode/issues/16328)

@aeslinger0 I'm using this extension.

I've tried to disable and didn't solve the issue. Only when I disable the integration with Eslint solves.

**Comment by schester44** [comment] 2019-07-09 16:48
I experience this same issue.

VS Code stops formatting my code, calling 'Format Code' doesn't work, and VS Code takes 2+ seconds to save. My fans start running as well.

**Comment by harleyguru** [comment] 2019-07-09 23:19
make sure to disable or uninstall `beautify` extension. When it's enabled, prettier didn't work.

**Comment by timsully** [comment] 2019-07-10 03:24
@harleyguru I had Beautify and Prettier installed at the same time and did what you recommended and Prettier is still unformatting the code once I save my file. Help anyone? Would be much appreciated! @CiGit

**Comment by harleyguru** [comment] 2019-07-10 03:27
@timsully have you increased timeout as mentioned here? https://github.com/prettier/prettier-vscode/issues/181#issuecomment-379540988

uninstall Beautify and other formatter extensions you might have installed and restart VS code.
It should work.

**Comment by timsully** [comment] 2019-07-10 03:28
@harleyguru My timeout is set to `"editor.formatOnSaveTimeout": 3000`

**Comment by timsully** [comment] 2019-07-10 03:32
@harleyguru Identified other code formatters in my plugins and it works! :D Thanks everyone!

**Comment by harleyguru** [comment] 2019-07-10 03:37
lol, @timsully This is not the issue of prettier itself actually. This is the conflict with other plugins.
Happy I could help you!

**Comment by ntotten** [comment] 2019-08-09 14:40
This issue appears to be resolved as such I am closing it. If you are still having problems please feel free to reopen.

**Closed by ntotten** 2019-08-09 14:40 UTC
Labels: bug, need more info

**Comment by jayarjo** [comment] 2020-02-28 10:06
These are the only extension I have, so no additional formatters and still it happens for me:
![Screen Shot 2020-02-28 at 2 04 56 PM](https://user-images.githubusercontent.com/150075/75539223-568af280-5a33-11ea-8e08-16ffddccce01.png)

Although I should say it happens for some files only, mainly those that weren't prettified yet (at least by me) and are especially messy.

**Comment by kiranjd** [comment] 2020-04-14 07:06
I'm facing a similar issue with huge code base in React Native. 

When I save a document, the loading indicator from prettier shows up as as `Saving your document` and it loads for indefinite time. Restarting VS Code doesn't solve it as well.

**Comment by ahayes91** [comment] 2020-04-14 10:38
> I'm facing a similar issue in JS files.
> 
> When I save a document, the loading indicator from prettier shows up as as `Saving your document` and it loads for indefinite time. Restarting VS Code doesn't solve it as well.

Seeing this myself today - wasn't seeing it yesterday

**Comment by effinrich** [comment] 2020-04-15 00:26
> > I'm facing a similar issue in JS files.
> > When I save a document, the loading indicator from prettier shows up as as `Saving your document` and it loads for indefinite time. Restarting VS Code doesn't solve it as well.
> 
> Seeing this myself today - wasn't seeing it yesterday

Yep, I'm also having this issue as of today.  JSX, JS, nothing getting formatted on save or any other way.

**Comment by iljapanic** [comment] 2020-04-19 18:58
I'm having the same issues, I suspect it might have something to do with the latest VS Code update.

I haven't had any issues with the identical setup until today when I updated the VS Code.

**Comment by ntotten** [comment] 2020-04-22 14:02
If you are having issues that seem similar to this, please open a new bug. Commenting on this one does not provide me with any info I can use to debug this. See: https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue
