### ISSUE TITLE
vscode-prettier doesn't format according to defaults in prettier@2.0.2

### ISSUE THREAD

**Issue by trivikr** [prettier/prettier-vscode#1285] opened 2020-04-01 16:24 UTC
### Summary

vscode-prettier doesn't format according to defaults for prettier@2.0.2

### Github Repository to Reproduce Issue

https://github.com/trivikr/prettier-vscode-test

### Steps To Reproduce:

- Clone the repo, and open it in VSCode
- Install [prettier-vscode extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) v3.20.0
- Run `yarn` to install dependencies
- Open [index.js](./index.js), and add trailingComma at the end of array

### Expected result

prettier-vscode should retain trailingComma as per prettier@2 defaults ([link](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-trailingcomma-to-es5-6963httpsgithubcomprettierprettierpull6963-by-fiskerhttpsgithubcomfisker))

### Actual result

prettier-vscode removes trailingComma

### Additional information

<details>
<summary>Recording</summary>

![prettier-vscode-test](https://user-images.githubusercontent.com/16024985/78161524-6a42c380-73fa-11ea-9431-0bdeacdb5fbb.gif)

</details>

**VS Code Version**:
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Prettier Extension Version**:
Extension Name: "prettier-vscode".
Extension Version: "3.20.0".

**OS and version**:
macOS 10.14.6 (18G4032)

## Prettier Log Output

<details>
<summary>LOGS</summary>

```
["INFO" - 9:21:13 AM] Extension Name: "prettier-vscode".
["INFO" - 9:21:13 AM] Extension Version: "3.20.0".
["INFO" - 9:21:13 AM] Loaded module 'prettier@2.0.2' from '/Users/trivikr/workspace/prettier-vscode-test/node_modules/prettier/index.js'
["INFO" - 9:21:13 AM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 9:21:13 AM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 9:21:38 AM] Formatting /Users/trivikr/workspace/prettier-vscode-test/index.js
["INFO" - 9:21:38 AM] Using ignore file (if present) at /Users/trivikr/workspace/prettier-vscode-test/.prettierignore
["INFO" - 9:21:38 AM] Loaded module 'prettier@2.0.2' from '/Users/trivikr/workspace/prettier-vscode-test/node_modules/prettier/index.js'
["INFO" - 9:21:38 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 9:21:38 AM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 9:21:38 AM] Prettier Options:
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine": "auto",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "none",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/Users/trivikr/workspace/prettier-vscode-test/index.js",
  "parser": "babel"
}
["INFO" - 9:21:39 AM] Formatting completed in 56.96916ms.
```

</details>

**Comment by nicolasrouanne** [comment] 2020-04-01 20:10
I have the same issue after bumping `prettier` from 1.9 to 2.0, i.e. **different behavior when running `prettier` on the command line and running `prettier` with _VS Code_**. 
It happens for [`trailingComa`](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-arrowparens-to-always-7430httpsgithubcomprettierprettierpull7430-by-kachkaevhttpsgithubcomkachkaev) and for [`arrowParens`](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-arrowparens-to-always-7430httpsgithubcomprettierprettierpull7430-by-kachkaevhttpsgithubcomkachkaev).

I have **no prettier _configuration file_, I rely on `prettier` default configuration** (which changed between 1.9 and 2.0)

I believed it was a bug in `prettier-vscode`, but it appears it's the intended behavior. When there is no configuration file, either in project or my home directory, `prettier-vscode` [falls back](https://github.com/prettier/prettier-vscode/tree/d3292fad21a2bcf2ef188a5e866f01dc5d7f3c0d#configuration) to [VS Code settings](https://github.com/prettier/prettier-vscode/tree/d3292fad21a2bcf2ef188a5e866f01dc5d7f3c0d#prettiers-settings). It is also [highly recommended](https://github.com/prettier/prettier-vscode/tree/d3292fad21a2bcf2ef188a5e866f01dc5d7f3c0d#configuration) to have a prettier configuration file to prevent this behavior.

That being said, **how do I tell `prettier-vscode` to use the **default** `prettier` settings** - i.e. "no configuration file" settings? 
> I wouldn't like to add a configuration file with copy-pasted default settings; seems brittle and defeats the purpose IMO.

**Comment by nicolasrouanne** [comment] 2020-04-01 20:15
This issue is fixed by #1272 (already merged ATM, waiting for release) and is a possible duplicate of #1275 .

I still think [the question ](https://github.com/prettier/prettier-vscode/issues/1285#issuecomment-607465358)on **relying on `prettier` defaults w/o a _configuration file_** still stands 😉

**Comment by trivikr** [comment] 2020-04-02 00:15
> This issue is fixed by #1272

I believe #1272 updates prettier-vscode to use prettier@2, and it not related to which configuration is used by the extension

**Comment by ntotten** [comment] 2020-04-03 12:53
Fixed in https://github.com/prettier/prettier-vscode/releases/tag/v4.0.0

**Closed by ntotten** 2020-04-03 12:53 UTC

**Comment by trivikr** [comment] 2020-04-03 15:43
v4.0.0 caused a new issue with backward compatibility https://github.com/prettier/prettier-vscode/issues/1290
