### ISSUE TITLE
Cannot find module '../ast-utils' when formating

### ISSUE THREAD

**Issue by usersaurus** [prettier/prettier-vscode#672] opened 2018-12-12 11:22 UTC
Hi all,

I'm getting the following error after installing prettier-vscode and trying to format a file.

`Cannot find module '../ast-utils' `

I have no idea about what's happening.

**Comment by poub** [comment] 2019-01-02 22:16
Hi,
Same error solved by remplacing the User Settings.json file in vs code. Make it basic like that

{
  "terminal.integrated.fontFamily": "Fira mono for Powerline",
  "window.zoomLevel": 1,
  "editor.formatOnSave": true
}

**Comment by IslamWahid** [comment] 2019-01-11 04:12
I just got the same issue

**Comment by IslamWahid** [comment] 2019-01-11 04:16
I think it's related to `eslint` version as I am using this setting `"prettier.eslintIntegration": true`
and it's what causing the issue and this issue just happened to me after upgrading to eslint version `^5.12.0`

**Comment by mrsufgi** [comment] 2019-03-06 13:31
had the same issue, @swansontec was right, had two eslints in my node_modules 

```rm -rf node_modules && yarn```  solved my issues

**Comment by iRoachie** [comment] 2019-06-24 02:06
Is there any resolution for this? Encountering this on eslint 5.16.0

**Comment by Calamari** [comment] 2019-06-24 09:54
@iRoachie, have you tried `rm -rf node_modules` and then running `npm` or `yarn` again as @mrsufgi suggested?

**Comment by 0x80** [comment] 2019-06-24 11:54
Looks like I have the same problem. Re-installing node_modules with yarn didn't do it for me.

**Comment by nfantone** [comment] 2019-06-24 12:21
I think this is down to:

```sh
warning " > eslint-plugin-import@2.17.3" has incorrect peer dependency "eslint@2.x - 5.x".
```

Reverting to `eslint` `5.16.0` works for now.

**Comment by 0x80** [comment] 2019-06-24 14:53
@nfantone 	If I go back to 5.16.x I get errors like:

```
Failed to load plugin '@typescript-eslint' declared in 'CLIOptions'/myproject/src/index.ts:: Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- /__placeholder__.js
```

**Comment by frederikhors** [comment] 2019-06-24 19:10
Same problem here with `eslint 6`.

`rm -rf node_modules` and `npm i` did not help.

**Error:**

`Cannot find module '../util/ast-utils'`

**Comment by frederikhors** [comment] 2019-06-24 19:20
@CiGit this is urgent now.

**Comment by shaodahong** [comment] 2019-06-25 13:59
this error happens in windows, in my mac, is fine

**Comment by frederikhors** [comment] 2019-06-25 19:36
https://github.com/benmosher/eslint-plugin-import/pull/1393 is merged and release but still the same problem. This is urgent. I'm crying...

**Comment by AFu-1993** [comment] 2019-06-26 01:37
> The error doesn't provide much context, so I did `grep ast-utils -R node_modules/`. All the hits were inside eslint, so this is almost certainly an eslint issue. I noticed that my node_modules folder had two copies of eslint, since my project depended on a different version (5.9.0) than prettier-eslint itself (^4.0.0).
> 
> Switching my project to depend on the same eslint as prettier-eslint (specifically, ^4.0.0) solved the problem for me.

### Your
My Eslint version is 6.0.1 . It got wrong in vscode . 

When I install Eslint 4.0.0 , everything was OK.

**Comment by nfantone** [comment] 2019-06-26 11:52
@0x80 I honestly wouldn't know. You seem to be working with TS - I'm not. Most probably one of the plugins you're using _do_ require `eslint@^6.x` Reverting back to latest `eslint@5.x` worked for me.

**Comment by nfantone** [comment] 2019-06-26 11:58
> this error happens in windows, in my mac, is fine

@shaodahong Not actually true, I'm afraid. It fails on macOS as well. AFAIK, this is tied to supporting latest `eslint`. It happens regardless of which OS you are on.

**Comment by shaodahong** [comment] 2019-06-27 02:57
@nfantone sounds bad, hope there fix it

**Comment by bradennapier** [comment] 2019-06-27 03:28
Just ran into this as well so I  assume this is about to really hit the fan if not updated soon :-P

**Comment by samrith-s** [comment] 2019-06-27 14:12
None of this do the trick for me. 

With `eslint@6.0.1` it couldn't read any plugin, got the error @0x80 mentioned. 

With `eslint@5.16.0` it couldn't find `ast-utils`, got the error @frederikhors

**Comment by nfantone** [comment] 2019-06-27 15:24
I've managed to get this working again with latest `eslint-config-prettier` released some hours ago. Here's what I have:

```js
"eslint": "^6.0.1"
"eslint-config-prettier": "^6.0.0"
"eslint-plugin-import": "^2.18.0"
"eslint-plugin-node": "^9.1.0"
"eslint-plugin-prettier": "^3.1.0"
"eslint-plugin-promise": "^4.2.1"
"prettier": "^1.18.2"
```

**Comment by samrith-s** [comment] 2019-06-27 15:45
I am not using `eslint-plugin-node` and `eslint-plugin-promise`, but everything else is the same version:
```json
{
    "eslint": "^6.0.1",
     "eslint-config-prettier": "^6.0.0",
     "eslint-plugin-import": "^2.18.0",
     "eslint-plugin-prettier": "^3.1.0",
}
```

Still doesn't work.

```
6/27/2019, 5:43:41 PM:
----------------------
Failed to load plugin 'prettier' declared in 'CLIOptions'/Users/samrith/Work/totem/serverless-graphql/src/handler.js:: Cannot find module 'eslint-plugin-prettier'
Require stack:
- /__placeholder__.js
```

Setting `prettier.eslintIntegration` to `false` works for now.

**Comment by nfantone** [comment] 2019-06-27 16:33
@samrith-s That looks like an entirely different error to me: `Cannot find module 'eslint-plugin-prettier'`. I've never seen that one. 

Sorry for the brainless question, buy are you sure it's declared and installed on `serverless-graphql`?

**Comment by samrith-s** [comment] 2019-06-27 16:38
I'm positive. 
![image](https://user-images.githubusercontent.com/9032162/60283909-929d0f00-990a-11e9-9eb2-2787cf016cd0.png)
This is my go-to setup. I've used it in 50+ apps and it has always worked. Somehow, every single project broke in the last 3-4 days.

**Comment by nfantone** [comment] 2019-06-27 17:42
@samrith-s Apart from the obvious stuff (try removing the lockfile, `rm -rf node_modules/` and `yarn` or `npm i`, again), I cannot think of a reason why it wouldn't work for you.

`prettier` is working as expected in all the projects I've updated so far.

**Comment by 0x80** [comment] 2019-06-27 18:23
@nfantone 	I've upgraded all my dependencies to latest, removed node_modules and yarn.lock and reinstalled + restarted vscode. 

Still the same ast-utils error for me. This is with versions:

```
    "eslint": "^6.0.1",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.2",
    "prettier": "^1.18.2",
````

**Comment by samrith-s** [comment] 2019-06-28 08:33
@nfantone I’ve tried all the possible solutions out there. The only thing that works is disabling `prettier.eslintIntegration`. I’m almost positive this is an error in `prettier-vscode` while using enabling ESLint integration.

**Comment by acmilank22** [comment] 2019-06-28 09:47
> @nfantone I’ve tried all the possible solutions out there. The only thing that works is disabling `prettier.eslintIntegration`. I’m almost positive this is an error in `prettier-vscode` while using enabling ESLint integration.

the same.

#863

**Comment by nfantone** [comment] 2019-06-28 11:23
@acmilank22 @0x80 @samrith-s Strange. Like I said, it did work for me after upgrading - so can't exactly back up the `prettier-vscode` fault theory. Which `node` version are you guys running on? I'm on `10.16.0` LTS.

```sh
❯ node -v
v10.16.0
```

**Comment by samrith-s** [comment] 2019-06-28 12:26
Another thing I noticed, if you have installed latest version of Node (mine is `12.4.0`), it breaks. After downgrading to Node 10, it works as expected.

**Comment by samrith-s** [comment] 2019-06-28 12:28
> Enabling prettier.eslintIntegration makes VSCode use prettier-eslint, instead of prettier binary. Which is something I'm not doing. This might be it, then. And there's actually no real need for using prettier-eslint if you configure your lint rules appropriately.

Yes, but it's strange that it's been working with that enabled for so long now, and suddenly in the last 3-4 days, it breaks.

**Comment by nfantone** [comment] 2019-06-28 12:39
> Another thing I noticed, if you have installed latest version of Node (mine is 12.4.0), it breaks. 

@samrith-s I was actually going to ask you this (check the "Edit" history on my [previous comment](https://github.com/prettier/prettier-vscode/issues/672#issuecomment-506700106)!). I'm on LTS.

```sh
❯ node -v
v10.16.0
```

But, anyway, I'd ditch `prettier-eslint` entirely. Doesn't have much use other than facilitating initial setup - which, if you have been working on 50+ projects in the past like it was mentioned, should not pose a problem.

**Comment by samrith-s** [comment] 2019-06-28 12:42
Yep, ditching it entirely from now on, so that no such problem occurs. Thanks a lot @nfantone for that comment, helped me debug in that direction! 😁

**Comment by EthanNYT** [comment] 2019-06-28 17:13
> But, anyway, I'd ditch `prettier-eslint` entirely. Doesn't have much use other than facilitating initial setup

Then I'd need an ESLint config file and a Prettier config file, right? And have to make sure any changes you make to one you have to make to the other, etc.

**Comment by Preeternal** [comment] 2019-06-30 16:53
I have to downgrade eslint version because the issue. I hope the solution will come.

**Comment by jimblue** [comment] 2019-07-03 20:36
Hi,

I'm also having the same issue on mac latest version of Vscode with eslint 6.

Thanks for your help

**Comment by piotrblasiak** [comment] 2019-07-04 05:43
Same here. Latest version and not even disabling prettier-eslint helped.

**Comment by samrith-s** [comment] 2019-07-04 17:10
Disabling `prettier-eslint` breaks everything in the code. I'd rather downgrade ESLint version and use Node 10 rather than do that.

**Comment by nfantone** [comment] 2019-07-04 17:13
@EthanNYT 

> Then I'd need an ESLint config file and a Prettier config file, right? 
No, not really. There are `eslint-plugin-prettier` and `eslint-config-prettier` that handle that for you. And `prettier` doesn't even need one (defaults work well enough). Although, there's nothing preventing you from configuring them separately.

> Also, it seems that ESLint has many settings that are missing from Prettier.
Those would still apply and won't conflict with each other. What would the issue be here?

Here's my typical `eslint` + `prettier` configuration for `node` projects (I like to use `standard` + semicolon).

```js
// package.json
{
    "eslint": "^5.16.0",
    "prettier": "^1.18.2",
    "eslint-config-prettier": "^4.3.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-promise": "^4.1.1",
    "eslint-plugin-standard": "^4.0.0"
}
```

```js
// .eslintrc.json
{
  "extends": [
    "standard",
    "prettier/standard",
    "plugin:prettier/recommended"
  ],
  "parserOptions": {
    "sourceType": "script"
  },
  "env": {
    "node": true,
    "jest": true
  },
  "rules": {
    "semi": [
      2,
      "always"
    ],
    "no-extra-semi": 2,
    "strict": [
      "error",
      "global"
    ]
  }
}
```

```js
// .prettierrc
{
  "singleQuote": true,
  "printWidth": 100
}
```

That's all you need.

**Comment by wangnengjie** [comment] 2019-07-05 12:45
I‘m new in web front-end. I had same problems and struggled for two days.

>With eslint@6.0.1 it couldn't read any plugin, got the error @0x80 mentioned.
>With eslint@5.16.0 it couldn't find ast-utils, got the error @frederikhors

Now it runs well,emm..., but I don't know why it can run well now.
Maybe my settings can give you some ideas.
I use `ts`+`react`
Belows are my configs:
1. vscode settings
```
"prettier.eslintIntegration": true 
// Of course it can run well if I set false. But it is not what I want to see.
```
2. package.json
```
// some moudule might be useless...It's just the result of my torment.
"eslint": "5.16.0", // yes, I can run it with `version 5.16.0` now 
"eslint-config-prettier": "^6.0.0",
"eslint-config-react-app": "^4.0.1",
"eslint-plugin-babel": "^5.3.0",
"eslint-plugin-flowtype": "^3.11.1",
"eslint-plugin-import": "^2.18.0",
"eslint-plugin-jsx-a11y": "^6.2.3",
"eslint-plugin-prettier": "^3.1.0",
"eslint-plugin-react": "^7.14.2",
"eslint-plugin-react-hooks": "^1.6.1",
```
3. .eslintrc
```
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "babel", "flowtype", "prettier", "react"],
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "modules": true,
      "jsx": true
    },
    "useJSXTextNode": true,
    "project": "./tsconfig.json"
  },
  "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:flowtype/recommended",
    "plugin:react/recommended",
    "prettier",
    "prettier/@typescript-eslint",
    "prettier/babel",
    "prettier/flowtype",
    "prettier/react"
  ],
  "rules": {
    // I remember that some rules will infulence the output of prettier in vscode. For example: 
    // I remove "@typescript-eslint/restrict-plus-operands": "error" and one problem disappear
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/no-explicit-any": 0,
    "@typescript-eslint/no-var-requires": 0,
    "@typescript-eslint/explicit-member-accessibility": 0
  },
  "settings": {
    // it is just to fix an warning in the output of eslint.
    // for file integrality, I paste it.
    "react": {
      "version": "999.999.999"
    }
  }
}
```
Hope my comment can help.

**Comment by EthanNYT** [comment] 2019-07-05 15:12
@nfantone @wangnengjie I like the `eslint-plugin`-based solutions, seems obvious in hindsight, thanks!

Also @ @wangnengjie 

> It's just the result of my torment

We've all been there   😁

**Comment by wangnengjie** [comment] 2019-07-05 15:40
Also, there is another thing a little strange. 
Before I went back to `5.16.0`, I try to downgrade eslint version...like `5.14.0`, then `5.12.0`, and then `5.8.0`. Finally `5.4.0` works well. 
But when I tried to upgrade, even `5.14.0` can work. Every time I changed the version, I reloaded vscode and make sure that there were no copied versions in node_modules.
But back to `6.0.1` error of this issue occured. Then `5.16.0`, another error. But after I remove one of the rules (just I mentioned above). Every thing went well.
 I don't even know whether the same problem will occur again tomorrow...QAQ

**Comment by dijam** [comment] 2019-07-08 07:27
I had similar problem for a while. I did everything possible. Downgrading and use fix versions. Even copy-paste from other folders/projects that work but didn't work.
Tried empty project with exact packages and it worked but when implement the same in my current project it wouldn't.
But, when Code released the new version, all went back to normal :) I assume MSCode was using some packages that messed up my configs that technically should have the highest priority when loading eslint config. 
Anyway, All good and I can work again :) 
My current versions: `"eslint": "^5.16.0","prettier": "^1.17.0",`
MSCode version: `1.36.0`

**Comment by adriangrahl** [comment] 2019-07-09 02:24
Updating MSCode to 1.36.0 fixed the issue for me too.

**Comment by 0x80** [comment] 2019-07-14 15:24
@dijam 	@adriangrahl 	Is VSCode called MSCode now? Did I miss the memo?

**Comment by mikemak-es** [comment] 2019-07-15 11:36
I'm still getting this issue despite following @dijam comment.

my versions and settings are below:

System:
macOS: 10.14.5
Node: 12.6.0
VSCode: 1.36.1

Project Package.json:
"eslint-plugin-react": "^7.14.2",
"eslint": "^5.16.0",
"prettier": "^1.17.0",

VSCode setting:
prettier.eslintIntegration: true

**Comment by nvtuan305** [comment] 2019-07-15 17:04
Downgrade eslint to previous working version not helped. I'm getting this issue.

**Comment by kamos1** [comment] 2019-07-18 01:56
I did a global uninstall and a local uninstall then reinstalled everything locally and now things are working.
```
    "eslint": "^6.0.1",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "prettier": "^1.18.2"

**Comment by Carrie999** [comment] 2019-07-19 09:10
for vscode how to handle ?

**Comment by Carrie999** [comment] 2019-07-19 09:54
delete eslint  Getting better

**Comment by nvtuan305** [comment] 2019-07-19 16:16
At the current, my working solution is **disable ESlint Integration setting** in vscode while waiting for new update version.

[1] Turn off ESlint Integration setting in vscode

[2] Install eslint, eslint-config-google (I'm using config from Google)
```
     npm i --save-dev eslint eslint-config-google
```
The newest version will be:
```
    "eslint": "^6.0.1",
    "eslint-config-google": "^0.13.0"
```

[3] Configure eslint and prettier to make it work as expected

`.eslintrc.json`
```json
{
  "extends": ["google"],
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "rules": {
    "object-curly-spacing": ["error", "always"],
    "max-len": ["error", 80],
    "indent": [2, 2, {"SwitchCase": 1}]
  }
}
```

`.prettierrc`
```json
{
  "semi": true,
  "trailingComma": "es5",
  "singleQuote": true,
  "printWidth": 80,
  "arrowParens": "always"
}
```

With this configuration, I got the result as expected before getting error  😄 😄 😄

**Comment by YIREN1** [comment] 2019-07-20 20:09
on  
`eslint "^5.16.0",   
"prettier": "^1.18.2"`

And it works for me if I delete all modules about eslint and reinstall them

**Comment by jimblue** [comment] 2019-07-20 21:07
This issue isn't the real issue, this is just a consequence.
The real problem come from **prettier-vscode** compatibility with ESlint 6...
This topics is becoming a mess a bit more each day and it should be close in favor of #870 !

**Comment by iKnowMagic** [comment] 2019-07-26 16:55
I had a similar problem, in which prettier in vscode simply refused to format my code. I deleted any entry in my **settings.json** file in vscode that contained the string `"editor.defaultFormatter"` such as **`"editor.defaultFormatter": "esbenp.prettier-vscode"`**, and now everything is working as expected.

Other related **settings in vscode** look like this:

```
{
...
  "eslint.alwaysShowStatus": true,
  "eslint.autoFixOnSave": true,
  "eslint.packageManager": "yarn",
  "eslint.run": "onType",
  "eslint.validate": [
    {
      "autoFix": true,
      "language": "vue"
    },
    {
      "autoFix": true,
      "language": "javascript"
    },
    {
      "autoFix": true,
      "language": "html"
    },
    {
      "autoFix": true,
      "language": "javascriptreact"
    }
  ],
  "javascript.format.enable": true,
  "javascript.validate.enable": false,
  "prettier.eslintIntegration": true,
  "prettier.stylelintIntegration": true,
...
}

```

The related packages in my **package.json** file look like this:

```
    "eslint": "^6.1.0",
    "eslint-config-prettier": "^6.0.0",
    "eslint-config-vue": "^2.0.2",
    "eslint-plugin-flowtype": "^3.12.1",
    "eslint-plugin-flowtype-errors": "^4.1.0",
    "eslint-plugin-html": "^6.0.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-vue": "^5.2.3",
    "prettier": "^1.18.2",
```

If interested, my **.eslintrc.js** file looks like this:

```
module.exports = {
  root: true,
  env: {
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    'plugin:flowtype-errors/recommended',
    'plugin:vue/recommended',
    '@vue/standard',
    'prettier',
    'prettier/standard',
    'prettier/vue'
  ],
  plugins: ['flowtype-errors', 'prettier'],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'space-before-function-paren': ['warn', 'never'],
    'no-unused-vars': 'warn',
    'vue/name-property-casing': ['warn', 'PascalCase'],
    'vue/component-name-in-template-casing': ['warn', 'kebab-case'],
    'vue/no-unused-components': 'warn',

    'array-bracket-newline': ['warn', 'consistent'],
    'array-element-newline': ['warn', 'consistent'],
    'object-curly-newline': ['warn', { consistent: true }],
    'function-paren-newline': ['warn', 'consistent']
  },
  overrides: [
    {
      files: ['**/*.test.js'],
      parserOptions: {
        parser: 'babel-eslint',
        sourceType: 'module'
      },
      env: { jest: true },
      globals: {
        mount: false,
        shallowMount: false,
        shallowMountView: false,
        createComponentMocks: false,
        createModuleStore: false
      },
      rules: {
        'no-undef': 'off'
      }
    }
  ]
}
```

**Comment by AveDemid** [comment] 2019-07-29 08:54
The problem is with prettier-vscode. but it seems I made everything work, so I will share my configuration. 

`// Validation
  "javascript.validate.enable": false,
  "typescript.validate.enable": false,
  // Eslint
  "eslint.autoFixOnSave": true,
  "eslint.validate": [
    {
      "language": "javascript",
      "autoFix": true
    },
    {
      "language": "javascriptreact",
      "autoFix": true
    },
    {
      "language": "typescript",
      "autoFix": true
    },
    {
      "language": "typescriptreact",
      "autoFix": true
    }
  ],
  // Format on save
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.formatOnSave": false
  },
  "[javascriptreact]": {
    "editor.formatOnSave": false
  },
  "[typescript]": {
    "editor.formatOnSave": false
  },
  "[typescriptreact]": {
    "editor.formatOnSave": false
  },
  // Prettiner
  "prettier.eslintIntegration": true`

`module.exports = {
  parser: "@typescript-eslint/parser",
  extends: [
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended"
  ],
  parserOptions: {
    ecmaVesion: 2018,
    sourceType: "module"
  },
  rules: {
    // React
    "react/display-name": "off",
    // TypeScript
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/indent": ["error", 2],
    "@typescript-eslint/no-unused-vars": "warn"
  },
  plugins: ["react-hooks"],
  settings: {
    react: {
      version: "detect"
    }
  }
};
`

**Comment by douglas-cavalcante** [comment] 2019-08-03 15:44
run yarn add prettier eslint-config-prettier eslint-plugin-prettier babel-eslint -D  in project.

**Comment by douglas-cavalcante** [comment] 2019-08-10 03:42
eslint:
yarn add eslint-plugin-react eslint-plugin-react-native eslint-config-airbnb eslint@^4.19.1 eslint-plugin-import eslint-plugin-jsx-a11y -D

eslint+prettier:
yarn add prettier eslint-config-prettier eslint-plugin-prettier babel-eslint -D

**Comment by max-lychko** [comment] 2019-08-11 21:20
Upgrade VSCode to 1.37.0
Hope this help

**Comment by ntotten** [comment] 2019-08-12 16:04
Duplicate of #870

**Closed by ntotten** 2019-08-12 16:04 UTC

**Comment by Mr-SPM** [comment] 2019-08-14 13:00
> Also, there is another thing a little strange.
> Before I went back to `5.16.0`, I try to downgrade eslint version...like `5.14.0`, then `5.12.0`, and then `5.8.0`. Finally `5.4.0` works well.
> But when I tried to upgrade, even `5.14.0` can work. Every time I changed the version, I reloaded vscode and make sure that there were no copied versions in node_modules.
> But back to `6.0.1` error of this issue occured. Then `5.16.0`, another error. But after I remove one of the rules (just I mentioned above). Every thing went well.
> I don't even know whether the same problem will occur again tomorrow...QAQ

downgrade 5.4.0 . it works !!!

**Comment by toastyboost** [comment] 2019-08-14 14:39
please help

**Comment by zfeher** [comment] 2019-08-17 17:33
Downgrading to 5.4.0 helped made it work. After that doing a couple of upgrades: to 5.14.0, 5.15.3 and eventually to 5.16.0 all started to work again for some reason \o/ Thank you @Mr-SPM for this tip.

Before that I tried to remove all eslint dependencies and reinstall them, it didn't work. Tried the `rm -rf node_modules && npm i` treatment, it didn't work. Strange beast, hope it stays working.

**Comment by VahanAper** [comment] 2019-08-23 13:09
Upgrading eslint from `6.1.0` to `6.2.0` fixed the problem for me

**Comment by samrith-s** [comment] 2019-08-26 13:35
Neither ESLint `5.16` or `^6` works. Only `5.4` works for me. For `6.x`, there's this error https://github.com/microsoft/vscode-eslint/issues/696

**Comment by zbeyens** [comment] 2019-08-26 16:30
This worked for me (using `eslint-plugin-prettier`):

- add `eslint@^5.16.0` in `package.json`
- `rm -rf node_modules && yarn`
- disable `prettier.eslintIntegration` ([deprecated](https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration))
- enable `eslint.autoFixOnSave`
- disable prettier for javascript (eslint does the work):
```json
"prettier.disableLanguages": [
  "javascript"
]
```

**Comment by Rennzie** [comment] 2019-08-30 05:54
Incase this is still an issue, I found that changing 

`"prettier.eslintIntegration": true` 

to

`"prettier-eslint.eslintIntegration": true`

 in Settings (JSON) for VS Code fixed all the issues with prettier and eslint. I've managed to upgrade to the latest version of prettier and eslint and things are working as expected.

**Comment by mort3za** [comment] 2019-09-12 07:47
Seems "prettier.eslintIntegration" config is now deprecated. there are a deprecation and solution in the readme: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration

**Comment by madflanderz** [comment] 2019-11-07 17:47
I had the same weird problem. I use eslint with eslint-plugin-prettier together. Somehow this was colliding with VSCode prettier plugin. After i disabled VSCode prettier plugin and using only eslint it was working again. Also had to set "eslint.autoFixOnSave" to true.

**Comment by akmur** [comment] 2020-02-06 10:01
For some reason removing the vs code prettier plugin worked for me

**Comment by ntotten** [comment] 2020-02-10 18:15
If you are using ESLint to do formatting, another option instead of disabling the plugin would be to disable prettier from formatting the languages you want to be handled by ESLint. You can do this with the by adding a `.vscode/settings.json` file to your project with the following content:

```
{
    "prettier.disableLanguages": ["js"]
}
```
