### ISSUE TITLE
Missing way set --config option

### ISSUE THREAD

**Issue by hayes** [prettier/prettier-vscode#394] opened 2018-03-15 19:03 UTC
Prettier exposes a --config option to specify a path to a config file.  This is useful if you want to put you config for prettier in a shared module.  Currently the vscode plugin does not expose any way to set this option.

**Comment by CiGit** [comment] 2018-03-17 10:52
You can use your shared config by requiring it. 
.prettierrc.js
```js
module.exports = require('path/to/shared/settings')
```

**Comment by hayes** [comment] 2018-03-17 15:42
Yup, not a hard problem to work around, just something that could be nice to have in the future. If I have some time later this weekend I might try to put a PR together

**Comment by CiGit** [comment] 2018-04-30 13:46
Closing as duplicate of #254

**Closed by CiGit** 2018-04-30 13:46 UTC
Labels: enhancement
