### ISSUE TITLE
Prettier does not work as default formatter in VS Code 1.57.1 on Windows.

### ISSUE THREAD

**Issue by KerimG** [prettier/prettier-vscode#2047] opened 2021-06-29 09:00 UTC
### Summary

I have the Prettier extension installed, have the prettier npm package installed globally and in this project. It seems as though the Prettier extension is not starting and is missing in the VS Code status bar.

![image](https://user-images.githubusercontent.com/9061713/123767649-ec54bd00-d8c7-11eb-8e6c-3c1a9adadc5c.png)

When I try to save a file that I know to have no errors, I get the error `"Extension 'Prettier - Code fromatter' cannot format 'src\index.js'"`

My relevant settings:
```
{
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

Manually formatting doesn't work either. Running prettier in the command line does correctly format the file.

_Short summary of what is going on or to provide context_.

It works fine on my Mac. Both VS Code installations are fine and settings are synced.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  Install Prettier extension
1.  Try to save a file
2.  Alternatively, try to format manually.

### Expected result

The file should have been formatted upon saving it.

### Actual result

I get the error `"Extension 'Prettier - Code fromatter' cannot format 'src\index.js'"`

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

**Prettier Extension Version**:
8.0.1

## Prettier Log Output
Cannot create log output, because Prettier is missing from the toolbar.

**Comment by ntotten** [comment] 2021-06-30 01:15
Are there any messages about the extension in the other logs?

**Comment by JessicaOPRD** [comment] 2021-06-30 01:39
Unsure if any others with this problem have this in their `exthost.log`? I think I upgraded around this timestamp, but I didn't notice the extension wasn't working until today.

```
[2021-06-28 10:16:29.856] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-28 10:16:29.856] [exthost] [error] TypeError: Cannot assign to read only property 'prettierPath' of object '#<Object>'
	at Object.t.getConfig (c:\Users\[name]\.vscode\extensions\esbenp.prettier-vscode-8.0.1\dist\extension.js:1:21612)
	at e.activate (c:\Users\[name]\.vscode\extensions\esbenp.prettier-vscode-8.0.1\dist\extension.js:1:73278)
	at Function._callActivateOptional (c:\Users\[name]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:14966)
```

Thank you for looking at this!

**Comment by KerimG** [comment] 2021-06-30 03:38
@ntotten and @JessicaOPRD 

Thanks for the help. How do I access the `exthost.log` file?

**Comment by JessicaOPRD** [comment] 2021-06-30 03:54
I wasn't sure either, or aware that there were other logs. I did ctrl + shift + p, searched "log," and selected "Developer: Open Extension Logs Folder."

**Comment by KerimG** [comment] 2021-06-30 10:09
Thank you @JessicaOPRD 

but the only relevant entries I have in my `exthost.log` are the following lines:

```
[2021-06-30 12:04:50.288] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-06-30 12:04:50.288] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/kg/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension
```

I don't know what happened but it seems to work now. It's really mysterious. Does it work for you now?

**Comment by JessicaOPRD** [comment] 2021-06-30 17:01
I am wondering if that log clears out on every restart of VSCode. After closing it and restarting VSCode, the error above wasn't in my logs anymore, just the same one you have. But my Prettier extension still wasn't working. I rebooted the machine and it's working now. 🙌

This version of VSCode seemed to need my permission to access the folder my code was in. A dialog popped up asking for it, which I gave. Possibly a permissions issue? That is my only guess.

Thank you for posting this so I could see it wasn't just me! I'm glad it's resolved for you too.

**Comment by yurtkuran** [comment] 2021-06-30 17:24
Having the same issue on a Mac

**Comment by JessicaOPRD** [comment] 2021-06-30 17:27
I did just see that if you open the extension log file as described above, you can navigate up to the root `logs` folder and possibly find older logs. I re-found that error in those logs. But it looks like they won't be around long based on timestamps.

**Comment by KerimG** [comment] 2021-07-01 05:25
Thank you, @JessicaOPRD . I managed to dig through some of those logs and think I found the culprit. Timestamp seems to match with the time I had the issue:

```
[2021-06-30 13:40:51.508] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/kg/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension
[2021-06-30 13:40:51.608] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-30 13:40:51.608] [exthost] [error] TypeError: Cannot assign to read only property 'prettierPath' of object '#<Object>'
	at Object.t.getConfig (c:\Users\kg\.vscode\extensions\esbenp.prettier-vscode-8.0.1\dist\extension.js:1:21612)
	at e.activate (c:\Users\kg\.vscode\extensions\esbenp.prettier-vscode-8.0.1\dist\extension.js:1:73278)
	at Function._callActivateOptional (c:\Users\kg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:14966)
	at Function._callActivate (c:\Users\kg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:14639)
	at c:\Users\kg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12799
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

I didn't have to do anything to fix it. I uninstalled the extension and used VS Code without it for a while and after I installed it again in the evening, it worked. What's freaky is that I _did_ try to uninstall and re-install when I first noticed the problem.

In the error message it looks like the error is an attempt to write to a read-only property. Is it perhaps a problem with VS Code's new restricted mode?

**Comment by KerimG** [comment] 2021-07-01 07:37
There is something super funky going on. It might be a VS Code problem, because now my "LiveServer"-Extension doesn't work.

**Comment by W2AlharbiMe** [comment] 2021-07-02 19:47
okay after i updated my vscode to latest version, prettier stopped working i got the following message when i save a file at the bottom left: "prettier was unable to format /../../../" 

so after disable prettier and enable it again i set it as the default formatter and now its working correctly 
but i don't know what happened exactly my vscode theme was reset to the default

**Comment by vpoiesz** [comment] 2021-07-09 00:19
Same issue here. 

exthost.log:

```
[2021-06-28 12:47:53.822] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-06-28 12:47:53.822] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/victorpoiesz/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension
[2021-06-28 12:47:54.018] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-28 12:47:54.018] [exthost] [error] TypeError: Cannot assign to read only property 'prettierPath' of object '#<Object>'
	at Object.t.getConfig (/Users/victorpoiesz/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension.js:1:21612)
	at e.activate (/Users/victorpoiesz/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension.js:1:73278)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:14948)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:14621)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12781
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

VS Code info:

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

Worked after reinstall and restarting VS Code.

**Comment by LittleStoney** [comment] 2021-07-09 06:20
same problem

**Comment by AlexanderArvidsson** [comment] 2021-07-12 14:26
Disabling, reloading prettier and enabling it again seems to have fixed it. Problem does not appear again after restarting, so it seems like this fixed it completely for me so far.

**Comment by matt-jolt** [comment] 2021-07-15 16:19
Had the same problem on a mac, but the disable, reenable hack worked for me.

**Closed** 2021-07-18 12:54 UTC

**Comment by Marcono1234** [comment] 2021-08-29 17:20
@KerimG, would you mind reopening this issue? I can consistently reproduce this `Cannot assign to read only property 'prettierPath' of object '#<Object>'` error for untrusted workspaces (VSCode shows "Restricted Mode" in the bottom left corner).
Or should I create a new issue?

**Comment by ntotten** [comment] 2021-09-02 13:25
Please create a new issue and follow our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue).

**Comment by Marcono1234** [comment] 2021-09-06 13:13
@ntotten have created #2165 for it.
