### ISSUE TITLE
Fails to format when "editor.formatOnSaveMode": "modifications" is set

### ISSUE THREAD

**Issue by elektronik2k5** [prettier/prettier-vscode#1677] opened 2020-12-02 10:49 UTC
Hello and thanks for releasing and maintaining this wonderful extension! :bowing_man: 

### Summary

Extension fails to format `.component.html` files when VSCode's `"editor.formatOnSaveMode": "modifications"` is set.

### Steps To Reproduce:

1.  Set `"editor.formatOnSaveMode": "modifications"` in VSCode settings
1.  Try to format using extension (on save or via command)

### Expected result

`path/to/file.component.html` file should be formatted.

### Actual result

Status bar shows `Extension 'Prettier - Code Formatter' cannot format file path/to/file.component.html` and file isn't formatted.

### Additional information

Unsetting `"editor.formatOnSaveMode": "modifications"` in VSCode settings fixes the issue. I suspect that the interop between VSCode's edited ranges and prettier's range is broken. The extension should either implement it or state and fail explicitly if this feature isn't supported.

**VS Code Version**:
```shell
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.8-200.fc33.x86_64
```

**Prettier Extension Version**:
`v5.8.0`

**OS and version**:
Fedora `Linux hp 5.9.8-200.fc33.x86_64 #1 SMP Tue Nov 10 21:58:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

## Prettier Log Output

This is strange, cause the output doesn't show an error. Perhaps it is incorrect?
```log
["INFO" - 20:50:53] Using config file at '/[redacted path]/.prettierrc.yaml'
["INFO" - 20:50:53] Prettier Options:
{
  "filepath": "/[redacted path]/src/[redacted path]/file.component.html",
  "parser": "angular",
  "useTabs": false,
  "tabWidth": 2,
  "printWidth": 120,
  "semi": true,
  "singleQuote": true,
  "quoteProps": "as-needed",
  "jsxSingleQuote": false,
  "trailingComma": "all",
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "arrowParens": "always",
  "endOfLine": "lf",
  "embeddedLanguageFormatting": "auto"
}
["INFO" - 20:50:53] Formatting completed in 357.514512ms.
```

**Comment by ntotten** [comment] 2020-12-09 20:15
We don't and probably won't (due to how prettier works) support this formatting mode. I'll look to see if we can show a better error.

**Comment by elektronik2k5** [comment] 2020-12-10 02:54
Thank you. Do you mind elaborating (or referring to) the reason why they're incompatible?

**Comment by ntotten** [comment] 2021-04-05 15:32
Duplicate of #1562

**Closed by ntotten** 2021-04-05 15:32 UTC
Labels: enhancement
