### ISSUE TITLE
Version 1.10 gives error "Cannot read property 'appendLine' of undefined

### ISSUE THREAD

**Issue by polvalente** [prettier/prettier-vscode#918] opened 2019-08-23 22:38 UTC
### Summary

Cannot use version 1.10 to format code

### Steps To Reproduce:

1.  Try to format

### Expected result

Formatter code

### Actual result

Error with following log:
```
[2019-08-23 19:34:15.456] [exthost] [error] TypeError: Cannot read property 'appendLine' of undefined
	at Object.addToOutput (/home/valente/.vscode/extensions/esbenp.prettier-vscode-1.10.0/out/errorHandler.js:60:19)
	at Object.requireLocalPkg (/home/valente/.vscode/extensions/esbenp.prettier-vscode-1.10.0/out/requirePkg.js:34:24)
	at /home/valente/.vscode/extensions/esbenp.prettier-vscode-1.10.0/out/PrettierEditProvider.js:42:44
	at Generator.next (<anonymous>)
	at __awaiter (/home/valente/.vscode/extensions/esbenp.prettier-vscode-1.10.0/out/PrettierEditProvider.js:7:71)
	at new Promise (<anonymous>)
	at __awaiter (/home/valente/.vscode/extensions/esbenp.prettier-vscode-1.10.0/out/PrettierEditProvider.js:3:12)
	at format (/home/valente/.vscode/extensions/esbenp.prettier-vscode-1.10.0/out/PrettierEditProvider.js:40:12)
	at PrettierEditProvider._provideEdits (/home/valente/.vscode/extensions/esbenp.prettier-vscode-1.10.0/out/PrettierEditProvider.js:160:16)
	at PrettierEditProvider.provideDocumentFormattingEdits (/home/valente/.vscode/extensions/esbenp.prettier-vscode-1.10.0/out/PrettierEditProvider.js:154:21)
	at define.provideDocumentFormattingEdits.o.asPromise (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:558:372)
	at t.asPromise.Promise (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:720)
	at new Promise (<anonymous>)
	at Object.t.asPromise (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:692)
	at P.provideDocumentFormattingEdits (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:558:343)
	at define.$provideDocumentFormattingEdits._withAdapter.e (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:573:896)
	at W._withAdapter (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:569:219)
	at W.$provideDocumentFormattingEdits (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:573:874)
	at d._doInvokeHandler (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:668:1006)
	at d._invokeHandler (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:668:698)
	at d._receiveRequest (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:667:293)
	at d._receiveOneMessage (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:666:141)
	at define.constructor._protocol.onMessage.e (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:664:400)
	at u.fire (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at a (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:179:815)
	at e (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:179:861)
	at u.fire (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at n.constructor.e.onMessage.e (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:775:104)
	at u.fire (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at a (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:179:815)
	at e (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:179:861)
	at u.fire (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at y._receiveMessage (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:188:834)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:116)
	at u.fire (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at f.acceptChunk (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:588)
	at define.constructor._register._socket.onData.e (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:919)
	at Socket.t (/snap/code/13/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:190:329)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.37.1
f06011ac164ae4dc8e753a3fe7f9549844d15e35
x64

**Prettier & Prettier Plugin Version**: 1.18.2 & 1.10

**OS and version**: Ubuntu 18.04.3 LTS

**Comment by eemeli** [comment] 2019-08-24 10:32
I'm experiencing the same error, on VS Code 1.37.1 on macOS Mojave. Formatting files with command-line Prettier (1.18.2) works without problems. Also, #921 looks like a dupe of this.

**Comment by ntotten** [comment] 2019-08-24 12:18
I am unable to reproduce this. I suspect it is something with ESLint. Can you provide details about 1) your prettier extension settings and 2) the versions of the modules you are using (prettier, eslint, etc)

**Comment by ntotten** [comment] 2019-08-24 12:57
Should be fixed in 1.12.0. Let me know if you are still having the issue.

**Closed by ntotten** 2019-08-24 12:57 UTC

**Comment by eemeli** [comment] 2019-08-24 13:09
Thank you @ntotten, 1.12.0 does work at least for me!

**Comment by parkerault** [comment] 2019-11-04 17:28
I'm getting this error message in the status bar, but I haven't been able to find any related entries in the logs. Where should I be looking for that?

Since a few days ago I can't format any files, and the "Format document with..." command has disappeared from the command palette. All extension preferences are set to default, I'm not using eslint (directly, but react-scripts does have its own linting configuration), and there are no other code formatting extensions installed. I'm using wsl with the remote-wsl extension and react-scripts v3.0.1.

VSCode version:
```
Version: 1.40.0-insider (user setup)
Commit: 37d34176a6ecf1d09b16a0cad11bb619f3b1e48f
Date: 2019-11-01T10:19:19.506Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134
```
prettier-vscode version: `2.3.0`

**Comment by codebykenny** [comment] 2019-11-10 00:11
I am getting the same error on WSL using 2.3.0

**Comment by Empereol** [comment] 2019-11-29 13:47
Also getting the message, `Extension `Prettier - Code formatter` cannot format ...`

![image](https://user-images.githubusercontent.com/746530/69872876-b3380f00-1284-11ea-84b1-2c4ef5c84b06.png)

Only happening to me using version `3.10.0` and above. If I downgrade to `3.9.0` it works fine.

**Comment by parkerault** [comment] 2019-11-30 01:15
Whoops, I should have come back here and posted my solution! In my case it was a corrupted install, maybe from the sync settings extension. What I discovered is that the extensions were still hanging around even after I uninstalled them from the editor. They get cached in ~/.vscode-server/extensions. I deleted everything in that directory, opened up vscode and reinstalled my extensions, and everything started working again. Hopefully this solves your problem too.

**Comment by 93Akkord** [comment] 2019-12-12 16:06
> Also getting the message, `Extension 'Prettier - Code formatter' cannot format ...`
> 
> ![image](https://user-images.githubusercontent.com/746530/69872876-b3380f00-1284-11ea-84b1-2c4ef5c84b06.png)
> 
> Only happening to me using version `3.10.0` and above. If I downgrade to `3.9.0` it works fine.

Same worked for me, but I was on 3.11.0.  3.9.0 works fine as mentioned.

**Comment by vielhuber** [comment] 2019-12-22 22:17
same here. 3.16.1 works, 3.17.0 and 3.18.0 do not.

**Comment by okovalov** [comment] 2020-01-16 14:52
@vielhuber same here. 3.18.0 does not work. throwing an error saying could not format the document and so on...

**Comment by malthoff** [comment] 2020-01-20 16:05
Same here. But even downgrading does not work.

**Comment by okovalov** [comment] 2020-01-20 19:39
@malthoff actually, I got it working somehow - I use eslint itself and I when had 
```
  "prettier.disableLanguages": [
    "javascript",
    "javascriptreact"
  ],
```
that did not work. please check, perhaps you have it disabled too?
so, when your project does not use eslint (therefore there is no .eslintrc and related packages installed) and you have prettier disabled in your config, then it wont work.. I hope it helps.

**Comment by malthoff** [comment] 2020-01-21 07:30
I am using TSlint, not ESlint. Couldn't figure out why this is not working anymore.

**Comment by okovalov** [comment] 2020-01-22 14:49
@malthoff I was finally able to make it work for type script and javascript with eslint. it took a while to figure out, but at the end it is really easy. let me know if you are interested, so I can share details and won't pollute this thread.

**Comment by eluchsinger** [comment] 2020-03-06 10:28
@okovalov  of course, I'm interested in the solution. How would you pollute this thread with a solution?

**Comment by SupunSam** [comment] 2020-03-16 07:33
> Whoops, I should have come back here and posted my solution! In my case it was a corrupted install, maybe from the sync settings extension. What I discovered is that the extensions were still hanging around even after I uninstalled them from the editor. They get cached in ~/.vscode-server/extensions. I deleted everything in that directory, opened up vscode and reinstalled my extensions, and everything started working again. Hopefully this solves your problem too.

@parkerault . Your Solution worked for me. I also think that this issue relies with the Sync extension.
