### ISSUE TITLE
Space between arrays on single line

### ISSUE THREAD

**Issue by DoCode** [prettier/prettier-vscode#259] opened 2017-11-09 12:15 UTC
How to add spaces inside brackets of arrays on single line?

```json
{
  "items": [ "item1", "item2" ]
}
```

**Comment by CiGit** [comment] 2017-11-09 14:21
This is a prettier feature, It was decided to remove spacing in brackets / parens.
Duplicate of #35 
You can read more about it in prettier/prettier#296

**Closed by CiGit** 2017-11-09 14:21 UTC
Labels: dependency, duplicate

**Comment by DoCode** [comment] 2017-11-09 14:50
Thank you.

**Comment by CiGit** [comment] 2017-11-09 15:19
Forgot to mention, if you really want it, you can use 'eslintIntegration' with https://eslint.org/docs/rules/space-in-brackets

**Comment by DoCode** [comment] 2017-11-09 16:15
@CiGit thanks for the hints!
But with this settings in VSCode it does not work on formatting the document:

```json
  "eslint.enable": true,
  "eslint.options": {
    "rules": {
      "array-bracket-spacing": ["error", "always", { "objectsInArrays": false }]
    }
  },
  "prettier.eslintIntegration": true
```

**Comment by CiGit** [comment] 2017-11-09 16:56
Good point. We do not read from this settings.

You have to put them in a file .eslintrc

**Comment by DoCode** [comment] 2017-11-09 17:08
The same behavior when I place a `.eslintrc` file with this content in a directory of json files:
```json
{
  "rules": {
    "array-bracket-spacing": ["always"]
  }
}
```

**Comment by CiGit** [comment] 2017-11-09 17:27
My bad, I've read your initial post really badly. Thought it was JS not JSON.
Sadly, I've no workaround for you.
