### ISSUE TITLE
If prettier is installed locally as a nested dependency, this extension won't find it

### ISSUE THREAD

**Issue by mbrowne** [prettier/prettier-vscode#647] opened 2018-11-20 21:53 UTC
Currently this extension checks for a locally installed version of prettier but it only finds it if it's explicitly mentioned in the `dependencies` or `devDependencies` of the `package.json` for the project. I've created a fork that allows it to work for nested dependencies too.

Example use case: at my company, we have a separate code-quality package with all of our linting/formatting configuration, and prettier is a dependency of the code-quality package. With the current behavior, our pre-commit can end up running a different version of prettier than the version used by this extension (this happened today because our local prettier version was slightly behind the version bundled with this extension).

**Comment by mbrowne** [comment] 2018-11-20 21:57
PR: https://github.com/prettier/prettier-vscode/pull/648

**Comment by CiGit** [comment] 2018-11-27 12:14
This is something we removed. 
#67

It is easier to add prettier as a dependency instead of removing it from a dependency.
Seems your issue could be fixed once we allow to specify a path to prettier.

**Comment by mbrowne** [comment] 2018-11-27 14:59
Ideally we would like the version of prettier to be determined by the shared code-quality package. But if it were possible to specify a path to prettier, that would be a good solution as long as it's possible to do so on a per-project level.

**Comment by ntotten** [comment] 2019-10-27 21:37
Duplicate of #232

**Closed by ntotten** 2019-10-27 21:37 UTC
Labels: bug
