### ISSUE TITLE
How should I use a file in vscode's User folder in configPath?

### ISSUE THREAD

**Issue by maple3142** [prettier/prettier-vscode#1049] opened 2019-11-13 06:02 UTC
I can't find a way to use a file located in `User` folder in configPath, is there a way to do that?
`User` is a folder located at `%APPDATA%\Code\User`, `/Library/Application Support/Code/User` or `~/.config/Code/User`.

I want to do that because [Settings Sync](https://github.com/shanalikhan/code-settings-sync) only allow you to sync files in that folder, and new changes in 3.0.0 require me to create a `.prettier` in home directory, which doesn't sync across machines.

**Comment by GeoGuo34** [comment] 2019-11-13 07:07
@maple3142 Add filename in path, eg.```folder\.prettierrc```, and ```%APPDATA%``` won't be recognized.

**Comment by maple3142** [comment] 2019-11-13 07:46
@GeoGuo34 But that would require to use absolute path, which won't work after sync to another machine.

**Comment by SvenZhao** [comment] 2019-11-13 09:27
@GeoGuo34  I have the same problem, I need to synchronize my own style configuration when the local configuration file does not exist

**Comment by ntotten** [comment] 2019-11-13 11:15
Duplicate of #1045

**Closed by ntotten** 2019-11-13 11:15 UTC
Labels: bug

**Comment by maple3142** [comment] 2019-11-13 11:49
@ntotten No, this issue is different from #1045 
I can get that working by leaving `configPath` empty and create a `.prettierrc` at home directory. The problem is I am trying to reference `User` directory in vscode's data dir, and there is no way except for using absolute path to use a file there.

**Comment by jefflundberg** [comment] 2019-11-13 20:07
I'm having the same issue. v3 broke the ability to sync Prettier settings through the Settings Sync extension.

I thought perhaps that I could [share my configuration through package.json](https://prettier.io/docs/en/configuration.html#sharing-configurations) but that doesn't seem to work either (either that or I'm doing it wrong)

What I ended up doing (and it seems to be working) is to place a ```.prettierrc``` file in the root of my development directory. I just have a ```c:\git``` directory where I clone all my repos into so this works in my case. I have one ```.prettierrc``` file sitting in ```c:\git```, with an empty ```prettier.configPath``` in vscode ```settings.json```.

Prettier will look in the current directory and all the way up the hierarchy for a config file. 
[Per the Prettier documentation](https://prettier.io/docs/en/configuration.html)
>The configuration file will be resolved starting from the location of the file being formatted, and searching up the file tree until a config file is (or isn't) found.

Now I just have to manually sync that file across various development environments.

**Comment by ntotten** [comment] 2019-11-13 20:35
Two things:

1. In the latest v3 relaase, we added back the old vscode configuration so you can just go back to that method.
2. I just fixed a bug to support relative home directory paths so you should be able to set the `prettier.configPath` to `~/.prettierrc` now.

Make sure you are on version 3.5.0 or above.

**Comment by jefflundberg** [comment] 2019-11-13 22:38
Thanks @ntotten! Is the plan to keep the vscode configuration options or is the intention to remove that in the future?
