### ISSUE TITLE
Implement the format on type interface

### ISSUE THREAD

**Issue by andrecasal** [prettier/prettier-vscode#980] opened 2019-10-02 12:04 UTC
VS Code implements the [`OnTypeFormattingEditProvider`](https://github.com/microsoft/vscode/blob/d859157d39a846ce58d99f22c8011f5d6a513959/src/vs/vscode.d.ts#L3080) interface which allows us to format code as we type it using VS Code's setting `"editor.formatOnType": true`. However, as explained in [#81235](https://github.com/microsoft/vscode/issues/81235#issue-496398042) prettier-vscode does not make use of the `OnTypeFormattingEditProvider` interface for this feature to work.

I'd like prettier-vscode to use this interface so that format on type works in VS Code.

The alternative is turning the feature off.

**Comment by ntotten** [comment] 2019-10-27 21:21
Duplicate of #142

**Closed by ntotten** 2019-10-27 21:21 UTC
Labels: enhancement
