### ISSUE TITLE
Is there a way to tell specify the files to format (not the ones to ignore!)

### ISSUE THREAD

**Issue by electrotype** [prettier/prettier-vscode#308] opened 2017-12-18 00:40 UTC
I know of `prettier.ignorePath`, `prettier.disableLanguages` and the `.prettierignore` file. But they all *exclude* some files.

I want to be able to tell the Prettier extension *to only format .ts and .json files*. Is this possible?

**Comment by jsieler** [comment] 2018-02-09 10:32
Looking for same solution, because i want to format .EJS files, which also have HTML syntax.

**Comment by CiGit** [comment] 2018-02-09 10:47
`["javascript","javascriptreact","typescript","typescriptreact","json","jsonc","css","postcss","less","scss","graphql","markdown","vue"]` these are all supported languages.

You will have to add every languages you **don't** want in `prettier.disableLanguages`

In @electrotype 's example: `prettier.disableLanguages:
 ["javascript","javascriptreact","typescriptreact","css","postcss","less","scss","graphql","markdown","vue"]` ie everything but the ones you want : `"typescript","json","jsonc"`

It's not possible to add a language. HTML is not supported by prettier yet

**Comment by ecbrodie** [comment] 2018-03-31 23:03
I am going to throw my weight into this issue too. What brought me here was the automatic formatting that this extension was applying to my project's `README.md` file. Specifically, I was not a big fan of the 3 spaces that were automatically being added in-between bullet list points and the first character of that list item.

I had set `editor.formatOnSave = true` so that Prettier would be applied to all files where I wish for it to be applied. In my React project, I imagined that to be just files ending in `.js` and `.jsx`. I didn't expect Markdown files to also be formatted. I suppose that the root cause of this problem is that there is no universal way to map the glob of files that we apply Prettier to (in my case, through the args of the `prettier` command run in the `"lint"` script of `package.json`) to this extension. I interpret Prettier on its own as being an opt-in tool, as it won't actually format anything unless you pass it a specific glob. Whereas, this extension is acting like an opt-out tool, where you have to specifically exclude things you don't want to be touched. As such, my current workaround is to set the configuration `""prettier.disableLanguages": ["markdown"]`.

I also want to note that there may be a relationship between this issue and https://github.com/prettier/prettier-vscode/issues/402, where the author is looking for more support for automatic Prettier formatting on Markdown documents. Any solution that is devised should be sufficient to handle both issues' concerns.

**Comment by OliverJAsh** [comment] 2018-08-14 16:00
👍 to this idea. My reasoning: on several projects now I have had to duplicate config between the Prettier CLI (globs) and the VSCode workspace settings for the Prettier extension (`formatOnSave` for specific languages).

Ideally, I could define an *include* glob once (like you can for excludes), and have both my IDE and the CLI honour that.

**Comment by Ciantic** [comment] 2019-03-11 13:52
You can also do this in workspace `settings.json`:

```
{
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "[markdown]": {
        "editor.formatOnPaste": false,
        "editor.formatOnSave": false,
        "editor.formatOnType": false
    }
}
```

**Comment by ntotten** [comment] 2019-08-09 14:38
This issue appears to be resolved as such I am closing it. If you are still having problems please feel free to reopen.

**Closed by ntotten** 2019-08-09 14:38 UTC
