### ISSUE TITLE
Allow to specify path of .prettierrc.json

### ISSUE THREAD

**Issue by aryzing** [prettier/prettier-vscode#431] opened 2018-04-28 18:46 UTC
It's quite common to have all config files in their own directory. However, if `.prettierrc` is not at the root fo the project, it doesn't get picked up. The prettier CLI allows for this with the [`--config`](https://prettier.io/docs/en/cli.html#find-config-path-and-config) flag.

**Comment by CiGit** [comment] 2018-04-30 13:45
Thanks @gakada !
Let close that one as duplicate of #254

**Closed by CiGit** 2018-04-30 13:45 UTC
