### ISSUE TITLE
Prettier doesnt format any type of file when was upgraded to 8.0.0

### ISSUE THREAD

**Issue by Peppoderosa** [prettier/prettier-vscode#2031] opened 2021-06-22 15:07 UTC
When prettier was auto upgrade to 8.0.0, the formatter stop working for ever type file that I try to use. I didnt know what was happening, so I downgrade to 7.1.1 and works fine. is the problem some settings or whatever with my vs code?

**Comment by lamartm** [comment] 2021-06-22 15:11
Yeah having same problems with 8.0 myself, Downgrading to 7.1.1 seems to do the trick

**Comment by ljosberinn** [comment] 2021-06-22 15:11
Seeing the same:
![image](https://user-images.githubusercontent.com/29307652/122950556-d487b100-d37c-11eb-991d-6ca2dc959a0c.png)

Error Log in Output - Log (Extension Host):

```sh
[2021-06-22 17:09:29.037] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-06-22 17:09:29.037] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/gerr.it/.vscode-insiders/extensions/esbenp.prettier-vscode-8.0.0/dist/extension
[2021-06-22 17:09:29.114] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-22 17:09:29.114] [exthost] [error] Error: Cannot find module 'prettier'
Require stack:
- c:\Users\gerr.it\.vscode-insiders\extensions\esbenp.prettier-vscode-8.0.0\dist\extension.js
- c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js
- c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js
- c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.s._load (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:27895)
    at Function.b._load (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:24647)
    at Function.c._load (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:59141)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at v (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:4:698)
    at Object.2392 (c:\Users\gerr.it\.vscode-insiders\extensions\esbenp.prettier-vscode-8.0.0\external "util":1:26)
    at outputChannel (c:\Users\gerr.it\.vscode-insiders\extensions\esbenp.prettier-vscode-8.0.0\dist\extension.js:1:72851)
    at Object.9854 (c:\Users\gerr.it\.vscode-insiders\extensions\esbenp.prettier-vscode-8.0.0\src\LoggingService.ts:7:11)
    at r (c:\Users\gerr.it\.vscode-insiders\extensions\esbenp.prettier-vscode-8.0.0\dist\extension.js:1:72851)
    at c:\Users\gerr.it\.vscode-insiders\extensions\esbenp.prettier-vscode-8.0.0\src\extension.ts:9:1
    at c:\Users\gerr.it\.vscode-insiders\extensions\esbenp.prettier-vscode-8.0.0\dist\extension.js:1:74003
    at Object.<anonymous> (c:\Users\gerr.it\.vscode-insiders\extensions\esbenp.prettier-vscode-8.0.0\dist\extension.js:1:74024)
    at Module.u._compile (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.s._load (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:27895)
    at Function.b._load (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:24647)
    at Function.c._load (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:59141)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.t [as __$__nodeRequire] (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:5:101)
    at h._loadCommonJSModule (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:26053)
    at h._doActivateExtension (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12626)
    at h._activateExtension (c:\Users\gerr.it\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11685)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```
prettier however is installed in the workspace

**Comment by kevin-lindsay-1** [comment] 2021-06-22 15:18
@Peppoderosa looks like this might be a duplicate of https://github.com/prettier/prettier-vscode/issues/2029

**Comment by shikelong** [comment] 2021-06-22 15:18
+1

**Comment by PhongPhinguin** [comment] 2021-06-22 15:24
Downgrade down to 7.1.1 also seem work for me, too.

**Comment by shadoworion** [comment] 2021-06-22 15:48
+1

**Comment by Peppoderosa** [comment] 2021-06-22 15:54
Just downgrading to 7.1.1, smell like a solution. Thanks.

**Closed** 2021-06-22 15:53 UTC

**Comment by tgroutars** [comment] 2021-06-22 16:15
@Peppoderosa How is it a solution? The bug still exists in 8.0.0. I'm fine with downgrading to 7.1.1 for now but this issue should still be fixed in v8
