### ISSUE TITLE
Apparently 'eslint -fix' not being called for *.svelte files with prettiereslintIntegration

### ISSUE THREAD

**Issue by SteveALee** [prettier/prettier-vscode#840] opened 2019-05-24 16:57 UTC
I have the extension set to use prettiereslint integration and for a `.js` file the `eqeqeq` error is getting fixed correctly on file save.

However the same code in a `.svelte` file is not working.
 
`eslint-plugin-svelte3` is installed to handle the `.svelte` file and `eslint --fix` works fine as does clicking on the lightbulb in vscode. It's just the fix on file save that is not working.

There's a [project here](https://github.com/SteveALee/sveltejs-template/tree/eslint-plugin-svelte3) that exhibits the problem. see the 2 files in `src/`

FYI I previously raised an issue on [eslint-plugin-svelt3](https://github.com/sveltejs/eslint-plugin-svelte3/issues/14) and it appears the `lint --fix `may not be being called by prittier on file save. Perhaps due to file extension?

**Comment by ntotten** [comment] 2019-08-12 17:08
This is our parser inference. The extension is likely not detecting the type of the file correctly. As a workaround, you can specify the parser in a prettier config file "overrides" property and set the parser. See: https://prettier.io/docs/en/options.html#parser

```
{
	// ...
	"overrides":[{
		"files": "*.html", // replace this by more specific extension if needed
      	"options": {
        	"parser": "html"
      	}
	}]
}
```

Duplicate of #487

**Closed by ntotten** 2019-08-12 17:08 UTC
