### ISSUE TITLE
SCSS Map - Removes empty lines, Adding Indent, Losing variable

### ISSUE THREAD

**Issue by nicholasp** [prettier/prettier-vscode#856] opened 2019-06-21 09:40 UTC
v1.9.0

**Input**
```scss
$colors: (
  white: #fff,
  
  bg-grey: #e5e5e5,
  bg-grey-dark: #ccc,
  bg-grey-hover: #f1f1f1,
  
  text: #2e2e2e,
  text-light: #848484,
  text-dark: #111,
  // ##############################
  success: rgb(43, 179, 118),
  error: rgb(194, 47, 47),
  warn: rgb(196, 88, 16),
  info: rgb(29, 111, 167),
  // ##############################
  check1: rgb(20, 16, 77),
  check2: rgb(184, 51, 177)
);
```

**Output**
```scss
$colors: (
  white: #fff,
  bg-grey: #e5e5e5,
  bg-grey-dark: #ccc,
  bg-grey-hover: #f1f1f1,
  text: #2e2e2e,
  text-light: #848484,
  text-dark: #111,
  // ##############################
    success: rgb(43, 179, 118),
  error: rgb(194, 47, 47),
  warn: rgb(196, 88, 16),
  info: rgb(29, 111, 167),
  // ##############################check1: rgb(20, 16, 77),
  check2: rgb(184, 51, 177)
);
```

**Comment by ntotten** [comment] 2019-08-12 16:00
This is our parser inference. The extension is likely not detecting the type of the file correctly. As a workaround, you can specify the parser in a prettier config file "overrides" property and set the parser. See: https://prettier.io/docs/en/options.html#parser

{
	// ...
	"overrides":[{
		"files": "*.html", // replace this by more specific extension if needed
      	"options": {
        	"parser": "html"
      	}
	}]
}

Duplicate of #487

**Closed by ntotten** 2019-08-12 16:00 UTC

**Comment by jpdutoit** [comment] 2019-10-08 13:29
I don't think this is a parser inference problem. I have set the parser to SCSS here, and it mangles the it pretty badly.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASARgGwIYAskAEAFADpQEED0lBAwhALYMIxkWoCWkUAjIQK4AnTEUpdoAZzHceAOgAOUAOYBKADRsCnbgCYBw0eKhSjOhcvVlN1Oo2axN26AGZ9I6ZI+9zqjeS1GACxuhtwmuj4qZCoUIGogEPIwHJLIoNiCghAA7gAKGQgSyCDYAG4QHAAmcSDogthgANZwMADK8g0cysgwgvxw8bgwDJgA6rgc8BIdYHCthZMcpZMAnsVgEkXxXRJwgjC59UoM2MgAZtiYu-EAVhIAHgBC9U0trdjMADJdcOeX1yA7vdWl0lJg4ABFfgQeB-K4DEAdQS7QTFCQbLaIwRdGCjKowXDIAAcAAZ4vIsrtRvV5MUKXAUaVfvEAI7Q+CHRJFFDYCQAWigcDglWFNUEcDZHHFh2wx1OSAu8PiuwYHB6fQRElB4KhMN+Cv+CJg2HQeMqBOQOnivWwHEwoPoTHlICg0GZIH4uwAKibuYrdgBfANAA

Compare it with this version, which looks correct:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASARgGwIYAskAEAFADpQEED0lBAwhALYMIxkWoCWkUAjIQK4AnTEUpdoAZzHceAOgAOUAOYBKADRsCnbgCYBw0eKhSjOhcvVlN1Oo2axN26AGZ9I6ZI+9zqjeS1GACxuRLgwMPJI1EYmuj4qZCoUIGogEPIwHJLIoNiCghAA7gAKeQgSyCDYAG4QHAAmKSDogthgANZwMADK8m0cysgwgvxwqWEMmADquBzwEn1gcN3lcxzVcwCelWASFakDEnCCMMWtSgzYyABm2JhHqQBWEgAeAEKtHV3d2MwAMgM4Dc7g8QM8Xt0BkpMHAAIr8CDwYH3MYgPqCI6CSoSXb7NGCAYwKYNGC4ZAADgADKl5AUjlNWvJKrS4JjqkDUgBHBHwM7pCoobASAC0UDgcHqEqagjg3I4MrO2AuVyQtxRqSODA4QxGqIkUJh8MRQNVINRMGw6GJ9VJyB0qWG2A4mCh9CYKpAUGgHJA-COABVLQK1UcAL6hoA
