### ISSUE TITLE
cannot format files in vscode

### ISSUE THREAD

**Issue by gz65555** [prettier/prettier-vscode#1619] opened 2020-10-23 03:47 UTC
![image](https://user-images.githubusercontent.com/6926263/96953752-7cb25500-1524-11eb-8c1c-fcd1f2a2addd.png)

Using `npx prettier <file path>` succeed.

I can't format any file in vscode. How can I get log from this plugin?  I don't know how to get more information. I just change my computer to mac 16 inch, os 10.15.5.

**Comment by DreamBuddy** [comment] 2020-10-23 07:04
me too,can not use after I upgrdate vscode

**Comment by Leafl** [comment] 2020-10-25 01:59
Are you using VS 1.50 or later?
Check to see if 
`"prettier.requireConfig": false,`
in the settings.json file. 
Duplicate of #1598

**Comment by gz65555** [comment] 2020-10-27 11:15
i use Migration Assistant migrate vscode to a new mac, maybe it's a problem of permission.

**Comment by gz65555** [comment] 2020-10-27 11:49
> me too,can not use after I upgrdate vscode

finnally, it works. I remove `~/.vscode/extensions` directory, reinstall vscode and prettier-vscode.

**Closed** 2020-10-27 11:50 UTC
