### ISSUE TITLE
Prettier formats on paste even when disabled in preferences

### ISSUE THREAD

**Issue by ciaoben** [prettier/prettier-vscode#374] opened 2018-02-19 10:15 UTC
First, thanks for the great extension.

I am encountering a problem, I have `formatOnPaste: false`, but this happens:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4526061/36372549-a8f939c4-1565-11e8-93d8-3538b86244c1.gif)

As you can see, as soon as I paste, the content format (without respecting prettier config), and then on save, everything works fine. 

I have plugin version 1.1.3, vscode 1.20.1, and prettier is version 1.9.1.

I expect that on paste nothing happens since my config  says `formatOnPaste: false`.

**Comment by RobinMalfait** [comment] 2018-02-19 17:35
I wonder if you have it enabled by accident in your workspace settings?

**Comment by CiGit** [comment] 2018-02-22 14:29
I don't see on this recording what's wrong...
cmd + S isn't that 'save' ?

**Comment by danderu** [comment] 2018-03-14 11:04
I'm also having the same issue. I've realized also that it formats my code but not following my `.prettierrc` rules.

**Comment by CiGit** [comment] 2018-03-17 10:45
@danderu If you disable prettier-vscode, does it also happen ?

**Comment by vinay03** [comment] 2018-08-22 06:25
Same Issue >.<

**Comment by CiGit** [comment] 2018-08-24 10:08
Stalled closing

**Closed by CiGit** 2018-08-24 10:08 UTC
Labels: need more info

**Comment by ackvf** [comment] 2019-03-13 12:19
I can confirm that in a fresh workspace with an unformated code, the action of pasting re-formats the whole code.
**prettier disabled**
![prettier01-disabled](https://user-images.githubusercontent.com/2313018/54278149-eb31e180-4591-11e9-8875-4e1b660b3727.gif)

**prettier enabled**
![prettier02-enabled](https://user-images.githubusercontent.com/2313018/54278172-f6850d00-4591-11e9-88ba-fffe4d649e81.gif)

**project setup**
Fresh workspace with zero files, zero workspace settings and only prettier enabled
![prettier00-setup](https://user-images.githubusercontent.com/2313018/54278191-056bbf80-4592-11e9-8f4c-9fd2ece9dcf6.jpg)



**code**
```
import React from "react";

const TableCell = props => null;
const TableHead = props => null;
const TableRow = props => null;
const NativeSelect = props => null;
const Input = props => null;
const FormControl = props => null;

const TableHeader = props => {
  return (
    <TableHead style={{ fontFamily: "Poppins", color: "#4a4a4a" }}>
      <TableRow style={{ backgroundColor: "#f3f3f3" }}>
        <TableCell align="left" style={{ fontWeight: "600", fontSize: "13px", paddingLeft: "31px" }}>
          Filter by
        </TableCell>
        <TableCell align="right" padding="none">
          <FormControl>
            <NativeSelect
              value={props.universityFilter}
              onChange={props.handleFilterChange("universityFilter")}
              input={<Input name="universityFilter" />}
              style={{ fontSize: "12px", fontWeight: "500", color: "#818181" }}
            >
              <option value="">All</option>
              {props.universities.map(option => (
                <option value={option.uuid} key={option.uuid}>
                  {option.name}
                </option>
              ))}
              {console.debug('noop')}
            </NativeSelect>
          </FormControl>
        </TableCell>
      </TableRow>
    </TableHead>
  );
};

export default TableHeader;
```

Even though I have no idea what I did there, these settings disabled the formatting on paste
```
  "prettier.eslintIntegration": true,
  "prettier.tslintIntegration": true,
  "prettier.printWidth": 120,
  "prettier.singleQuote": true,
  "prettier.stylelintIntegration": true,
  "prettier.trailingComma": "all",
  "prettier.requireConfig": true,
```

**Comment by gknapp** [comment] 2019-06-28 15:33
I've a similar problem. Disabling prettier in a particular workspace is ignored and still continues to format on save.

I also have a `.prettierignore` file in my project root but it too appears to be ignored.

**Comment by 7iomka** [comment] 2019-10-14 12:44
the same problem

**Comment by ackvf** [comment] 2019-12-30 11:10
@CiGit Do you still require more information?

**Comment by ntotten** [comment] 2020-01-03 18:05
@gknapp If prettier is disable in the workspace this cannot possibly an issue with the prettier extension.

**Comment by ntotten** [comment] 2020-01-03 18:07
@ackvf I can't reproduce this. Please create a github project that contains the configuration and full repro steps to duplicate this issue. I tried your code and pasted with format on paste disabled and no formatting happens.
