### ISSUE TITLE
Doesn't respect whitespace settings from .editorconfig

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier-vscode#213] opened 2017-09-06 08:48 UTC
I have all whitespace settings in `.editorconfig` still they seem to not be respected by default.

I need to replicate same settings with prettier settings, which is more limited as e.g. I cannot provide different settings for js files and json.

**Comment by azz** [comment] 2017-09-06 09:13
> I cannot provide different settings for js files and json.

Yes you can:

```
// .prettierrc
{
  "printWidth": 100,
  "overrides": [
    {
      "files": "*.json",
      "options": { "printWidth": 120 }
    }
  ]
}
```

See https://github.com/prettier/prettier#configuration-file for more info, and https://github.com/prettier/prettier/issues/42 for prettier tracking EditorConfig support.

**Comment by medikoo** [comment] 2017-09-06 09:17
Still duplicating same configuration in two files is not great. I want to avoid having `.prettierrc` at all. Technically all it needs to know is in `.editorconfig` and eslint config

**Comment by CiGit** [comment] 2017-09-06 11:37
I'm wondering how it will work with eslint + editorconfig :confused:

**Comment by thorn0** [comment] 2017-11-10 23:10
Duplicate of #81

**Comment by CiGit** [comment] 2017-11-21 21:33
Closing as duplicate. Thanks @thorn0

**Closed by CiGit** 2017-11-21 21:33 UTC
